program redeye_besleyCopp;

uses
  Forms,
  PBWin7 in 'PBWin7.pas',
  pbMainMenu in 'pbMainMenu.pas' {frmpbMainMenu},
  pbluCustomers in 'pbluCustomers.pas' {frmpbluCustomers},
  pbluSuppliers in 'pbluSuppliers.pas' {frmpbluSuppliers},
  pbDatabase in 'pbDatabase.pas' {dmBroker: TDataModule},
  pbLogin in 'pbLogin.pas' {frmpbLogin},
  pbEnvSel in 'pbEnvSel.pas' {frmpbEnvSel},
  pbCustomerDm in 'pbCustomerDm.pas' {dtmdlCustomers: TDataModule},
  pbluCustOrders in 'pbluCustOrders.pas' {frmpbluCustOrders},
  pbOrdersDm in 'pbOrdersDm.pas' {dtmdlOrders: TDataModule},
  pbSupplierDm in 'pbSupplierDm.pas' {dtmdlSuppliers: TDataModule},
  pbluOrdersSearch in 'pbluOrdersSearch.pas' {frmpbluOrdersSearch},
  PBMaintCust in 'PBMaintCust.pas' {PBMaintCustFrm},
  CCSPrint in '..\CCSCommonD7\CCSPrint.pas',
  pbluCustBrSelect in 'pbluCustBrSelect.pas' {frmpbluCustBrSelect},
  PBImages in 'PBImages.pas' {PBImagesFrm},
  PBDBMemo in 'PBDBMemo.pas' {PBDBMemoFrm},
  PBDelivNotes in 'PBDelivNotes.pas' {PBDelivNotesFrm},
  PBMaintCompany in 'PBMaintCompany.pas' {PBMaintCompanyFrm},
  pbluSupplierSelect in 'pbluSupplierSelect.pas' {frmpbluSupplierSelect},
  PBLUPrdTyp in 'PBLUPrdTyp.pas' {PBLUPrdTypFrm},
  PBMaintRep in 'PBMaintRep.pas' {PBMaintRepFrm},
  PBLURep in 'PBLURep.pas' {PBLURepFrm},
  PBLUAdHoc in 'PBLUAdHoc.pas' {PBLUAdHocFrm},
  PBLUCust in 'PBLUCust.pas' {PBLUCustFrm},
  PBLUPrdTypCap in 'PBLUPrdTypCap.pas' {PBLUPrdTypCapFrm},
  PBLUPrdTypOChg in 'PBLUPrdTypOChg.pas' {PBLUPrdTypOChgFrm},
  PBLUPrdTypQu in 'PBLUPrdTypQu.pas' {PBLUPrdTypQuFrm},
  PBLUPrdTypQuList in 'PBLUPrdTypQuList.pas' {PBLUPrdTypQuListfrm},
  PBLURepNom in 'PBLURepNom.pas' {PBLURepNomFrm},
  PBLUSConta in 'PBLUSConta.pas' {PBLUSContaFrm},
  PBLUSupBrch in 'PBLUSupBrch.pas' {PBLUSupBrchFrm},
  PBLUSupp in 'PBLUSupp.pas' {PBLUSuppFrm},
  PBMaintAdHoc in 'PBMaintAdHoc.pas' {PBMaintAdHocFrm},
  PBMaintGroups in 'PBMaintGroups.pas' {PBMaintGroupsFrm},
  PBMaintGroupsDets in 'PBMaintGroupsDets.pas' {PBMaintGroupsDetsFrm},
  PBMaintPrdTyp in 'PBMaintPrdTyp.pas' {PBMaintPrdTypFrm},
  PBMaintPrdTypCap in 'PBMaintPrdTypCap.pas' {PBMaintPrdTypCapFrm},
  PBMaintPrdTypOChg in 'PBMaintPrdTypOChg.pas' {PBMaintPrdTypOChgFrm},
  PBMaintPrdTypQu in 'PBMaintPrdTypQu.pas' {PBMaintPrdTypQuFrm},
  PBMaintRepNom in 'PBMaintRepNom.pas' {PBMaintRepNomFrm},
  PBMaintSConta in 'PBMaintSConta.pas' {PBMaintSContaFrm},
  PBMaintSupBrch in 'PBMaintSupBrch.pas' {PBMaintSupBrchFrm},
  PBMaintSupp in 'PBMaintSupp.pas' {PBMaintSuppFrm},
  PBMaintSuppCap in 'PBMaintSuppCap.pas' {PBMaintSuppCapFrm},
  PBMaintSpecIns in 'PBMaintSpecIns.pas' {PBMaintSpecInsFrm},
  PBLUSpecIns in 'PBLUSpecIns.pas' {PBLUSpecInsFrm},
  PBLUAddCharges in 'PBLUAddCharges.pas' {PBLUAddChrgFrm},
  PBLUPriceUnit in 'PBLUPriceUnit.pas' {PBLUPriceUnitFrm},
  PBMaintAddChrgs in 'PBMaintAddChrgs.pas' {PBMaintAddChrgsFrm},
  PBMaintPriceUnit in 'PBMaintPriceUnit.pas' {PBMaintPriceUnitFrm},
  CCSCommon in '..\CCSCommonD7\CCSCommon.pas',
  PBLUStandSize in 'PBLUStandSize.pas' {PBLUStandSizeFrm},
  PBMaintPaper in 'PBMaintPaper.pas' {PBMaintPaperFrm},
  PBMaintStandSize in 'PBMaintStandSize.pas' {PBMaintStandSizeFrm},
  PBLUArtwrkTyp in 'PBLUArtwrkTyp.pas' {PBLUArtwrkTypFrm},
  PBMaintArtwrkTyp in 'PBMaintArtwrkTyp.pas' {PBMaintArtwrkTypFrm},
  PBMaintOpsDet in 'PBMaintOpsDet.pas' {PBMaintOpsDetFrm},
  PBLUOps in 'PBLUOps.pas' {PBLUOpsFrm},
  PBAuditControl in 'PBAuditControl.pas' {PBAuditControlFrm},
  PBMaintInterf in 'PBMaintInterf.pas' {PBMaintInterfFrm},
  PBMaintLastNos in 'PBMaintLastNos.pas' {PBMaintLastNosFrm},
  PBMaintOpsDetPass in 'PBMaintOpsDetPass.pas' {PBMaintOpsDetPassFrm},
  PBMaintVATCode in 'PBMaintVATCode.pas' {PBMaintVATCodeFrm},
  PBAuditDM in 'PBAuditDM.pas' {PBAuditDataMod: TDataModule},
  PBLUBranch in 'PBLUBranch.pas' {PBLUBranchFrm},
  PBLUCConta in 'PBLUCConta.pas' {PBLUCContaFrm},
  PBLUCContaEvents in 'PBLUCContaEvents.pas' {PBLUCContaEventsFrm},
  PBLUCRep in 'PBLUCRep.pas' {PBLUCRepFrm},
  PBLUFormRef in 'PBLUFormRef.pas' {PBLUFormRefFrm},
  PBMaintBranch in 'PBMaintBranch.pas' {PBMaintBranchFrm},
  PBMaintCConta in 'PBMaintCConta.pas' {PBMaintCContaFrm},
  PBMaintContApp in 'PBMaintContApp.pas' {PBMaintContAppfrm},
  PBMaintCRep in 'PBMaintCRep.pas' {PBMaintCRepFrm},
  PBMaintFormRef in 'PBMaintFormRef.pas' {PBMaintFormRefFrm},
  PBMaintPOrd in 'PBMaintPOrd.pas' {PBMaintPOrdFrm},
  PBIntSelDM in 'PBIntSelDM.pas' {dmIntSel: TDataModule},
  PBPOObjects in 'PBPOObjects.pas',
  PBPODataMod in 'PBPODataMod.pas' {PBPODM: TDataModule},
  DateSelV5 in 'DateSelV5.pas' {DateSelV5Form},
  PBJobBagDM in 'PBJobBagDM.pas' {dmJobBag: TDataModule},
  PBMaintPOrdLine in 'PBMaintPOrdLine.pas' {PBMaintPOrdLineFrm},
  PBMaintPOrdLineDeliv in 'PBMaintPOrdLineDeliv.pas' {PBMaintPOrdLineDelivFrm},
  PBMaintPOrdLineExtChg in 'PBMaintPOrdLineExtChg.pas' {PBMaintPOrdLineExtChgFrm},
  PBLUProofHistN in 'PBLUProofHistN.pas' {PBLUProofHistNFrm},
  PBPOAddDtls in 'PBPOAddDtls.pas' {PBPOAddDtlsFrm},
  PBMaintPOAddNotes in 'PBMaintPOAddNotes.pas' {PBMaintPOAddNotesFrm},
  PBPartDescDg in 'PBPartDescDg.pas' {PBPartDescDlg},
  PBMaintPOrdLInactive in 'PBMaintPOrdLInactive.pas' {PBMaintPOrdLInactiveFrm},
  PBLUReasCode in 'PBLUReasCode.pas' {PBLUReasCodeFrm},
  PBMaintReasCode in 'PBMaintReasCode.pas' {PBMaintReasCodeFrm},
  PBMaintPOrdLineCallOff in 'PBMaintPOrdLineCallOff.pas' {PBMaintPOrdLineCallOffFrm},
  PBLUCustFormRef in 'PBLUCustFormRef.pas' {PBLUCustFormRefFrm},
  PBMaintPOrdLView in 'PBMaintPOrdLView.pas' {PBMaintPOrdLViewFrm},
  PBMaintIntNote in 'PBMaintIntNote.pas' {PBMaintIntNoteFrm},
  PBRSPOrdN in 'PBRSPOrdN.pas' {PBRSPOrdNFrm},
  CCSDataBroker in '..\CCSCommonD7\CCSDataBroker.pas' {DataBroker: TDataModule},
  LetterDM in '..\PAGEDESIGNER\LetterDM.pas' {dmLetter: TDataModule},
  PDLetter in '..\PAGEDESIGNER\PDLetter.pas',
  CCSPress in '..\CCSCommonD7\CCSPress.pas' {frmPrintingPress},
  CCSDevil in '..\CCSCommonD7\CCSDevil.pas',
  Compositor in '..\CCSCommonD7\Compositor.pas' {Compositor},
  PBDBPOrdLtr in 'PBDBPOrdLtr.pas' {dbPOrdLtr: TDataModule},
  PBFaxList in 'PBFaxList.pas' {PBFaxListFrm},
  PBEmailList in 'PBEmailList.pas' {PBEmailListFrm},
  pbluCustStock in 'pbluCustStock.pas' {frmpbluCustStock},
  pbStockDm in 'pbStockDm.pas' {dtmdlStock: TDataModule},
  pbLuBranches in 'pbLuBranches.pas' {frmpbluBranches},
  pbluCustEnquiries in 'pbluCustEnquiries.pas' {frmpbluCustEnquiries},
  pbEnqsdm in 'pbEnqsdm.pas' {dtmdlEnqs: TDataModule},
  pbluContacts in 'pbluContacts.pas' {frmpbluContacts},
  pbluEnqsSearch in 'pbluEnqsSearch.pas' {frmpbluEnqsSearch},
  STLUStkMvmnts in 'STLUStkMvmnts.pas' {STLUStkMvmntsFrm},
  STLUStkLoc in 'STLUStkLoc.pas' {STLUStkLocFrm},
  STLUStkBinLots in 'STLUStkBinLots.pas' {STLUStkBinLotsFrm},
  STLUStkSales in 'STLUStkSales.pas' {STLUStkSalesFrm},
  STLUStkProduction in 'STLUStkProduction.pas' {STLUStkProductionFrm},
  STLUStkPurchases in 'STLUStkPurchases.pas' {STLUStkPurchasesFrm},
  PBenquiry in 'PBenquiry.pas' {PBEnquiryFrm},
  STSOObjects in 'STSOObjects.pas',
  PBenqline in 'PBenqline.pas' {PBEnqLineTmp},
  PBEnqLineDtls in 'PBEnqLineDtls.pas' {PBEnqLineDtlsFrm},
  PBEnqAddDtls in 'PBEnqAddDtls.pas' {PBEnqAddDtlsFrm},
  PBEnqDataMod in 'PBEnqDataMod.pas' {PBEnqDataModFrm: TDataModule},
  PBPOToEnq in 'PBPOToEnq.pas' {PBPOToEnqFrm},
  PBEnqSelSup in 'PBEnqSelSup.pas' {PBEnqSelSupFrm},
  PBRSEnqN in 'PBRSEnqN.pas' {PBRSEnqNFrm},
  PBDBEnqLtr in 'PBDBEnqLtr.pas' {dbEnqLtr: TDataModule},
  PBEnqSuppDataMod in 'PBEnqSuppDataMod.pas' {PBEnqSuppDataModFrm: TDataModule},
  PBEnqSupTmp in 'PBEnqSupTmp.pas' {PBEnqSupTmpFrm},
  PBLUEnqAddChg in 'PBLUEnqAddChg.pas' {PBLUEnqAddChgFrm},
  PBEnqRespQty in 'PBEnqRespQty.pas' {PBEnqRespQtyFrm},
  PBEnqJobPrice in 'PBEnqJobPrice.pas' {PBEnqJobPriceFrm},
  PBEnqJobDtls in 'PBEnqJobDtls.pas' {PBEnqJobDtlsFrm},
  PBEnqAddChg in 'PBEnqAddChg.pas' {PBEnqAddChgFrm},
  PBDBQuoLtr in 'PBDBQuoLtr.pas' {dbQuoLtr: TDataModule},
  PBDBQuoSumLtr in 'PBDBQuoSumLtr.pas' {dbQuoSumLtr: TDataModule},
  PBRSQuoN in 'PBRSQuoN.pas' {PBRSQuoNFrm},
  STSODataMod in 'STSODataMod.pas' {STSalesOrdDM: TDataModule},
  STMaintSOrdLineServ in 'STMaintSOrdLineServ.pas' {STMaintSOrdLineServFrm},
  STPrtMnt in 'STPrtMnt.pas' {STPrtMntFrm},
  STPrtMntDetsMulti in 'STPrtMntDetsMulti.pas' {STPrtMntDetsMultiFrm},
  STPrtMntDets in 'STPrtMntDets.pas' {STPrtMntDetsFrm},
  StMntPrtSupp in 'StMntPrtSupp.pas' {STMntPrtSuppFrm},
  STLUPrtGrp in 'STLUPrtGrp.pas' {STLUPrtGrpFrm},
  STMntPrtGrp in 'STMntPrtGrp.pas' {STMntPrtGrpFrm},
  STProdImport in 'STProdImport.pas' {STProdImportFrm},
  STMaintPrtEComm in 'STMaintPrtEComm.pas' {STMaintPrtECommFrm},
  STMaintSOrdLine in 'STMaintSOrdLine.pas' {STMaintSOrdLineFrm},
  CSLUCustCstCntr in '..\CCSCommonD7\CSLUCustCstCntr.pas' {CSLUCustCstCntrFrm},
  CSMaintCustCstCntr in '..\CCSCommonD7\CSMaintCustCstCntr.pas' {CsMaintCustCstCntrFrm},
  STMaintSinvExtChg in 'STMaintSinvExtChg.pas' {STMaintSInvExtChgFrm},
  STMaintSOrdSerialNos in 'STMaintSOrdSerialNos.pas' {STMaintSOrdSerialNosFrm},
  PBNarrativeDM in 'PBNarrativeDM.pas' {dmNarrative: TDataModule},
  pbluCustDeliv in 'pbluCustDeliv.pas' {frmpbluOrderdeliv},
  STPrtAllocSales in 'STPrtAllocSales.pas' {STPrtAllocSalesFrm},
  STStockDM in 'STStockDM.pas' {STStockDataMod: TDataModule},
  STPrtAllocStStock in 'STPrtAllocStStock.pas' {STPrtAllocStStockFrm},
  STRSPickNote in 'STRSPickNote.pas' {STRSPickNotefrm},
  STPickObject in 'STPickObject.pas',
  stPickingDM in 'STPickingDM.pas' {STPickDM: TDataModule},
  STPickbyPart in 'STPickbyPart.pas' {STPickbyPartFrm},
  STPickItem in 'STPickItem.pas' {STPickItemFrm},
  STRSSalesOrd in 'STRSSalesOrd.pas' {STRSSalesOrdfrm},
  PBRSDelivNote in 'PBRSDelivNote.pas' {PBRSDelivNoteFrm},
  PBRSBoxLabels in 'PBRSBoxLabels.pas' {PBRSBoxLabelsfrm},
  PBMaintDeliv in 'PBMaintDeliv.pas' {PBMaintDelivFrm},
  pbStockMoveDm in 'pbStockMoveDm.pas' {dtmdlStockMove: TDataModule},
  PBMaintDelivBin in 'PBMaintDelivBin.pas' {PBMaintDelivBinfrm},
  PBMntPrtBinUpd in 'PBMntPrtBinUpd.pas' {PBMntPrtBinUpdFrm},
  PBMntPrtBin in 'PBMntPrtBin.pas' {PBMntPrtBinFrm},
  PBDelivStock in 'PBDelivStock.pas' {PBDelivStockFrm},
  STRSBoxLabels in 'STRSBoxLabels.pas' {STRSBoxLabelsfrm},
  pbluCustJobs in 'pbluCustJobs.pas' {frmpbluCustJobs},
  pbJobsDm in 'pbJobsDm.pas' {dtmdlJobs: TDataModule},
  pbluJobsSearch in 'pbluJobsSearch.pas' {frmpbluJobsSearch},
  PBMaintJobBagDets in 'PBMaintJobBagDets.pas' {PBMaintJobBagDetsFrm},
  PBMaintJobBagRC in 'PBMaintJobBagRC.pas' {PBMaintJobBagRCFrm},
  PBMaintQEnq in 'PBMaintQEnq.pas' {PBMaintQEnqFrm},
  PBEnquiryDataMod in 'PBEnquiryDataMod.pas' {PBEnqDM: TDataModule},
  PBRSProofN in 'PBRSProofN.pas' {PBRSProofNFrm},
  PBMaintProofHistN in 'PBMaintProofHistN.pas' {PBMaintProofHistNFrm},
  PBAutoPODets in 'PBAutoPODets.pas' {PBAutoPODetsFrm},
  PBAutoPO in 'PBAutoPO.pas' {PBAutoPOFrm},
  PBAutoPODataMod in 'PBAutoPODataMod.pas' {PBAutoPODM: TDataModule},
  STMaintProduct in 'STMaintProduct.pas' {frmSTMaintProduct},
  STMaintProductLvls in 'STMaintProductLvls.pas' {frmSTMaintProductLvls},
  STPrtTran in 'STPrtTran.pas' {STPrtTranFrm},
  STPrtTransQty in 'STPrtTransQty.pas' {STPrtTransQtyFrm},
  STLUBinPrt in 'STLUBinPrt.pas' {STLUBinPrtFrm},
  STPrtTransRecv in 'STPrtTransRecv.pas' {STPrtTransRecvFrm},
  STPrtTransSN in 'STPrtTransSN.pas' {STPrtTransSNFrm},
  STLUStStkNumbers in 'STLUStStkNumbers.pas' {STLUStStkNumbersFrm},
  STMaintStStkNumbers in 'STMaintStStkNumbers.pas' {STMaintStStkNumbersfrm},
  PBRPProof in 'Quick Reports\BesleyCopp\PBRPProof.pas' {PBRPProofFrm},
  PBRPDeliv in 'Quick Reports\BesleyCopp\PBRPDeliv.pas' {PBRPDelivFrm},
  STLUProductLvls in 'STLUProductLvls.pas' {frmSTLUProductLvls},
  PBLUDeliveriesDM in 'PBLUDeliveriesDM.pas' {dtmdlDeliveries: TDataModule},
  STRPSord in 'Quick Reports\BesleyCopp\STRPSord.pas' {STRPSordFrm},
  STRPDeliv in 'Quick Reports\BesleyCopp\STRPDeliv.pas' {STRPDelivfrm},
  STRPLabels in 'Quick Reports\BesleyCopp\STRPLabels.pas' {STRPLabelsFrm},
  STRPPick in 'Quick Reports\BesleyCopp\STRPPick.pas' {STRPPickfrm},
  STRSDelivNote in 'STRSDelivNote.pas' {STRSDelivNotefrm},
  pbluOrders in 'pbluOrders.pas' {frmpbLUOrders},
  PBLUVATCode in 'pbluVatCode.pas' {PBLUVATCodeFrm},
  STPrtMntLvls in 'STPrtMntLvls.pas' {STPrtMntLvlsFrm},
  STLUSuppPrt in 'STLUSuppPrt.pas' {STLUSuppPrtFrm},
  STRSLabels in 'STRSLabels.pas' {STRSLabelsfrm},
  CCSMaintPrtImages in '..\CCSCommonD7\CCSMaintPrtImages.pas' {CCSMaintPrtImagesFrm},
  GIFImage in '..\CCSCommonD7\gifimage.pas',
  CCSImageViewer in '..\CCSCommonD7\CCSImageViewer.pas' {CCSImageViewerFrm},
  STMntSOrd in 'STMntSOrd.pas' {STMntSOrdFrm},
  STMntSOrdSpecIn in 'STMntSOrdSpecIn.pas' {STMntSOrdSpecInFrm},
  pbLUEnquiries in 'pbLUEnquiries.pas' {frmPBLuEnquiries},
  pbLuStock in 'pbLuStock.pas' {frmPBLUStock},
  pbLuSalesOrders in 'pbLuSalesOrders.pas' {frmPBLUSalesOrders},
  pbLuJobs in 'pbLuJobs.pas' {frmPBLUJobs},
  pbLUSalesInvoices in 'pbLUSalesInvoices.pas' {frmPBLUSalesInvoices},
  pbLUPurchaseInvoices in 'pbLUPurchaseInvoices.pas' {frmPBLUPurchaseInvoices},
  PBSalesInvoiceDm in 'PBSalesInvoiceDm.pas' {dmSalesInvoice: TDataModule},
  PBLUSalesInvoiceSO in 'PBLUSalesInvoiceSO.pas' {PBLUSalesInvoiceSOfrm},
  PBLUSalesInvoiceCN in 'PBLUSalesInvoiceCN.pas' {PBLUSalesInvoiceCNfrm},
  PBLUSalesInvoiceJB in 'PBLUSalesInvoiceJB.pas' {PBLUSalesInvoiceJBfrm},
  PBLUSalesInvoiceJBL in 'PBLUSalesInvoiceJBL.pas' {PBLUSalesInvoiceJBLfrm},
  PBLUSalesInvoicePO in 'PBLUSalesInvoicePO.pas' {PBLUSalesInvoicePOfrm},
  PBMaintSalesInvoiceLine in 'PBMaintSalesInvoiceLine.pas' {PBMaintSalesInvoiceLinefrm},
  PBMaintSalesInvoice in 'PBMaintSalesInvoice.pas' {PBMaintSalesInvoicefrm},
  PBRPSalesInv in 'Quick Reports\BesleyCopp\PBRPSalesInv.pas' {PBRPSalesInvFrm},
  PBSalesInvRPrint in 'PBSalesInvRPrint.pas' {PBSalesInvRPrintFrm},
  PBSalesInvPrint in 'PBSalesInvPrint.pas' {PBSalesInvPrintFrm},
  PBMaintInvChgs in 'PBMaintInvChgs.pas' {PBMaintInvChgsfrm},
  STMntStorTyp in 'STMntStorTyp.pas' {STMntStorTypFrm},
  STLUStorTyp in 'STLUStorTyp.pas' {STLUStorTypFrm},
  STMntPrtStor in 'STMntPrtStor.pas' {STMntPrtStorFrm},
  STLUPrtStor in 'STLUPrtStor.pas' {STLUPrtStorFrm},
  STMntPrtBinUpd in 'STMntPrtBinUpd.pas' {STMntPrtBinUpdFrm},
  STMntPrtBin in 'STMntPrtBin.pas' {STMntPrtBinFrm},
  pbLUStockRpts in 'pbLUStockRpts.pas' {frmPBLUStockRpts},
  STRSStkBalRep in 'STRSStkBalRep.pas' {STRSStkBalRepfrm},
  STRPStkBalRep2 in 'STRPStkBalRep2.pas' {STRPStkBalRep2frm},
  STRPStkBalRep in 'STRPStkBalRep.pas' {STRPStkBalRepfrm},
  STFaxList in 'STFaxList.pas' {STFaxListFrm},
  STEmailList in 'STEmailList.pas' {STEmailListFrm},
  StMovSl in 'StMovSl.pas' {StMovSlfrm},
  StMovRep in 'StMovRep.pas' {StMovRepFrm},
  STRSSlwMvngStkRep in 'STRSSlwMvngStkRep.pas' {STRSSlwMvngStkRepfrm},
  STRPSlwMvngStkRep in 'STRPSlwMvngStkRep.pas' {STRPSlwMvngStkRepfrm},
  STNegStkRep in 'STNegStkRep.pas' {STNegStkRepFrm},
  STNegStksl in 'STNegStksl.pas' {STNegStkSlfrm},
  STRSStkVal in 'STRSStkVal.pas' {STRSStkValfrm},
  STStkValSl in 'STStkValSl.pas' {STStkValSlfrm},
  STStkValRep in 'STStkValRep.pas' {STStkValRepFrm},
  STStkVarRep in 'STStkVarRep.pas' {STStkVarRepFrm},
  STRSAgedStk in 'STRSAgedStk.pas' {STRSAgedStkFrm},
  STRPAgedStk in 'STRPAgedStk.pas' {STRPAgedStkFrm},
  STRPSalesByCust in 'STRPSalesByCust.pas' {STRPSalesByCustFrm},
  STRSSalesByCust in 'STRSSalesByCust.pas' {STRSSalesByCustFrm},
  STLUSordDM in 'STLUSordDM.pas' {DmLookupSOrd: TDataModule},
  STRPSOHistory in 'STRPSOHistory.pas' {STRPSOHistoryFrm},
  STRSSOHistory in 'STRSSOHistory.pas' {STRSSOHistoryFrm},
  STLUPrtByCustOrder in 'STLUPrtByCustOrder.pas' {STLUPrtByCustOrderFrm},
  STRPWorkIP in 'STRPWorkIP.pas' {STRPWorkIPfrm},
  STRSWorkIP in 'STRSWorkIP.pas' {STRSWorkIPfrm},
  STPartSuppSel in 'STPartSuppSel.pas' {STPartSuppSelFrm},
  STRPCustProdUsage in 'STRPCustProdUsage.pas' {STRPCustProdUsagefrm},
  STRPCustStkBal in 'STRPCustStkBal.pas' {STRPCustStkBalfrm},
  STRSCustProdUsage in 'STRSCustProdUsage.pas' {STRSCustProdUsageFrm},
  STRSCustStkBal in 'STRSCustStkBal.pas' {STRSCustStkBalfrm},
  STPartSuppRep in 'STPartSuppRep.pas' {STPartSuppRepFrm},
  STPartSuppDM in 'STPartSuppDM.pas' {STPartSDM: TDataModule},
  CCSemailHandler in '..\CCSCommonD7\CCSemailHandler.pas' {emailHandler: TDataModule},
  CCSEmailList in '..\CCSCommonD7\CCSEmailList.pas' {CCSEmailListFrm},
  STRSBoxLabelsDeliv in 'STRSBoxLabelsDeliv.pas' {STRSBoxLabelsDelivFrm},
  STRPLabelsDeliv in 'Quick Reports\BesleyCopp\STRPLabelsDeliv.pas' {STRPLabelsdelivFrm},
  pbLUOrderRpts in 'pbLUOrderRpts.pas' {frmPBLUOrderRpts},
  PBFaxToOne in 'PBFaxToOne.pas' {PBFaxToOneFrm},
  PBEmailToOne in 'PBEmailToOne.pas' {PBEmailToOneFrm},
  PBRSEnqSel in 'PBRSEnqSel.pas' {PBRSEnqSelFrm},
  PBRPEnqLst in 'PBRPEnqLst.pas' {PBRPEnqLstFrm},
  PBEnqNote in 'PBEnqNote.pas' {PBEnqNoteFrm},
  PBEnqQuantities in 'PBEnqQuantities.pas' {PBEnqQuantitiesFrm},
  PBEnqSuppRespns in 'PBEnqSuppRespns.pas' {PBEnqSuppRespnsFrm},
  PBEnqSupResp in 'PBEnqSupResp.pas' {PBEnqSupRespFrm},
  pbLUJobRpts in 'pbLUJobRpts.pas' {frmPBLUJobRpts},
  PBRDPORep in 'PBRDPORep.pas' {PBRDPORepDataMod: TDataModule},
  PBRSWorkIP in 'PBRSWorkIP.pas' {PBRSWorkIPfrm},
  PBRP4CastSumm in 'PBRP4CastSumm.pas' {PBRP4CastSummFrm},
  PBRS4CastInvs in 'PBRS4CastInvs.pas' {PBRS4CastInvsFrm},
  PBRS4CastSumm in 'PBRS4CastSumm.pas' {PBRS4CastSummfrm},
  PBRP4CastInvs in 'PBRP4CastInvs.pas' {PBRP4CastInvsFrm},
  PBRSRptOrds in 'PBRSRptOrds.pas' {PBRSRptOrdsFrm},
  PBRPRptOrds in 'PBRPRptOrds.pas' {PBRPRptOrdsFrm},
  PBRPWorkIP in 'PBRPWorkIP.pas' {PBRPWorkIPfrm},
  PBRSJBMargin in 'PBRSJBMargin.pas' {PBRSJBMarginfrm},
  PBRSODueEnq in 'PBRSODueEnq.pas' {PBRSODueEnqFrm},
  PBRSODueQte in 'PBRSODueQte.pas' {PBRSODueQteFrm},
  PBRSPODue in 'PBRSPODue.pas' {PBRSPODueFrm},
  PBRSPORepM in 'PBRSPORepM.pas' {PBRSPORepMFrm},
  PBRSPORep in 'PBRSPOREP.pas' {PBRSPORepFrm},
  PBRPPOnotonJB in 'PBRPPOnotonJB.pas' {PBRPPOnotonJBfrm},
  PBRSPOnotonJB in 'PBRSPOnotonJB.pas' {PBRSPOnotonJBfrm},
  pbLUSalesInvRpts in 'pbLUSalesInvRpts.pas' {frmPBLUSalesInvRpts},
  PBRPJBMargin in 'PBRPJBMargin.pas' {PBRPJBMarginFrm},
  PBRPODueEnq in 'PBRPODueEnq.pas' {PBRPODueEnqFrm},
  PBRPODueQte in 'PBRPODueQte.pas' {PBRPODueQteFrm},
  PBRPPODue in 'PBRPPODue.pas' {PBRPPODueFrm},
  PBRPPORep in 'PBRPPORep.pas' {PBRPPORepFrm},
  PBRPPORepM in 'PBRPPORepM.pas' {PBRPPORepMFrm},
  PBRPRepProfitSumm in 'PBRPRepProfitSumm.pas' {PBRPRepProfitSummFrm},
  PBRPSalesByInv in 'PBRPSalesByInv.pas' {PBRPSalesByInvFrm},
  PBRPSalesByInvDet in 'PBRPSalesByInvDet.pas' {PBRPSalesByInvDetFrm},
  PBRPSalesbyProd in 'PBRPSalesbyProd.pas' {PBRPSalesbyProdFrm},
  PBRPSalesComm in 'PBRPSalesComm.pas' {PBRPSalesCommFrm},
  PBRPSalesCommbyCat in 'PBRPSalesCommbyCat.pas' {PBRPSalesCommbyCatFrm},
  PBRPSalesProfit in 'PBRPSalesProfit.pas' {PBRPSalesProfitFrm},
  PBRPSalesProfitSumm in 'PBRPSalesProfitSumm.pas' {PBRPSalesProfitSummFrm},
  PBRSCustState in 'PBRSCustState.pas' {PBRSCustStateFrm},
  PBRSCustTurn in 'PBRSCustTurn.pas' {PBRSCustTurnFrm},
  PBRSSalesByInv in 'PBRSSalesByInv.pas' {PBRSSalesByInvFrm},
  PBRSSalesByProd in 'PBRSSalesByProd.pas' {PBRSSalesByProdFrm},
  PBRSSalesComm in 'PBRSSalesComm.pas' {PBRSSalesCommFrm},
  PBRSSalesProfit in 'PBRSSalesProfit.pas' {PBRSSalesProfitfrm},
  PBRPCustState in 'Quick Reports\BesleyCopp\PBRPCustState.pas' {PBRPCustStateFrm},
  PBLUSInvDM in 'PBLUSInvDM.pas' {dmLookUpSInv: TDataModule},
  PBRPProofStatus in 'PBRPProofStatus.pas' {PBRPProofStatusfrm},
  PBRSProofStatus in 'PBRSProofStatus.pas' {PBRSProofStatusFrm},
  PBSupplierInvoiceDM in 'PBSupplierInvoiceDm.pas' {dmSupplierInvoice: TDataModule},
  PBMaintSuppInvoice in 'PBMaintSuppInvoice.pas' {PBMaintSuppInvoicefrm},
  PBMaintSuppInvoicePass in 'PBMaintSuppInvoicePass.pas' {PBMaintSuppInvoicePassFrm},
  PBMaintSuppInvoiceChgs in 'PBMaintSuppInvoiceChgs.pas' {PBMaintSuppInvoiceChgsfrm},
  PBMaintSuppInvoiceLine in 'PBMaintSuppInvoiceLine.pas' {PBMaintSuppInvoiceLinefrm},
  PBLUSupplierInvoicePurch in 'PBLUSupplierInvoicePurch.pas' {PBLUSupplierInvoicePurchFrm},
  PBLUSupplierInvoiceCN in 'PBLUSupplierInvoiceCN.pas' {PBLUSupplierInvoiceCNFrm},
  PBLUSupplierInvoiceJB in 'PBLUSupplierInvoiceJB.pas' {PBLUSupplierInvoiceJBFrm},
  PBLUSupplierInvoicePO in 'PBLUSupplierInvoicePO.pas' {PBLUSupplierInvoicePOFrm},
  pbLUPurchaseOrders in 'pbLUPurchaseOrders.pas' {frmPBLUPurchaseOrders},
  pbPOrdersDM in 'pbPOrdersDM.pas' {dtmdlPOrders: TDataModule},
  STMntPOrd in 'STMntPOrd.pas' {STMntPOrdFrm},
  STPOObjects in 'STPOObjects.pas',
  STPODataMod in 'STPODataMod.pas' {STPODM: TDataModule},
  STMntPOrdAdd in 'STMntPOrdAdd.pas' {STMntPOrdAddFrm},
  STMntPOrdQty in 'STMntPOrdQty.pas' {STMntPOrdQtyFrm},
  STMaintPOExtChg in 'STMaintPOExtChg.pas' {STMaintPOExtChgFrm},
  STPordRSl in 'STPordRSl.pas' {STPordRSlFrm},
  STPOrdRep in 'Quick Reports\BesleyCopp\STPOrdRep.pas' {STPOrdRepFrm},
  STPODirectConf in 'STPODirectConf.pas' {STPODirectConfFrm},
  STMaintParam in 'STMaintParam.pas' {STMaintParamFrm},
  STLUFormRef in 'STLUFormRef.pas' {frmSTLUFormRef},
  STMaintFormRef in 'STMaintFormRef.pas' {frmSTMaintFormRef},
  pbLUCustOrdersJB in 'pbLUCustOrdersJB.pas' {frmpbluCustOrdersJB},
  pbluCustEvents in 'pbluCustEvents.pas' {frmPBLUCustEvents},
  pbEventsDM in 'pbEventsDM.pas' {dtmdlEvents: TDataModule},
  PBMaintCContaEvents in 'PBMaintCContaEvents.pas' {PBMaintCContaEventsFrm},
  PBMaintContactEvents in 'PBMaintContactEvents.pas' {frmPBMaintContactEvents},
  PBLUReps in 'PBLUReps.pas' {frmPBLUReps},
  pbLUCustomerRpts in 'pbLUCustomerRpts.pas' {frmPBLUCustomerRpts},
  PBRSCustContDet in 'PBRSCustContDet.pas' {PBRSCustContDetFrm},
  PBRSCustDet in 'PBRSCustDet.pas' {PBRSCustDetFrm},
  PBRPCustContDet in 'PBRPCustContDet.pas' {PBRPCustContDetFrm},
  PBRPCustDet in 'PBRPCustDet.pas' {PBRPCustDetFrm},
  pbLUSalesCredits in 'pbLUSalesCredits.pas' {frmPBLUSalesCredits},
  pbLUPurchaseCredits in 'pbLUPurchaseCredits.pas' {frmPBLUPurchaseCredits},
  pbluCustSalesInvoices in 'pbluCustSalesInvoices.pas' {frmpbLUCustSalesInvoices},
  PBAccImportDM in 'PBAccImportDM.pas' {dmAccImport: TDataModule},
  PBAccExport1 in 'PBAccExport1.pas' {PBAccExport1Frm},
  PBAccExport2 in 'PBAccExport2.pas' {PBAccExport2Frm},
  PBAccExport3 in 'PBAccExport3.pas' {PBAccExport3Frm},
  PBAccExport4 in 'PBAccExport4.pas' {PBAccExport4Frm},
  PBAccExportDM in 'PBAccExportDM.pas' {dmAccExport: TDataModule},
  PBAccExportDirectDebit in 'PBAccExportDirectDebit.pas' {PBAccExportDirectDebitFrm},
  PBAbout in 'PBAbout.pas' {PBAboutFrm},
  PBDocObjectsDM in 'PBDocObjectsDM.pas' {dmPBDocObjects: TDataModule},
  PBDocObjects in 'PBDocObjects.pas',
  PBMaintPOEmail in 'PBMaintPOEmail.pas' {PBMaintPOEmailFrm},
  PBMaintCompanyFY in 'PBMaintCompanyFY.pas' {PBMaintCompanyFYfrm},
  PBMaintFinanceYear in 'PBMaintFinanceYear.pas' {PBMaintFinanceYearFrm},
  PBLUFinanceYear in 'PBLUFinanceYear.pas' {PBLUFinanceYearFrm},
  PBMaintRepCatBudgets in 'PBMaintRepCatBudgets.pas' {PBMaintRepCatBudgetsFrm},
  PBMaintRepBudgets in 'PBMaintRepBudgets.pas' {PBMaintRepBudgetsFrm},
  PBMaintJobType in 'PBMaintJobType.pas' {PBMaintJobTypeFrm},
  PBLUJobType in 'PBLUJobType.pas' {PBLUJobTypeFrm},
  PBRSPurchByInv in 'PBRSPurchByInv.pas' {PBRSPurchByInvFrm},
  PBRPPurchByInv in 'PBRPPurchByInv.pas' {PBRPPurchByInvFrm},
  pbLUPurchaseInvoiceRpts in 'pbLUPurchaseInvoiceRpts.pas' {frmPBLUPurchaseInvoiceRpts},
  PBRSSalesByPrdCat in 'PBRSSalesByPrdCat.pas' {PBRSSalesByPrdCatFrm},
  PBRPSalesByPrdCatDet in 'PBRPSalesByPrdCatDet.pas' {PBRPSalesByPrdCatDetFrm},
  PBRPSalesByPrdCat in 'PBRPSalesByPrdCat.pas' {PBRPSalesByPrdCatFrm},
  PBRPStkMove in 'PBRPStkMove.pas' {PBRPStkMovefrm},
  PBRSOSSInvPayments in 'PBRSOSSInvPayments.pas' {PBRSOSSInvPaymentsFrm},
  PBRPOSSInvPayments in 'PBRPOSSInvPayments.pas' {PBRPOSSInvPaymentsFrm},
  pbMaintSalesInvPay in 'pbMaintSalesInvPay.pas' {PBMaintSalesInvPayFrm},
  PBLUProductionLoc in 'PBLUProductionLoc.pas' {PBLUProductionLocfrm},
  PBMaintProductionLoc in 'PBMaintProductionLoc.pas' {PBMaintProductionLocFrm},
  pbLUPurchaseOrderRpts in 'pbLUPurchaseOrderRpts.pas' {frmPBLUPurchaseOrderRpts},
  STRSPord in 'STRSPord.pas' {STRSPordFrm},
  STRPPord in 'STRPPord.pas' {STRPPordfrm},
  CCSMaintProdImages in '..\CCSCOMMOND7\CCSMaintProdImages.pas' {CCSMaintProdImagesFrm},
  pbluFormReferences in 'pbluFormReferences.pas' {frmPBLUFormReferences},
  PBLUProd in 'PBLUProd.pas' {PBLUProdFrm},
  pbFormReferenceDM in 'pbFormReferenceDM.pas' {dtmdlForms: TDataModule},
  PBWOrdersDm in 'PBWOrdersDm.pas' {dtmdlWOrders: TDataModule},
  pbLuWorksOrders in 'pbLuWorksOrders.pas' {frmPBLUWorksOrders},
  pbluWorksOrdersSearch in 'pbluWorksOrdersSearch.pas' {frmpbluWorksOrdersSearch},
  PBMaintWorksOrders in 'PBMaintWorksOrders.pas' {frmPBMaintWorksOrders},
  PBMaintProductionType in 'PBMaintProductionType.pas' {PBMaintProductionTypeFrm},
  PBLUProductionType in 'PBLUProductionType.pas' {PBLUProductionTypeFrm},
  PBLUPreProduction in 'PBLUPreProduction.pas' {PBLUPreProductionFrm},
  PBMaintPreProduction in 'PBMaintPreProduction.pas' {PBMaintPreProductionFrm},
  PBRPWorksOrder in 'Quick Reports\BesleyCopp\PBRPWorksOrder.pas' {frmPBRPWorksOrder},
  PBMaintProcess in 'PBMaintProcess.pas' {PBMaintProcessFrm},
  PBLUProcess in 'PBLUProcess.pas' {PBLUProcessFrm},
  PBMaintProcessQstn in 'PBMaintProcessQstn.pas' {PBMaintProcessQstnFrm},
  PBLUProcessQstn in 'PBLUProcessQstn.pas' {PBLUProcessQstnFrm},
  PBLUProcessQstnList in 'PBLUProcessQstnList.pas' {PBLUProcessQstnListFrm},
  PBMaintProductionProcess in 'PBMaintProductionProcess.pas' {frmPBMaintProductionProcess},
  PBRSWorksOrder in 'PBRSWorksOrder.pas' {frmPBRSWorksOrder},
  PBMaintWOrderConfDelivs in 'PBMaintWOrderConfDelivs.pas' {frmPBMaintWOrderConfDelivs},
  PBMaintWOrderEvents in 'PBMaintWOrderEvents.pas' {frmPBMaintWOrderEvents},
  STMaintSOrdDel in 'STMaintSOrdDel.pas' {STMaintSOrdDelfrm},
  PBMaintAccountTeam in 'PBMaintAccountTeam.pas' {PBMaintAccountTeamFrm},
  PBLUAccountTeam in 'PBLUAccountTeam.pas' {PBLUAccountTeamfrm},
  PBLURepTeam in 'PBLURepTeam.pas' {PBLURepTeamfrm},
  PBMaintRepTeam in 'PBMaintRepTeam.pas' {PBMaintRepTeamFrm},
  PBMaintAccTeamMembers in 'PBMaintAccTeamMembers.pas' {frmPBMaintAccTeamMembers},
  PBLUAccountManager in 'PBLUAccountManager.pas' {PBLUAccountManagerFrm},
  PBMaintAccountManager in 'PBMaintAccountManager.pas' {PBMaintAccountManagerFrm},
  PBMaintJobBagExtras in 'PBMaintJobBagExtras.pas' {PBMaintJobBagExtrasFrm},
  PBPOrdHist in 'PBPOrdHist.pas' {PBPOrdHistFrm},
  PBRSJBDraft in 'PBRSJBDraft.pas' {PBRSJBDraftFrm},
  PBLUCustCstCntr in 'PBLUCustCstCntr.pas' {PBLUCustCstCntrFrm},
  PBLUCustDisc in 'PBLUCustDisc.pas' {PBLUCustDiscFrm},
  PBRSPurchInv in 'PBRSPurchInv.pas' {PBRSPurchInvFrm},
  PBRSPOStockDue in 'PBRSPOStockDue.pas' {PBRSPOStockDueFrm: Unit1},
  PBPeriodEnd in 'PBPeriodEnd.pas' {PBPeriodEndfrm},
  PBPeriodEndDM in 'PBPeriodEndDM.pas' {dmPeriodEnd: TDataModule},
  PBRSRepsPerform in 'PBRSRepsPerform.pas' {PBRSRepsPerformfrm},
  PBRPRepsPerform in 'PBRPRepsPerform.pas' {PBRPRepsPerformFrm},
  PBMaintRepFinancials in 'PBMaintRepFinancials.pas' {PBMaintRepFinancialsFrm},
  PBLUPOLAddChgs in 'PBLUPOLAddChgs.pas' {PBLUPOLAddChgsfrm},
  PBMaintPOLAddChgs in 'PBMaintPOLAddChgs.pas' {PBMaintPOLAddChgsfrm},
  pbLUManagementRpts in 'pbLUManagementRpts.pas' {frmPBLUManagementRpts},
  PBRSPEndRepsPerform in 'PBRSPEndRepsPerform.pas' {PBRSPEndRepsPerformfrm},
  PBRPPEndRepsPerform in 'PBRPPEndRepsPerform.pas' {PBRPPEndRepsPerformfrm},
  PBRSPEndRepsProfit in 'PBRSPEndRepsProfit.pas' {PBRSPEndRepsProfitFrm},
  PBRSPEndCustPerform in 'PBRSPEndCustPerform.pas' {PBRSPEndCustPerformFrm},
  PBRSPEndRepsCommission in 'PBRSPEndRepsCommission.pas' {PBRSPEndRepsCommissionFrm},
  PBRPPEndRepsCatComm in 'PBRPPEndRepsCatComm.pas' {PBRPPEndRepsCatCommFrm},
  PBMaintJobBag in 'PBMaintJobBag.pas' {PBMaintJobBagFrm},
  PBMaintJobBagLines in 'PBMaintJobBagLines.pas' {PBMaintJobBagLinesFrm},
  PBMaintJobBagSundries in 'PBMaintJobBagSundries.pas' {PBMaintJobBagSundriesfrm},
  PBRPJobBagWIP in 'PBRPJobBagWIP.pas' {PBRPJobBagWIPfrm},
  PBRSJobBagWIP in 'PBRSJobBagWIP.pas' {PBRSJobBagWIPfrm},
  PBRPJobBagExtrasWIP in 'PBRPJobBagExtrasWIP.pas' {PBRPJobBagExtrasWIPfrm},
  PBRSJobBagExtrasWIP in 'PBRSJobBagExtrasWIP.pas' {PBRSJobBagExtrasWIPfrm},
  PBRS4CastMonthInvs in 'PBRS4CastMonthInvs.pas' {PBRS4CastMonthInvsFrm},
  PBRP4CastMonthInvs in 'PBRP4CastMonthInvs.pas' {PBRP4CastMonthInvsFrm},
  STProdImportCust in 'STProdImportCust.pas' {STProdImportCustFrm},
  STProdImportAllCust in 'STProdImportAllCust.pas' {STProdImportAllCustFrm},
  STRPBxLabels in 'Quick Reports\BesleyCopp\STRPBxLabels.pas' {STRPBxLabelsFrm},
  STRPCustStkBalDet in 'STRPCustStkBalDet.pas' {STRPCustStkBalDetfrm},
  STRSStockLabels in 'STRSStockLabels.pas' {STRSStockLabelsfrm},
  STRPStockLabels in 'Quick Reports\BesleyCopp\STRPStockLabels.pas' {STRPStockLabelsFrm},
  PBPartTransfer in 'PBPartTransfer.pas' {PBPartTransferFrm},
  pbluCustomerSearch in 'pbluCustomerSearch.pas' {frmpbluCustomerSearch},
  PBLUProductRef in 'PBLUProductRef.pas' {PBLUProductRefFrm},
  PBMaintProductRef in 'PBMaintProductRef.pas' {PBMaintProductRefFrm},
  PBMaintJobBagLineDetails in 'PBMaintJobBagLineDetails.pas' {PBMaintJobBagLineDetailsFrm},
  STMaintSalesOrder in 'STMaintSalesOrder.pas' {frmSTMaintSalesOrder},
  STMaintSalesOrderLine in 'STMaintSalesOrderLine.pas' {frmSTMaintSalesOrderLine},
  pbLUCustWorksJB in 'pbLUCustWorksJB.pas' {frmpbluCustWorksJB},
  PBRSJobBag in 'PBRSJobBag.pas' {frmPBRSJobBag},
  pbLUCustEnqsJB in 'pbLUCustEnqsJB.pas' {frmpbluCustEnqsJB},
  STLUStockLocations in 'STLUStockLocations.pas' {frmSTLUStockLocations},
  STRSSOReturns in 'STRSSOReturns.pas' {STRSSOReturnsFrm},
  STRPSOReturns in 'STRPSOReturns.pas' {STRPSOReturnsFrm},
  pbLUSalesOrdersRpts in 'pbLUSalesOrdersRpts.pas' {frmPBLUSalesOrdersRpts},
  PBLUPackageSize in 'PBLUPackageSize.pas' {PBLUPackageSizeFrm},
  PBMaintPackageSize in 'PBMaintPackageSize.pas' {PBMaintPackageSizeFrm},
  STLUCourier in 'STLUCourier.pas' {STLUCourierFrm},
  STLUCourierServ in 'STLUCourierServ.pas' {STLUCourierServFrm},
  STMaintCourierServ in 'STMaintCourierServ.pas' {STMaintCourierServFrm},
  STMaintCourier in 'STMaintCourier.pas' {STMaintCourierFrm},
  PBRPOSSInv in 'PBRPOSSInv.pas' {PBRPOSSInvFrm},
  PBRSOSSInv in 'PBRSOSSInv.pas' {PBRSOSSInvFrm},
  PBRSOSSInvPInvRecd in 'PBRSOSSInvPInvRecd.pas' {PBRSOSSInvPInvRecdFrm},
  PBRPOSSInvPInvRecd in 'PBRPOSSInvPInvRecd.pas' {PBRPOSSInvPInvRecdFrm},
  PBRSOSSInvJobBags in 'PBRSOSSInvJobBags.pas' {PBRSOSSInvJobBagsFrm},
  PBRPOSSInvJobBags in 'PBRPOSSInvJobBags.pas' {PBRPOSSInvJobBagsFrm},
  STRSPickingNote in 'STRSPickingNote.pas' {STRSPickingNoteFrm},
  PBLUPartBOM in 'PBLUPartBOM.pas' {PBLUPartBOMFrm},
  PBMaintPartBOM in 'PBMaintPartBOM.pas' {PBMaintPartBOMfrm},
  STRPStockUsage in 'STRPStockUsage.pas' {STRPStockUsagefrm},
  STRSStockUsage in 'STRSStockUsage.pas' {STRSStockUsageFrm},
  CCSProgressBar in '..\CCSCOMMOND7\CCSProgressBar.pas' {frmCCSProgressBar},
  PBRPPurchByInvDets in 'PBRPPurchByInvDets.pas' {PBRPPurchByInvDetsFrm},
  STMaintStock in 'STMaintStock.pas' {STMaintStockFrm},
  STMaintPick in 'STMaintPick.pas' {STMaintPickFrm},
  PBFileImport in 'PBFileImport.pas' {PBFileImportFrm},
  STRPPickingNote in 'STRPPickingNote.pas' {STRPPickingNoteFrm},
  pbLUAccMgrRpts in 'pbLUAccMgrRpts.pas' {frmPBLUAccMgrRpts},
  pbLUStockTake in 'pbLUStockTake.pas' {frmPBLUStocktake},
  STStkTkSl in 'STStkTkSl.pas' {STStkTkslfrm},
  STStkTakeDM in 'STStkTakeDM.pas' {STStkTkDM: TDataModule},
  STLUPartBinLot in 'STLUPartBinLot.pas' {STLUPartBinLotFrm},
  pbLUWorksOrdersRpts in 'pbLUWorksOrdersRpts.pas' {frmPBLUWorksOrdersRpts},
  PBRSWIDespatch in 'PBRSWIDespatch.pas' {PBRSWIDespatchFrm},
  PBRPWIDespatch in 'PBRPWIDespatch.pas' {PBRPWIDespatchFrm},
  STMaintSalesOrderLineValues in 'STMaintSalesOrderLineValues.pas' {frmSTMaintSalesOrderLineValues},
  STRSSOProdReturns in 'STRSSOProdReturns.pas' {STRSSOProdReturnsFrm},
  PBMaintCustStockPrefix in 'PBMaintCustStockPrefix.pas' {PBMaintCustStockPrefixFrm},
  STRPStockLocations in 'STRPStockLocations.pas' {frmSTRPStockLocations},
  PBMaintRevenueLoc in 'PBMaintRevenueLoc.pas' {PBMaintRevenueLocFrm},
  PBLURevenueLoc in 'PBLURevenueLoc.pas' {PBLURevenueLocFrm},
  PBMaintProofStatus in 'PBMaintProofStatus.pas' {PBMaintProofStatusFrm},
  PBLUProofStatus in 'PBLUProofStatus.pas' {PBLUProofStatusFrm},
  PBLUJobReturns in 'PBLUJobReturns.pas' {frmPBLUJobReturns},
  PBMaintJobReturns in 'PBMaintJobReturns.pas' {frmPBMaintJobReturns},
  PBMaintJobBagRecStock in 'PBMaintJobBagRecStock.pas' {frmPBMaintJobBagRecStock},
  StStkTkSel in 'STStkTkSel.pas' {STStkTkSelFrm},
  STStkTkbyPart in 'STStkTkbyPart.pas' {STStkTkbyPartFrm},
  PBRPPurchInv in 'PBRPPurchInv.pas' {PBRPPurchInvFrm},
  PBLUSalesInvoiceCustJB in 'PBLUSalesInvoiceCustJB.pas' {PBLUSalesInvoiceCustJBfrm},
  PBLUCategory in 'PBLUCategory.pas' {PBLUCategoryFrm},
  PBMaintCategory in 'PBMaintCategory.pas' {PBMaintCategoryFrm},
  STLUPartStock in 'STLUPartStock.pas' {STLUPartStockFrm},
  PBMaintJobBagDoc in 'PBMaintJobBagDoc.pas' {PBMaintJobBagDocFrm},
  PBWordOLE in 'PBWordOLE.pas' {PBWordOLEFrm},
  PBExcelOLE in 'PBExcelOLE.pas' {PBExcelOLEFrm},
  PBSendtoExcel in 'PBSendtoExcel.pas' {frmPBSendtoExcel},
  PBRSSalesInvStats in 'PBRSSalesInvStats.pas' {PBRSSalesInvStatsFrm},
  PBRPSalesInvStats in 'PBRPSalesInvStats.pas' {PBRPSalesInvStatsFrm},
  taoMAPI in '..\CCSCOMMOND7\taoMAPI.pas',
  PBRPPEndSalesComm in 'PBRPPEndSalesComm.pas' {PBRPPEndSalesCommFrm},
  PBRPPEndRepsCatPerform in 'PBRPPEndRepsCatPerform.pas' {PBRPPEndRepsCatPerformfrm},
  PBMaintWorkCentreGroup in 'PBMaintWorkCentreGroup.pas' {PBMaintWorkCentreGroupFrm},
  PBLUWorkCentreGroup in 'PBLUWorkCentreGroup.pas' {PBLUWorkCentreGroupfrm},
  PBMaintProcessWCGroup in 'PBMaintProcessWCGroup.pas' {PBMaintProcessWCGroupFrm},
  PBLUProcessWCGroup in 'PBLUProcessWCGroup.pas' {PBLUProcessWCGroupfrm},
  PBMaintWorkCentre in 'PBMaintWorkCentre.pas' {PBMaintWorkCentreFrm},
  PBLUWorkCentre in 'PBLUWorkCentre.pas' {PBLUWorkCentrefrm},
  PBMaintWorkCentreSize in 'PBMaintWorkCentreSize.pas' {PBMaintWorkCentreSizeFrm},
  PBMaintWorkCentreWCGroup in 'PBMaintWorkCentreWCGroup.pas' {PBMaintWorkCentreWCGroupFrm},
  PBMaintWorkCentreGroupWC in 'PBMaintWorkCentreGroupWC.pas' {PBMaintWorkCentreGroupWCFrm},
  PBMaintJobBagProcess in 'PBMaintJobBagProcess.pas' {PBMaintJobBagProcessFrm},
  PBRSSupplierTurn in 'PBRSSupplierTurn.pas' {PBRSSupplierTurnFrm},
  PBRPSupplierTurn in 'PBRPSupplierTurn.pas' {PBRPSupplierTurnFrm},
  PBRPCustTurn in 'PBRPCustTurn.pas' {PBRPCustTurnFrm},
  PBMaintJobBagSched in 'PBMaintJobBagSched.pas' {PBMaintJobBagSchedFrm},
  PBRPJobBagSched in 'Quick Reports\BesleyCopp\PBRPJobBagSched.pas' {frmPBRPJobBagSched},
  PBRSDataServsWIP in 'PBRSDataServsWIP.pas' {PBRSDataServsWIPFrm},
  PBRPDataServsWIP in 'PBRPDataServsWIP.pas' {PBRPDataServsWIPFrm},
  PBRPJobBagApprovalDue in 'PBRPJobBagApprovalDue.pas' {PBRPJobBagApprovalDueFrm},
  PBRPClientServsWIP in 'PBRPClientServsWIP.pas' {PBRPClientServsWIPFrm},
  pbLUQuoteRpts in 'pbLUQuoteRpts.pas' {frmPBLUQuoteRpts},
  PBMaintCreditReason in 'PBMaintCreditReason.pas' {PBMaintCreditReasonFrm},
  PBLUCreditReason in 'PBLUCreditReason.pas' {PBLUCreditReasonFrm},
  PBMaintPOrdHistory in 'PBMaintPOrdHistory.pas' {PBMaintPOrdHistoryFrm},
  PBMaintEnquiryDoc in 'PBMaintEnquiryDoc.pas' {PBMaintEnquiryDocFrm},
  PBRPCustProfitSumm in 'PBRPCustProfitSumm.pas' {PBRPCustProfitSummFrm},
  STRPAgedStkNote in 'STRPAgedStkNote.pas' {STRPAgedStkNoteFrm},
  PBMaintCompBranch in 'PBMaintCompBranch.pas' {PBMaintCompBranchFrm},
  pbLUCompBranch in 'pbLUCompBranch.pas' {pbLUCompBranchFrm},
  PBMaintFormReference in 'PBMaintFormReference.pas' {PBMaintFormReferencefrm},
  PBRSJobBagWIPStkReq in 'PBRSJobBagWIPStkReq.pas' {PBRSJobBagWIPStkReqFrm},
  PBRPJobBagWIPStkReq in 'PBRPJobBagWIPStkReq.pas' {PBRPJobBagWIPStkReqfrm},
  PBAboutOps in 'PBAboutOps.pas' {PBAboutOpsFrm},
  PBLUCustProductTemp in 'PBLUCustProductTemp.pas' {PBLUCustProductTempFrm},
  PBMaintCustProductTemp in 'PBMaintCustProductTemp.pas' {PBMaintCustProductTempFrm},
  PBMaintCustCstCntr in 'PBMaintCustCstCntr.pas' {PBMaintCustCstCntrFrm},
  PBMaintCustDisc in 'PBMaintCustDisc.pas' {PBMaintCustDiscFrm},
  PBMaintProduct1 in 'PBMaintProduct1.pas' {PBMaintProduct1Frm},
  pbQuotesDm in 'pbQuotesDm.pas' {dtmdlQuotes: TDataModule},
  pbLUQuotes in 'pbLUQuotes.pas' {frmPBLUQuotes},
  PBMaintQuote in 'PBMaintQuote.pas' {PBMaintQuoteFrm},
  pbluQuotesSearch in 'pbluQuotesSearch.pas' {frmpbluQuotesSearch},
  PBMaintQuoteLines in 'PBMaintQuoteLines.pas' {PBMaintQuoteLinesFrm},
  PBRSQuote in 'PBRSQuote.pas' {frmPBRSQuote},
  PBRPJobBag in 'PBRPJobBag.pas' {frmPBRPJobBag},
  PBMaintQuoteDoc in 'PBMaintQuoteDoc.pas' {PBMaintQuoteDocFrm},
  PBLUQuoteEnqsQty in 'PBLUQuoteEnqsQty.pas' {PBLUQuoteEnqsQtyFrm},
  PBRSCustCatKPI in 'PBRSCustCatKPI.pas' {PBRSCustCatKPIfrm},
  PBRSPEndLocPerform in 'PBRSPEndLocPerform.pas' {PBRSPEndLocPerformfrm},
  PBRPPEndLocPerform in 'PBRPPEndLocPerform.pas' {PBRPPEndLocPerformfrm},
  PBLUQuoteReason in 'PBLUQuoteReason.pas' {PBLUQuoteReasonFrm},
  PBMaintQuoteReason in 'PBMaintQuoteReason.pas' {PBMaintQuoteReasonFrm: Unit1},
  PBRPCustCatKPI in 'PBRPCustCatKPI.pas' {PBRPCustCatKPIFrm},
  PBRSCreditNoteReason in 'PBRSCreditNoteReason.pas' {PBRSCreditNoteReasonFrm},
  PBRPCreditNoteReason in 'PBRPCreditNoteReason.pas' {PBRPCreditNoteReasonFrm},
  PBMaintCustAccMgr in 'PBMaintCustAccMgr.pas' {PBMaintCustAccMgrFrm},
  PBMaintAccMgrsCust in 'PBMaintAccMgrsCust.pas' {PBMaintAccMgrsCustFrm},
  PBMaintContactOnline in 'PBMaintContactOnline.pas' {PBMaintContactOnlineFrm},
  PBRSQuoteCust in 'PBRSQuoteCust.pas' {PBRSQuoteCustFrm},
  PBRPQuoteCust in 'PBRPQuoteCust.pas' {PBRPQuoteCustFrm},
  PBRSQuoteReason in 'PBRSQuoteReason.pas' {PBRSQuoteReasonFrm},
  PBRPQuoteReason in 'PBRPQuoteReason.pas' {PBRPQuoteReasonFrm},
  PBRPQuoteProduction in 'PBRPQuoteProduction.pas' {PBRPQuoteProductionFrm},
  PBRSPOAuth in 'PBRSPOAuth.pas' {PBRSPOAuthFrm},
  PBRPPOAuth in 'PBRPPOAuth.pas' {PBRPPOAuthFrm},
  pbLURepRpts in 'pbLURepRpts.pas' {frmPBLURepRpts: Unit1},
  STImpDirectOrders in 'STImpDirectOrders.pas' {STImpDirectOrdersFrm},
  STImpSalesOrders in 'STImpSalesOrders.pas' {STImpSalesOrdersFrm},
  PBMaintJobBagInactive in 'PBMaintJobBagInactive.pas' {PBMaintJobBagInactiveFrm},
  PBSendEInvoiceViaFTP in 'PBSendEInvoiceViaFTP.pas' {PBSendEInvoiceViaFTPFrm},
  PBMaintWOrderDelivs in 'PBMaintWOrderDelivs.pas' {frmPBMaintWOrderDelivs},
  PBLUWorksOrderDelivs in 'PBLUWorksOrderDelivs.pas' {frmPBLUWorksOrderDelivs},
  PBMaintSuppCharges in 'PBMaintSuppCharges.pas',
  PBLUProcessGroup in 'PBLUProcessGroup.pas' {PBLUProcessGroupFrm},
  PBMaintProcessGroup in 'PBMaintProcessGroup.pas' {PBMaintProcessGroupFrm},
  PBRPPEndCatPerform in 'PBRPPEndCatPerform.pas' {PBRPPEndCatPerformfrm},
  PBRSPEndCatPerform in 'PBRSPEndCatPerform.pas' {PBRSPEndCatPerformfrm},
  STMaintStockUsage in 'STMaintStockUsage.pas' {STMaintStockUsageFrm},
  STRPBarCode in 'STRPBarCode.pas' {STRPBarCodeFrm},
  STRSBarCode in 'STRSBarCode.pas' {STRSBarCodeFrm},
  STMaintStockReturns in 'STMaintStockReturns.pas' {STMaintStockReturnsFrm},
  PBRSJobBagOvers in 'PBRSJobBagOvers.pas' {PBRSJobBagOversFrm},
  PBRPJobBagOvers in 'PBRPJobBagOvers.pas' {PBRPJobBagOversFrm},
  STRSStockReturns in 'STRSStockReturns.pas' {STRSStockReturnsFrm},
  STRPStockReturns in 'STRPStockReturns.pas' {STRPStockReturnsFrm},
  STRPStockUsageDet in 'STRPStockUsageDet.pas' {STRPStockUsageDetfrm},
  PBExportEInvoice in 'PBExportEInvoice.pas' {PBExportEInvoiceFrm},
  STRSSOrderDeliv in 'STRSSOrderDeliv.pas' {STRSSOrderDelivFrm},
  STMaintCustStock in 'STMaintCustStock.pas' {STMaintCustStockFrm},
  PBSendPOViaFTP in 'PBSendPOViaFTP.pas' {PBSendPOViaFTPFrm},
  PBLUDBAlias in 'PBLUDBAlias.pas' {PBLUDBAliasFrm},
  PBMaintDBAlias in 'PBMaintDBAlias.pas' {PBMaintDBAliasFrm},
  PBRSEInvoice in 'PBRSEInvoice.pas' {PBRSEInvoiceFrm},
  pbluCustQuotes in 'pbluCustQuotes.pas' {frmpbluCustQuotes},
  PBMaintBranchCstCntr in 'PBMaintBranchCstCntr.pas' {PBMaintBranchCstCntrFrm},
  PBMaintFSCClaim in 'PBMaintFSCClaim.pas' {PBMaintFSCClaimFrm},
  PBLUFSCClaim in 'PBLUFSCClaim.pas' {PBLUFSCClaimFrm},
  PBLUBranchCstCntr in 'PBLUBranchCstCntr.pas' {PBLUBranchCstCntrFrm},
  PBLUWCOperator in 'PBLUWCOperator.pas' {PBLUWCOperatorFrm},
  PBMaintWCOperator in 'PBMaintWCOperator.pas' {PBMaintWCOperatorFrm},
  PBMaintProcessOps in 'PBMaintProcessOps.pas' {PBMaintProcessOpsFrm},
  PBLUProcessOps in 'PBLUProcessOps.pas' {PBLUProcessOpsFrm},
  PBRSProdAmends in 'PBRSProdAmends.pas' {PBRSProdAmendsFrm},
  pbLUProductionRpts in 'pbLUProductionRpts.pas' {frmPBLUProductionRpts},
  PBRPProdAmends in 'PBRPProdAmends.pas' {PBRPProdAmendsFrm},
  pbLUEnquiryRpts in 'pbLUEnquiryRpts.pas' {frmPBLUEnquiryRpts},
  PBRSProdWeekly in 'PBRSProdWeekly.pas' {PBRSProdWeeklyFrm},
  PBRPProdWeekly in 'PBRPProdWeekly.pas' {PBRPProdWeeklyFrm},
  PBLUJobLog in 'PBLUJobLog.pas' {PBLUJobLogFrm},
  SFJobBagLogDM in '..\SFDC\SFJobBagLogDM.pas' {dtmdlJobBagLog: TDataModule},
  PBLUJobLogSearch in 'PBLUJobLogSearch.pas' {frmPBLUJobLogSearch},
  PBEnqInActLine in 'PBEnqInActLine.pas' {PBEnqInActLineFrm},
  PBLUProcessCost in 'PBLUProcessCost.pas' {PBLUProcessCostFrm},
  PBMaintProcessCost in 'PBMaintProcessCost.pas' {PBMaintProcessCostFrm},
  PBMaintProcessCostCat in 'PBMaintProcessCostCat.pas' {PBMaintProcessCostCatFrm},
  PBMaintProcessCostSub in 'PBMaintProcessCostSub.pas' {PBMaintProcessCostSubFrm},
  PBRPQuote in 'Quick Reports\BesleyCopp\PBRPQuote.pas' {frmPBRPQuote},
  PBMaintDocument in 'PBMaintDocument.pas' {PBMaintDocumentFrm},
  PBMaintPaymentTerms in 'PBMaintPaymentTerms.pas' {PBMaintPaymentTermsFrm},
  PBLUPaymentTerms in 'PBLUPaymentTerms.pas' {PBLUPaymentTermsFrm},
  PBMaintJobBagProcessCosts in 'PBMaintJobBagProcessCosts.pas' {PBMaintJobBagProcessCostsFrm},
  Office12_TLB in '..\CCSCommonD7\Office12_TLB.pas',
  Outlook12_TLB in '..\CCSCommonD7\Outlook12_TLB.pas',
  PBRPJBDraft in 'Quick Reports\BesleyCopp\PBRPJBDraft.pas' {PBRPJBDraftFrm},
  STRPSalesHistory in 'STRPSalesHistory.pas' {STRPSalesHistoryFrm},
  STRPSalesHistoryLoc in 'STRPSalesHistoryLoc.pas' {STRPSalesHistoryLocFrm},
  pbluSupplierSearch in 'pbluSupplierSearch.pas' {frmpbluSupplierSearch},
  PBMaintCustMulti in 'PBMaintCustMulti.pas' {PBMaintCustMultiFrm},
  PBMaintSICCode in 'PBMaintSICCode.pas' {PBMaintSICCodeFrm},
  pbluSICCode in 'pbluSICCode.pas' {PBLUSICCodeFrm},
  pbluProspects in 'pbluProspects.pas' {frmPBLUProspects},
  PBRSWorksOrderISO in 'PBRSWorksOrderISO.pas' {PBRSWorksOrderISOfrm},
  PBLUActivitiesSearch in 'PBLUActivitiesSearch.pas' {frmPBLUActivitiesSearch},
  PBExpiryDate in 'PBExpiryDate.pas' {frmPBExpiryDate},
  PBMaintEmailSupplier in 'PBMaintEmailSupplier.pas' {PBMaintEmailSupplierFrm},
  PBMaintEmail in 'PBMaintEmail.pas' {PBMaintEmailFrm},
  PBMaintActivity in 'PBMaintActivity.pas' {PBMaintActivityFrm},
  PBMaintCompanyDocStructure in 'PBMaintCompanyDocStructure.pas' {PBMaintCompanyDocStructureFrm},
  PBMaintCompanyDocName in 'PBMaintCompanyDocName.pas' {PBMaintCompanyDocNameFrm},
  PBLUWorksOrderStatus in 'PBLUWorksOrderStatus.pas' {PBLUWorksOrderStatusfrm},
  PBMaintWorksOrderStatus in 'PBMaintWorksOrderStatus.pas' {PBMaintWorksOrderStatusFrm},
  PBMaintWOrderStatus in 'PBMaintWOrderStatus.pas' {PBMaintWOrderStatusFrm},
  PBLUSalesInvoiceDD in 'PBLUSalesInvoiceDD.pas' {PBLUSalesInvoiceDDFrm},
  PBMaintRepTeamMembers in 'PBMaintRepTeamMembers.pas' {frmPBMaintRepTeamMembers},
  PBMaintRepTeamBudgets in 'PBMaintRepTeamBudgets.pas' {PBMaintRepTeamBudgetsFrm},
  PBRPPEndRepTeamPerform in 'PBRPPEndRepTeamPerform.pas' {PBRPPEndRepTeamPerformFrm},
  PBRSPEndRepTeamPerform in 'PBRSPEndRepTeamPerform.pas' {PBRSPEndRepTeamPerformFrm},
  PBContractDM in 'PBContractDM.pas' {dtmdlContract: TDataModule},
  PBActivityDM in 'PBActivityDM.pas' {dtmdlActivity: TDataModule},
  PBLUContracts in 'PBLUContracts.pas' {frmPBLUContracts},
  PBLUActivities in 'PBLUActivities.pas' {frmPBLUActivities},
  PBMaintContract in 'PBMaintContract.pas' {PBMaintContractFrm},
  pbLUContractCustomerJobs in 'PBLUContractCustomerJobs.pas' {PBLUContractCustomerJobsFrm},
  PBLUContractSearch in 'PBLUContractSearch.pas' {frmPBLUContractSearch},
  pbLuNCA in 'pbLuNCA.pas' {frmPBluNCA},
  PBRSJobBagComplete in 'PBRSJobBagComplete.pas' {PBRSJobBagCompleteFrm},
  PBRPCustCreditTerms in 'Quick Reports\BesleyCopp\PBRPCustCreditTerms.pas' {PBRPCustCreditTermsFrm},
  PBRPCusSupLabs in 'PBRPCusSupLabs.pas' {PBRPCusSupLabsFrm},
  PBRPLabels in 'Quick Reports\BesleyCopp\PBRPLabels.pas' {PBRPLabelsFrm},
  PBRPLabelsReels in 'Quick Reports\BesleyCopp\PBRPLabelsReels.pas' {PBRPLabelsReelsFrm};

{$R *.RES}

begin
  Application.Initialize;
  Application.Title := 'Quaystone Redeye Management Information';
  Application.CreateForm(TdmBroker, dmBroker);
  Application.CreateForm(TfrmpbMainMenu, frmpbMainMenu);
  Application.CreateForm(TPBImagesFrm, PBImagesFrm);
  Application.CreateForm(TdmLetter, dmLetter);
  Application.CreateForm(TPBAuditDataMod, PBAuditDataMod);
  Application.Run;
end.
