program Firebelly_Elite;

uses
  Forms,
  wtWin7 in 'wtWin7.pas',
  wtSplash in 'wtSplash.pas' {frmWTSplash},
  wtDatabase in 'wtDatabase.pas' {frmWTDatabase},
  wtCustomerDM in 'wtCustomerDM.pas' {dtmdlCustomers: TDataModule},
  wtDataModule in 'wtDataModule.pas' {dtmdlWorktops: TDataModule},
  wtLUThickness in 'wtLUThickness.pas' {frmWtLUThickness},
  wtLUworktops in 'wtLUworktops.pas' {frmWtLUWorktops},
  WTMaintParams in 'WTMaintParams.pas' {frmWTMaintParams},
  wtLUMatType in 'wtLUMatType.pas' {frmWTLUMatType},
  wtMaintProductGroup in 'wtMaintProductGroup.pas' {frmWtMaintProductGroup},
  wtMaintThickness in 'wtMaintThickness.pas' {frmWtMaintThickness},
  wtLUWTThickness in 'wtLUWTThickness.pas' {frmWTLUWTThickness},
  WTMaintWTThickness in 'WTMaintWTThickness.pas' {frmWTMaintWTThickness},
  wtLUCustomer in 'wtLUCustomer.pas' {frmWTLUCustomer},
  WTAutoPriceChange in 'WTAutoPriceChange.pas' {frmWTAutoPriceChange},
  wtMaintQuote in 'wtMaintQuote.pas' {frmWTMaintQuote},
  WTMaintCustomer in 'WTMaintCustomer.pas' {frmWtMaintCustomer},
  wtLUAddChgs in 'wtLUAddChgs.pas' {frmWTLUAddChgs},
  wtLUCustQuotes in 'wtLUCustQuotes.pas' {frmwtLUCustQuotes},
  wtLUCustJobs in 'wtLUCustJobs.pas' {frmwtLUCustJobs},
  wtLUCustInvoices in 'wtLUCustInvoices.pas' {frmwtLUCustInvoices},
  WTCustJobsDM in 'WTCustJobsDM.pas' {dtmdlCustJobs: TDataModule},
  WTCustInvoicesDM in 'WTCustInvoicesDM.pas' {dtmdlCustInvoices: TDataModule},
  wtAboutBox in 'wtAboutBox.pas' {frmwtAboutBox},
  wtMain in 'wtMain.pas' {frmWTMain},
  WTQuotesDM in 'WTQuotesDM.pas' {dtmdlQuote: TDataModule},
  wtCommon in 'wtCommon.pas',
  wtLUQuotes in 'wtLUQuotes.pas' {frmwtLUQuotes},
  wtNotesDM in 'wtNotesDM.pas' {dtmdlNotes: TDataModule},
  wtLUEdges in 'wtLUEdges.pas' {frmwtLUEdges},
  WTMaintEdges in 'WTMaintEdges.pas' {frmWTMaintEdges},
  wtLUCutOuts in 'wtLUCutOuts.pas' {frmWTLUCutOuts},
  wtMaintCutOuts in 'wtMaintCutOuts.pas' {frmWTMaintCutOuts},
  wtMaintEdgeDetails in 'wtMaintEdgeDetails.pas' {frmWTMaintEdgeDetails},
  wtLUCustType in 'wtLUCustType.pas' {frmWTLUCustType},
  wtMaintCustTypes in 'wtMaintCustTypes.pas' {frmWTMaintCustTypes},
  wtLUVat in 'wtLUVat.pas' {frmwtLUVat},
  wtMaintVat in 'wtMaintVat.pas' {frmwtMaintVat},
  AllCommon in 'AllCommon.pas',
  WTSrchCustomer in 'WTSrchCustomer.pas' {frmWTSrchCustomer},
  wtMaintQUpstand in 'wtMaintQUpstand.pas' {frmWTMaintQUpstand},
  wtMaintQCutOut in 'wtMaintQCutOut.pas' {frmWtMaintQCutOut},
  wtMaintQEdge in 'wtMaintQEdge.pas' {frmWTMaintQEdge},
  wtMaintQExtra in 'wtMaintQExtra.pas' {frmWTMaintQExtra},
  wtMaintCustomerConts in 'wtMaintCustomerConts.pas' {frmwtMaintCustomerConts},
  WTSrchCustContacts in 'WTSrchCustContacts.pas' {frmWTSrchCustContacts},
  wtMaintQElement in 'wtMaintQElement.pas' {frmWTMaintQElement},
  wtLUPurchases in 'wtLUPurchases.pas' {frmwtLUPurchases},
  wtLUSales in 'wtLUSales.pas' {frmwtLUSales},
  WTJobsDM in 'WTJobsDM.pas' {dtmdlJob: TDataModule},
  wtLUJobs in 'wtLUJobs.pas' {frmwtLUJobs},
  WTSalesOrderDM in 'WTSalesOrderDM.pas' {dtmdlSalesOrder: TDataModule},
  wtMaintSalesOrder in 'wtMaintSalesOrder.pas' {frmWTMaintSalesOrder},
  wtPurchasesDM in 'wtPurchasesDM.pas' {dtmdlPurchase: TDataModule},
  wtMaintPurchOrders in 'wtMaintPurchOrders.pas' {frmWTMaintPurchOrders},
  wtSalesInvoiceDM in 'wtSalesInvoiceDM.pas' {dtmdlSalesInvoice: TDataModule},
  wtMaintSalesInvoice in 'wtMaintSalesInvoice.pas' {frmWTMaintSalesInvoice},
  wtRSQuote in 'wtRSQuote.pas' {frmWTRSQuote},
  wtLUWTGroup in 'wtLUWTGroup.pas' {frmWTLUWTGroup},
  WTMaintWTGroup in 'WTMaintWTGroup.pas' {frmWTMaintWTGroup},
  wtMaintAddChgs in 'wtMaintAddChgs.pas' {frmwtMaintAddChgs},
  wtMaintJob in 'wtMaintJob.pas' {frmWTMaintJob},
  wtMaintJUpstand in 'wtMaintJUpstand.pas' {frmWTMaintJUpstand},
  wtMaintJEdge in 'wtMaintJEdge.pas' {frmWTMaintJEdge},
  wtMaintJElement in 'wtMaintJElement.pas' {frmWTMaintJElement},
  wtMaintJExtra in 'wtMaintJExtra.pas' {frmWTMaintJExtra},
  wtMaintJCutOut in 'wtMaintJCutOut.pas' {frmWtMaintJCutOut},
  WTRSJobCutSched in 'WTRSJobCutSched.pas' {frmWTRSJobCutSched},
  WTRSJobMasonRpt in 'WTRSJobMasonRpt.pas' {frmWTRSJobMasonRpt},
  WTRPJobMasonRpt in 'WTRPJobMasonRpt.pas' {frmWTRPJobMasonRpt},
  WTQuoteSearch in 'WTQuoteSearch.pas' {frmWTQuoteSearch},
  WTJobSearch in 'WTJobSearch.pas' {frmWTJobSearch},
  wtMaintQEvents in 'wtMaintQEvents.pas' {frmWTMaintQEvents},
  wtMaintJEvents in 'wtMaintJEvents.pas' {frmWTMaintJEvents},
  wtUtilities in 'wtUtilities.pas' {frmWTUtilities},
  wtLUOperators in 'wtLUOperators.pas' {frmWTLUOperators},
  WTMaintOperators in 'WTMaintOperators.pas' {frmWTMaintOperators},
  WTUpdateDB in 'WTUpdateDB.pas' {dtmdlUpdateDB: TDataModule},
  WTLogin in 'WTLogin.pas' {frmWTLogin},
  WtLUWTGroupPrices in 'WtLUWTGroupPrices.pas' {frmWtLUWTGroupPrices},
  WTMaintWTGPrices in 'WTMaintWTGPrices.pas' {frmWTMaintWTGPrices},
  wtRSJobSheet in 'wtRSJobSheet.pas' {frmWTRSJobSheet},
  wtRPJobAccSheet in 'wtRPJobAccSheet.pas' {frmwtRPJobAccSheet},
  wtLUEdgeTypes in 'wtLUEdgeTypes.pas' {frmWTLUEdgeTypes},
  wtMaintEdgeType in 'wtMaintEdgeType.pas' {frmWTMaintEdgeType},
  wtMaintQElementM in 'wtMaintQElementM.pas' {frmWTMaintQElementM},
  wtMaintJElementM in 'wtMaintJElementM.pas' {frmWTMaintJElementM},
  wtRSQuotePerf in 'wtRSQuotePerf.pas' {frmWTRSQuotePerf},
  wtFaxList in 'wtFaxList.pas' {frmWTFaxList},
  wtEmailList in 'wtEmailList.pas' {frmWTEmailList},
  wtMaintClient in 'wtMaintClient.pas' {frmWTMaintClient},
  WTLUQuoteRpts in 'WTLUQuoteRpts.pas' {frmWTLUQuoteRpts},
  WTRPQuotePerf in 'WTRPQuotePerf.pas' {frmwtRPQuotePerf},
  DateSelV5 in 'DateSelV5.pas' {DateSelV5Form},
  wtRSOutQuote in 'wtRSOutQuote.pas' {frmWTRSOutQuote},
  WTRPOutQuote in 'WTRPOutQuote.pas' {frmwtRPOutQuote},
  AllImages in 'AllImages.pas' {frmAllImages},
  WTMaintSalesOrderJobLine in 'WTMaintSalesOrderJobLine.pas' {frmWTMaintSalesOrderJobLine},
  wtLUStock in 'wtLUStock.pas' {frmWTLUStock},
  wtStockDM in 'wtStockDM.pas' {dtmdlStock: TDataModule},
  wtLUReps in 'wtLUReps.pas' {frmWTLUReps},
  wtMaintReps in 'wtMaintReps.pas' {frmWTMaintReps},
  wtLUProductGroups in 'wtLUProductGroups.pas' {frmWTLUProductGroups},
  wtMaintMatType in 'wtMaintMatType.pas' {frmWtMaintMatType},
  wtMaintProduct in 'wtMaintProduct.pas' {frmWtMaintProduct},
  wtLUProducts in 'wtLUProducts.pas' {frmWTLUProducts},
  wtMaintSalesInvoiceLine in 'wtMaintSalesInvoiceLine.pas' {frmWTMaintSalesInvoiceLine},
  wtRSSalesInvoice in 'wtRSSalesInvoice.pas' {frmwtRSSalesInvoice},
  wtLUSalesInvoices in 'wtLUSalesInvoices.pas' {frmWTLUSalesInvoices},
  WTLUSalesInvoiceSO in 'WTLUSalesInvoiceSO.pas' {frmWTLUSalesInvoiceSO},
  WTMaintSalesOrderLine in 'WTMaintSalesOrderLine.pas' {frmWTMaintSalesOrderLine},
  wtRSSOrder in 'wtRSSOrder.pas' {frmWTRSSOrder},
  wtLUSOLines in 'wtLUSOLines.pas' {frmWTLUSOLines},
  WTLUSOrderRpts in 'WTLUSOrderRpts.pas' {frmWTLUSOrderRpts},
  WTRPSOrderTemplate in 'WTRPSOrderTemplate.pas' {frmwtRPSOrderTemplate},
  wtRSSOrderTemplate in 'WTRSSOrderTemplate.pas' {frmWTRSSOrderTemplate},
  WTSOrderSearch in 'WTSOrderSearch.pas' {frmWTSOrderSearch},
  wtMaintJobComplete in 'wtMaintJobComplete.pas' {frmWTMaintJobComplete},
  wtLUSalesOrderQuotes in 'wtLUSalesOrderQuotes.pas' {frmWTLUSalesOrderQuotes},
  wtLUSalesCredits in 'wtLUSalesCredits.pas' {frmWTLUSalesCredits},
  WTLUSalesInvoiceCN in 'WTLUSalesInvoiceCN.pas' {frmWTLUSalesInvoiceCN},
  wtRSSalesInvoiceReprint in 'wtRSSalesInvoiceReprint.pas' {frmWTRSSalesInvoiceReprint},
  wtAccExport1 in 'wtAccExport1.pas' {frmWTAccExport1},
  WTAccExport2 in 'WTAccExport2.pas' {frmWTAccExport2},
  WTAccExport3 in 'WTAccExport3.pas' {frmWTAccExport3},
  WTAccExportDM in 'WTAccExportDM.pas' {dmAccExport: TDataModule},
  WTAccExport4 in 'WTAccExport4.pas' {frmWTAccExport4},
  WTAccExportFactInvs in 'WTAccExportFactInvs.pas' {frmWTAccExportFactInvs},
  wtLoginError in 'wtLoginError.pas' {frmWTLoginError},
  wtLicence in 'wtLicence.pas' {frmWTLicence},
  WTLUJobRpts in 'WTLUJobRpts.pas' {frmWTLUJobRpts},
  wtRSOutJobs in 'wtRSOutJobs.pas' {frmWTRSOutJobs},
  WTRPOutJobs in 'WTRPOutJobs.pas' {frmwtRPOutJobs},
  WTRPSOAntInvoice in 'WTRPSOAntInvoice.pas' {frmwtRPSOAntInvoice},
  wtRSSOAntInvoice in 'wtRSSOAntInvoice.pas' {frmWTRSSOAntInvoice},
  WTDeleteHistory in 'WTDeleteHistory.pas' {frmWTDeleteHistory},
  WTUtilitiesDM in 'WTUtilitiesDM.pas' {dtmdlUtilities: TDataModule},
  wtLUSalesLead in 'wtLUSalesLead.pas' {frmWTLUSalesLead},
  wtLUFitters in 'wtLUFitters.pas' {frmWTLUFitters},
  wtMaintFitters in 'wtMaintFitters.pas' {frmWTMaintFitters},
  WTSendtoExcel in 'WTSendtoExcel.pas' {frmWTSendtoExcel},
  WTLUEdgeDetails in 'WTLUEdgeDetails.pas' {frmWTLUEdgeDetails},
  wtLUCutOutDetails in 'wtLUCutOutDetails.pas' {frmWTLUCutOutDetails},
  wtMaintCutOutDetails in 'wtMaintCutOutDetails.pas' {frmWTMaintCutOutDetails},
  wtRPContract in 'Elite\Reports\wtRPContract.pas' {frmWTRPContract},
  WTRPJobCutSched in 'Elite\Reports\WTRPJobCutSched.pas' {frmWTRPJobCutSched},
  WtRPJobRemedialSheet in 'Elite\Reports\WtRPJobRemedialSheet.pas' {frmwtRPJobRemedialSheet},
  WtRPJobSheetClient in 'Elite\Reports\WtRPJobSheetClient.pas' {frmWTRPJobSheetClient},
  WTRPSOrderAllocation in 'Elite\Reports\WTRPSOrderAllocation.pas' {frmWTRPSOrderAllocation},
  WtRPJobFitting in 'Elite\Reports\WtRPJobFitting.pas' {frmwtRPJobFitting},
  WtRPJobSheet in 'Elite\Reports\WtRPJobSheet.pas' {frmwtRPJobSheet},
  wtRPSalesInvoice in 'Elite\Reports\wtRPSalesInvoice.pas' {frmWTRPSalesInvoice},
  wtRPSOrder in 'Elite\Reports\wtRPSOrder.pas' {frmwtRPSOrder},
  wtRPTemplate in 'Elite\Reports\wtRPTemplate.pas' {frmwtRPTemplate},
  WTMaintContract in 'WTMaintContract.pas' {frmWTMaintContract},
  wtMaintQSlab in 'WTMaintQSlab.pas' {frmWTMaintQSlab},
  WTLUCustWTGroups in 'WTLUCustWTGroups.pas' {frmWTLUCustWTGroups},
  WTMaintCustWTGroup in 'WTMaintCustWTGroup.pas' {frmWTMaintCustWTGroup},
  WTLUCustEdgeCutOutGroup in 'WTLUCustEdgeCutOutGroup.pas' {frmWTLUCustEdgeCutOutGroup},
  WTMaintCustEdgeCutOutGroup in 'WTMaintCustEdgeCutOutGroup.pas' {frmWTMaintCustEdgeCutOutGroup},
  wtLUCustCutOutDetails in 'wtLUCustCutOutDetails.pas' {frmWTLUCustCutOutDetails},
  wtMaintCustEdge in 'wtMaintCustEdge.pas' {frmWTMaintCustEdge},
  wtLUCustEdgeDetails in 'wtLUCustEdgeDetails.pas' {frmWTLUCustEdgeDetails},
  wtMaintCustCustOut in 'wtMaintCustCustOut.pas' {frmWTMaintCustCutOut},
  WTMaintPurchaseOrderLine in 'WTMaintPurchaseOrderLine.pas' {frmWTMaintPurchaseOrderLine},
  WTMaintPurchaseOrder in 'WTMaintPurchaseOrder.pas' {frmWTMaintPurchaseOrder},
  wtRPQuote in 'Elite\Reports\wtRPQuote.pas' {frmwtRPQuote},
  wtRPQuoteSummary in 'Elite\Reports\wtRPQuoteSummary.pas' {frmwtRPQuoteSummary},
  WTContractsDM in 'WTContractsDM.pas' {dtmdlContract: TDataModule};

{$R *.RES}

begin
  Application.Initialize;
//  frmWTSplash := TfrmWTSplash.Create( Application );
//  frmWTSplash.Show;
//  frmWTSplash.Refresh;
  Application.Title := 'Worktop Manufacturing';
  Application.CreateForm(TdtmdlWorktops, dtmdlWorktops);
  Application.CreateForm(TfrmWTMain, frmWTMain);
  Application.CreateForm(TfrmAllImages, frmAllImages);
  Application.Run;
end.
