program Firebelly_aktiv;

uses
  Forms,
  wtWin7 in '..\wtWin7.pas',
  wtSplash in '..\wtSplash.pas' {frmWTSplash},
  wtDatabase in '..\wtDatabase.pas' {frmWTDatabase},
  wtCustomerDM in '..\wtCustomerDM.pas' {dtmdlCustomers: TDataModule},
  wtDataModule in '..\wtDataModule.pas' {dtmdlWorktops: TDataModule},
  wtLUThickness in '..\wtLUThickness.pas' {frmWtLUThickness},
  wtLUworktops in '..\wtLUworktops.pas' {frmWtLUWorktops},
  WTMaintParams in '..\WTMaintParams.pas' {frmWTMaintParams},
  wtLUMatType in '..\wtLUMatType.pas' {frmWTLUMatType},
  wtMaintProductGroup in '..\wtMaintProductGroup.pas' {frmWtMaintProductGroup},
  wtMaintThickness in '..\wtMaintThickness.pas' {frmWtMaintThickness},
  wtLUWTThickness in '..\wtLUWTThickness.pas' {frmWTLUWTThickness},
  WTMaintWTThickness in '..\WTMaintWTThickness.pas' {frmWTMaintWTThickness},
  wtLUCustomer in '..\wtLUCustomer.pas' {frmWTLUCustomer},
  WTAutoPriceChange in '..\WTAutoPriceChange.pas' {frmWTAutoPriceChange},
  wtMaintQuote in '..\wtMaintQuote.pas' {frmWTMaintQuote},
  WTMaintCustomer in '..\WTMaintCustomer.pas' {frmWtMaintCustomer},
  wtLUAddChgs in '..\wtLUAddChgs.pas' {frmWTLUAddChgs},
  wtLUCustQuotes in '..\wtLUCustQuotes.pas' {frmwtLUCustQuotes},
  wtLUCustInvoices in '..\wtLUCustInvoices.pas' {frmwtLUCustInvoices},
  WTCustInvoicesDM in '..\WTCustInvoicesDM.pas' {dtmdlCustInvoices: TDataModule},
  wtAboutBox in '..\wtAboutBox.pas' {frmwtAboutBox},
  wtMain in '..\wtMain.pas' {frmWTMain},
  WTQuotesDM in '..\WTQuotesDM.pas' {dtmdlQuote: TDataModule},
  wtCommon in '..\wtCommon.pas',
  wtLUQuotes in '..\wtLUQuotes.pas' {frmwtLUQuotes},
  wtNotesDM in '..\wtNotesDM.pas' {dtmdlNotes: TDataModule},
  wtLUEdges in '..\wtLUEdges.pas' {frmwtLUEdges},
  WTMaintEdges in '..\WTMaintEdges.pas' {frmWTMaintEdges},
  wtLUCutOuts in '..\wtLUCutOuts.pas' {frmWTLUCutOuts},
  wtMaintCutOuts in '..\wtMaintCutOuts.pas' {frmWTMaintCutOuts},
  wtMaintEdgeDetails in '..\wtMaintEdgeDetails.pas' {frmWTMaintEdgeDetails},
  wtLUCustType in '..\wtLUCustType.pas' {frmWTLUCustType},
  wtMaintCustTypes in '..\wtMaintCustTypes.pas' {frmWTMaintCustTypes},
  wtLUVat in '..\wtLUVat.pas' {frmwtLUVat},
  wtMaintVat in '..\wtMaintVat.pas' {frmwtMaintVat},
  AllCommon in '..\AllCommon.pas',
  WTSrchCustomer in '..\WTSrchCustomer.pas' {frmWTSrchCustomer},
  wtMaintQUpstand in '..\wtMaintQUpstand.pas' {frmWTMaintQUpstand},
  wtMaintQCutOut in '..\wtMaintQCutOut.pas' {frmWtMaintQCutOut},
  wtMaintQEdge in '..\wtMaintQEdge.pas' {frmWTMaintQEdge},
  wtMaintQExtra in '..\wtMaintQExtra.pas' {frmWTMaintQExtra},
  wtMaintCustomerConts in '..\wtMaintCustomerConts.pas' {frmwtMaintCustomerConts},
  WTSrchCustContacts in '..\WTSrchCustContacts.pas' {frmWTSrchCustContacts},
  wtMaintQElement in '..\wtMaintQElement.pas' {frmWTMaintQElement},
  wtLUSales in '..\wtLUSales.pas' {frmwtLUSales},
  WTJobsDM in '..\WTJobsDM.pas' {dtmdlJob: TDataModule},
  wtLUJobs in '..\wtLUJobs.pas' {frmwtLUJobs},
  WTSalesOrderDM in '..\WTSalesOrderDM.pas' {dtmdlSalesOrder: TDataModule},
  wtMaintSalesOrder in '..\wtMaintSalesOrder.pas' {frmWTMaintSalesOrder},
  wtMaintPurchOrders in '..\wtMaintPurchOrders.pas' {frmWTMaintPurchOrders},
  wtSalesInvoiceDM in '..\wtSalesInvoiceDM.pas' {dtmdlSalesInvoice: TDataModule},
  wtMaintSalesInvoice in '..\wtMaintSalesInvoice.pas' {frmWTMaintSalesInvoice},
  wtRSQuote in '..\wtRSQuote.pas' {frmWTRSQuote},
  wtRPQuoteTrade in '..\wtRPQuoteTrade.pas' {frmwtRPQuoteTrade},
  wtLUWTGroup in '..\wtLUWTGroup.pas' {frmWTLUWTGroup},
  WTMaintWTGroup in '..\WTMaintWTGroup.pas' {frmWTMaintWTGroup},
  wtMaintAddChgs in '..\wtMaintAddChgs.pas' {frmwtMaintAddChgs},
  wtMaintJob in '..\wtMaintJob.pas' {frmWTMaintJob},
  wtMaintJUpstand in '..\wtMaintJUpstand.pas' {frmWTMaintJUpstand},
  wtMaintJEdge in '..\wtMaintJEdge.pas' {frmWTMaintJEdge},
  wtMaintJElement in '..\wtMaintJElement.pas' {frmWTMaintJElement},
  wtMaintJExtra in '..\wtMaintJExtra.pas' {frmWTMaintJExtra},
  wtMaintJCutOut in '..\wtMaintJCutOut.pas' {frmWtMaintJCutOut},
  WTRSJobCutSched in '..\WTRSJobCutSched.pas' {frmWTRSJobCutSched},
  WTRSJobMasonRpt in '..\WTRSJobMasonRpt.pas' {frmWTRSJobMasonRpt},
  WTRPJobMasonRpt in '..\WTRPJobMasonRpt.pas' {frmWTRPJobMasonRpt},
  WTCustomerSearch in '..\WTCustomerSearch.pas' {frmWTCustomerSearch},
  WTJobSearch in '..\WTJobSearch.pas' {frmWTJobSearch},
  wtMaintQEvents in '..\wtMaintQEvents.pas' {frmWTMaintQEvents},
  wtMaintJEvents in '..\wtMaintJEvents.pas' {frmWTMaintJEvents},
  wtUtilities in '..\wtUtilities.pas' {frmWTUtilities},
  wtLUOperators in '..\wtLUOperators.pas' {frmWTLUOperators},
  WTMaintOperators in '..\WTMaintOperators.pas' {frmWTMaintOperators},
  WTUpdateDB in '..\WTUpdateDB.pas' {dtmdlUpdateDB: TDataModule},
  WTLogin in '..\WTLogin.pas' {frmWTLogin},
  WtLUWTGroupPrices in '..\WtLUWTGroupPrices.pas' {frmWtLUWTGroupPrices},
  WTMaintWTGPrices in '..\WTMaintWTGPrices.pas' {frmWTMaintWTGPrices},
  wtRSJobSheet in '..\wtRSJobSheet.pas' {frmWTRSJobSheet},
  WtRPJobSheet in '..\WtRPJobSheet.pas' {frmWtRPJobSheet},
  wtRPJobAccSheet in '..\wtRPJobAccSheet.pas' {frmwtRPJobAccSheet},
  wtLUEdgeTypes in '..\wtLUEdgeTypes.pas' {frmWTLUEdgeTypes},
  wtMaintEdgeType in '..\wtMaintEdgeType.pas' {frmWTMaintEdgeType},
  wtMaintQElementM in '..\wtMaintQElementM.pas' {frmWTMaintQElementM},
  wtMaintJElementM in '..\wtMaintJElementM.pas' {frmWTMaintJElementM},
  wtRSQuotePerf in '..\wtRSQuotePerf.pas' {frmWTRSQuotePerf},
  wtSendFax in '..\wtSendFax.pas' {frmWTSendFax},
  wtFaxList in '..\wtFaxList.pas' {frmWTFaxList},
  wtEmailList in '..\wtEmailList.pas' {frmWTEmailList},
  wtMaintClient in '..\wtMaintClient.pas' {frmWTMaintClient},
  WTLUQuoteRpts in '..\WTLUQuoteRpts.pas' {frmWTLUQuoteRpts},
  WTRPQuotePerf in '..\WTRPQuotePerf.pas' {frmwtRPQuotePerf},
  DateSelV5 in '..\DateSelV5.pas' {DateSelV5Form},
  wtRSOutQuote in '..\wtRSOutQuote.pas' {frmWTRSOutQuote},
  WTRPOutQuote in '..\WTRPOutQuote.pas' {frmwtRPOutQuote},
  AllImages in '..\AllImages.pas' {frmAllImages},
  WTMaintSalesOrderJobLine in '..\WTMaintSalesOrderJobLine.pas' {frmWTMaintSalesOrderJobLine},
  wtLUStock in '..\wtLUStock.pas' {frmWTLUStock},
  wtStockDM in '..\wtStockDM.pas' {dtmdlStock: TDataModule},
  wtLUReps in '..\wtLUReps.pas' {frmWTLUReps},
  wtMaintReps in '..\wtMaintReps.pas' {frmWTMaintReps},
  wtLUProductGroups in '..\wtLUProductGroups.pas' {frmWTLUProductGroups},
  wtMaintMatType in '..\wtMaintMatType.pas' {frmWtMaintMatType},
  wtMaintProduct in '..\wtMaintProduct.pas' {frmWtMaintProduct},
  wtLUProducts in '..\wtLUProducts.pas' {frmWTLUProducts},
  wtMaintSalesInvoiceLine in '..\wtMaintSalesInvoiceLine.pas' {frmWTMaintSalesInvoiceLine},
  wtRSSalesInvoice in '..\wtRSSalesInvoice.pas' {frmwtRSSalesInvoice},
  wtLUSalesInvoices in '..\wtLUSalesInvoices.pas' {frmWTLUSalesInvoices},
  WTLUSalesInvoiceSO in '..\WTLUSalesInvoiceSO.pas' {frmWTLUSalesInvoiceSO},
  WTMaintSalesOrderLine in '..\WTMaintSalesOrderLine.pas' {frmWTMaintSalesOrderLine},
  wtRSSOrder in '..\wtRSSOrder.pas' {frmWTRSSOrder},
  wtLUSOLines in '..\wtLUSOLines.pas' {frmWTLUSOLines},
  WTLUSOrderRpts in '..\WTLUSOrderRpts.pas' {frmWTLUSOrderRpts},
  WTRPSOrderSchedule in '..\WTRPSOrderSchedule.pas' {frmwtRPSOrderSchedule},
  WTRSSOrderSchedule in '..\WTRSSOrderSchedule.pas' {frmWTRSSOrderSchedule},
  WTSOrderSearch in '..\WTSOrderSearch.pas' {frmWTSOrderSearch},
  WtRPJobFittingTrade in '..\WtRPJobFittingTrade.pas' {frmwtRPJobFittingTrade},
  wtMaintJobComplete in '..\wtMaintJobComplete.pas' {frmWTMaintJobComplete},
  wtLUSalesOrderQuotes in '..\wtLUSalesOrderQuotes.pas' {frmWTLUSalesOrderQuotes},
  wtLUSalesCredits in '..\wtLUSalesCredits.pas' {frmWTLUSalesCredits},
  WTLUSalesInvoiceCN in '..\WTLUSalesInvoiceCN.pas' {frmWTLUSalesInvoiceCN},
  wtRSSalesInvoiceReprint in '..\wtRSSalesInvoiceReprint.pas' {frmWTRSSalesInvoiceReprint},
  wtAccExport1 in '..\wtAccExport1.pas' {frmWTAccExport1},
  WTAccExport2 in '..\WTAccExport2.pas' {frmWTAccExport2},
  WTAccExport3 in '..\WTAccExport3.pas' {frmWTAccExport3},
  WTAccExportDM in '..\WTAccExportDM.pas' {dmAccExport: TDataModule},
  WTAccExport4 in '..\WTAccExport4.pas' {frmWTAccExport4},
  WTAccExportFactInvs in '..\WTAccExportFactInvs.pas' {frmWTAccExportFactInvs},
  wtLoginError in '..\wtLoginError.pas' {frmWTLoginError},
  wtLicence in '..\wtLicence.pas' {frmWTLicence},
  WTLUJobRpts in '..\WTLUJobRpts.pas' {frmWTLUJobRpts},
  wtRSOutJobs in '..\wtRSOutJobs.pas' {frmWTRSOutJobs},
  WTRPOutJobs in '..\WTRPOutJobs.pas' {frmwtRPOutJobs},
  WTRPSOAntInvoice in '..\WTRPSOAntInvoice.pas' {frmwtRPSOAntInvoice},
  wtRSSOAntInvoice in '..\wtRSSOAntInvoice.pas' {frmWTRSSOAntInvoice},
  wtRPTemplate in '..\wtRPTemplate.pas' {frmwtRPTemplate},
  WTDeleteHistory in '..\WTDeleteHistory.pas' {frmWTDeleteHistory},
  WTUtilitiesDM in '..\WTUtilitiesDM.pas' {dtmdlUtilities: TDataModule},
  wtLUSalesLead in '..\wtLUSalesLead.pas' {frmWTLUSalesLead},
  wtLUFitters in '..\wtLUFitters.pas' {frmWTLUFitters},
  wtMaintFitters in '..\wtMaintFitters.pas' {frmWTMaintFitters},
  WTLUDesigner in '..\WTLUDesigner.pas' {frmWTLUDesigner},
  WTMaintBranch in '..\WTMaintBranch.pas' {frmWTMaintBranch},
  WTMaintDesigner in '..\WTMaintDesigner.pas' {frmWTMaintDesigner},
  WTRSJobValue in '..\WTRSJobValue.pas' {frmWTRSJobValue},
  WTRPJobValue in '..\WTRPJobValue.pas' {frmWTRPJobValue},
  wtRSQuoteSalesLead in '..\wtRSQuoteSalesLead.pas' {frmWTRSQuoteSalesLead},
  WTRPQuoteSalesLead in '..\WTRPQuoteSalesLead.pas' {frmwtRPQuoteSalesLead},
  wtLUCutOutDetails in '..\wtLUCutOutDetails.pas' {frmWTLUCutOutDetails},
  WTLUEdgeDetails in '..\WTLUEdgeDetails.pas' {frmWTLUEdgeDetails},
  wtMaintWT in '..\wtMaintWT.pas' {frmWTMaintWT},
  wtRPJob in '..\wtRPJob.pas' {frmwtRPJob},
  WTLUManageMentRpts in '..\WTLUManageMentRpts.pas' {frmWTLUManagementRpts},
  wtMaintCutOutDetails in '..\wtMaintCutOutDetails.pas' {frmWTMaintCutOutDetails},
  WtRPJobFitting in '..\Aktiv\Reports\WtRPJobFitting.pas' {frmwtRPJobFitting},
  WTQuoteSearch in '..\WTQuoteSearch.pas' {frmWTQuoteSearch},
  WTMaintContactEvents in '..\WTMaintContactEvents.pas' {frmWTMaintContactEvents},
  WTEventsDM in '..\WTEventsDM.pas' {dtmdlEvents: TDataModule},
  wtDBMemo in '..\wtDBMemo.pas' {frmwtDBMemo},
  WtAccImportDM in '..\WtAccImportDM.pas' {dmAccImport: TDataModule},
  WTFileImport in '..\WTFileImport.pas' {frmWTFileImport},
  wtLUDataSource in '..\wtLUDataSource.pas' {frmWTLUDataSource},
  wtMaintDataSource in '..\wtMaintDataSource.pas' {frmWTMaintDataSource},
  WTLUContactType in '..\WTLUContactType.pas' {frmWTLUContactType},
  WTMaintContactType in '..\WTMaintContactType.pas' {frmWTMaintContactType},
  wtMaintProspectAction in '..\wtMaintProspectAction.pas' {frmWTMaintProspectAction},
  wtLUProspectAction in '..\wtLUProspectAction.pas' {frmWTLUProspectAction},
  WTLUCustomerRpts in '..\WTLUCustomerRpts.pas' {frmWTLUCustomerRpts},
  WTRSCustomerAction in '..\WTRSCustomerAction.pas' {frmWTRSCustomerAction},
  WTRPCustomerAction in '..\WTRPCustomerAction.pas' {frmwtRPCustomerAction},
  WTRPJobCutSched in '..\Aktiv\Reports\WTRPJobCutSched.pas' {frmWTRPJobCutSched},
  WTRPSalesOrder in '..\WTRPSalesOrder.pas' {frmwtRPSalesOrder},
  WTRSSalesOrder in '..\WTRSSalesOrder.pas' {frmWTRSSalesOrder},
  wtRSQuoteEvent in '..\wtRSQuoteEvent.pas' {frmWTRSQuoteEvent},
  WTRPQuoteEvent in '..\WTRPQuoteEvent.pas' {frmWTRPQuoteEvent},
  WTRSCustContDet in '..\WTRSCustContDet.pas' {frmWTRSCustContDet},
  WTRPCustContDet in '..\WTRPCustContDet.pas' {frmWTRPCustContDet},
  wtRSTemplateSheet in '..\wtRSTemplateSheet.pas' {frmWTRSTemplateSheet},
  wtLUMaterialUse in '..\wtLUMaterialUse.pas' {frmWTLUMaterialUse},
  wtLUWorktopDetails in '..\wtLUWorktopDetails.pas' {frmWTLUWorktopDetails},
  WTMaintWorktopDetails in '..\WTMaintWorktopDetails.pas' {frmWTMaintWorktopDetails},
  WTLUWorktopPrices in '..\WTLUWorktopPrices.pas' {frmWTLUWorktopPrices},
  WTLUSupplier in '..\WTLUSupplier.pas' {frmWTLUSupplier},
  WTMaintSupplier in '..\WTMaintSupplier.pas' {frmWTMaintSupplier},
  WTSupplierSearch in '..\WTSupplierSearch.pas' {frmWTSupplierSearch},
  WTMaintSupplierContact in '..\WTMaintSupplierContact.pas' {frmWTMaintSupplierContact},
  WTLUSupplierContacts in '..\WTLUSupplierContacts.pas' {frmWTLUSupplierContacts},
  wtMaintQSlab in '..\wtMaintQSlab.pas' {frmWTMaintQSlab},
  wtRPSOrder in '..\Aktiv\Reports\wtRPSOrder.pas' {frmwtRPSOrder},
  wtRPSalesInvoice in '..\Aktiv\Reports\wtRPSalesInvoice.pas' {frmWTRPSalesInvoice},
  WTRPQuoteImpLevel in '..\WTRPQuoteImpLevel.pas' {frmWTRPQuoteImpLevel},
  WTRSQuoteImpLevel in '..\WTRSQuoteImpLevel.pas' {frmWTRSQuoteImpLevel},
  WTRSQuoteDecline in '..\WTRSQuoteDecline.pas' {frmWTRSQuoteDecline},
  WTRPQuoteDecline in '..\WTRPQuoteDecline.pas' {frmwtRPQuoteDecline},
  WTParamsHelp in '..\WTParamsHelp.pas' {frmWTParamsHelp},
  wtRPQuote in '..\Aktiv\Reports\wtRPQuote.pas' {frmwtRPQuote},
  WTLUPrices in '..\WTLUPrices.pas' {frmWTLUPrices},
  WTRPSOrderAllocation in '..\Aktiv\Reports\WTRPSOrderAllocation.pas' {frmWTRPSOrderAllocation},
  wtRPJobSheetClient in '..\wtRPJobSheetClient.pas' {frmwtRPJobSheetClient},
  wtRPPOrder in '..\Aktiv\Reports\wtRPPOrder.pas' {frmwtRPPOrder},
  WTLUPOrderSalesOrderLine in '..\WTLUPOrderSalesOrderLine.pas' {frmWTLUPOrderSalesOrderLine},
  WTMaintPurchaseOrder in '..\WTMaintPurchaseOrder.pas' {frmWTMaintPurchaseOrder},
  WTMaintPurchaseOrderLine in '..\WTMaintPurchaseOrderLine.pas' {frmWTMaintPurchaseOrderLine},
  WTMaintPurchaseOrderLineProd in '..\WTMaintPurchaseOrderLineProd.pas' {frmWTMaintPurchaseOrderLineProd},
  wtMaintSOEvents in '..\wtMaintSOEvents.pas' {frmWTMaintSOEvents},
  wtMaintPOEvents in '..\wtMaintPOEvents.pas' {frmWTMaintPOEvents},
  wtRPQuoteSummary in '..\Aktiv\Reports\wtRPQuoteSummary.pas' {frmwtRPQuoteSummary},
  WTRPContractDetails in '..\WTRPContractDetails.pas' {frmwtRPContractDetails},
  WTRPContractOrders in '..\WTRPContractOrders.pas' {frmwtRPContractOrders},
  WTRPSOCostAnalysis in '..\WTRPSOCostAnalysis.pas' {frmWTRPSOCostAnalysis},
  WTRPSOrderTemplate in '..\WTRPSOrderTemplate.pas' {frmwtRPSOrderTemplate},
  WTRPSOProduction in '..\WTRPSOProduction.pas' {frmWTRPSOProduction},
  WTRPSalesOrderInvoice in '..\WTRPSalesOrderInvoice.pas' {frmWTRPSalesOrderInvoice},
  WTRPMaterialAnalysis in '..\WTRPMaterialAnalysis.pas' {frmWTRPMaterialAnalysis},
  wtRSMaterialAnalysis in '..\wtRSMaterialAnalysis.pas' {frmWTRSMaterialAnalysis},
  WTRPSalesbyInvoice in '..\WTRPSalesbyInvoice.pas' {frmwtRPSalesbyInvoice},
  WTRPSIPayments in '..\WTRPSIPayments.pas' {frmwtRPSIPayments},
  WTRPSalesInvoicePayments in '..\WTRPSalesInvoicePayments.pas' {frmWTRPSalesInvoicePayments},
  wtPurchasesDM in '..\wtPurchasesDM.pas' {dtmdlPurchaseOrder: TDataModule},
  WTPricesDM in '..\WTPricesDM.pas' {dtmdlPrices: TDataModule},
  Printer.Enums in '..\..\PrinterTools\Printer.Enums.pas',
  Printer.Interfaces in '..\..\PrinterTools\Printer.Interfaces.pas',
  Printer.Tools in '..\..\PrinterTools\Printer.Tools.pas',
  DragAndDrop.Interfaces in '..\..\Drag and Drop Tools\DragAndDrop.Interfaces.pas',
  DragAndDrop.Tools in '..\..\Drag and Drop Tools\DragAndDrop.Tools.pas';

{$R *.RES}

begin
  {$IFDEF DEBUG}
  ReportMemoryLeaksOnShutdown := True;
  {$ENDIF}
  Application.Initialize;
  frmWTSplash := TfrmWTSplash.Create( Application );
  frmWTSplash.Show;
  frmWTSplash.Refresh;
  Application.Title := 'Worktop Manufacturing';
  Application.MainFormOnTaskBar := True;
  Application.CreateForm(TdtmdlWorktops, dtmdlWorktops);
  Application.CreateForm(TfrmWTMain, frmWTMain);
  Application.CreateForm(TfrmWTSendFax, frmWTSendFax);
  Application.CreateForm(TfrmAllImages, frmAllImages);
  Application.Run;
end.
