program Firebelly_Romany;

uses
  Forms,
  wtSplash in '..\wtSplash.pas' {frmWTSplash},
  wtDatabase in '..\wtDatabase.pas' {frmWTDatabase},
  wtCustomerDM in '..\wtCustomerDM.pas' {dtmdlCustomers: TDataModule},
  wtDataModule in '..\wtDataModule.pas' {dtmdlWorktops: TDataModule},
  wtLUThickness in '..\wtLUThickness.pas' {frmWtLUThickness},
  wtLUworktops in '..\wtLUworktops.pas' {frmWtLUWorktops},
  WTMaintParams in '..\WTMaintParams.pas' {frmWTMaintParams},
  wtLUMatType in '..\wtLUMatType.pas' {frmWTLUMatType},
  wtMaintProductGroup in '..\wtMaintProductGroup.pas' {frmWtMaintProductGroup},
  wtMaintThickness in '..\wtMaintThickness.pas' {frmWtMaintThickness},
  wtLUWTThickness in '..\wtLUWTThickness.pas' {frmWTLUWTThickness},
  WTMaintWTThickness in '..\WTMaintWTThickness.pas' {frmWTMaintWTThickness},
  wtLUCustomer in '..\wtLUCustomer.pas' {frmWTLUCustomer},
  WTAutoPriceChange in '..\WTAutoPriceChange.pas' {frmWTAutoPriceChange},
  wtMaintQuote in '..\wtMaintQuote.pas' {frmWTMaintQuote},
  WTMaintCustomer in '..\WTMaintCustomer.pas' {frmWtMaintCustomer},
  wtLUAddChgs in '..\wtLUAddChgs.pas' {frmWTLUAddChgs},
  wtLUCustQuotes in '..\wtLUCustQuotes.pas' {frmwtLUCustQuotes},
  wtLUCustJobs in '..\wtLUCustJobs.pas' {frmwtLUCustJobs},
  wtLUCustInvoices in '..\wtLUCustInvoices.pas' {frmwtLUCustInvoices},
  WTCustJobsDM in '..\WTCustJobsDM.pas' {dtmdlCustJobs: TDataModule},
  WTCustInvoicesDM in '..\WTCustInvoicesDM.pas' {dtmdlCustInvoices: TDataModule},
  wtAboutBox in '..\wtAboutBox.pas' {frmwtAboutBox},
  wtMain in '..\wtMain.pas' {frmWTMain},
  WTQuotesDM in '..\WTQuotesDM.pas' {dtmdlQuote: TDataModule},
  wtCommon in '..\wtCommon.pas',
  wtLUQuotes in '..\wtLUQuotes.pas' {frmwtLUQuotes},
  wtNotesDM in '..\wtNotesDM.pas' {dtmdlNotes: TDataModule},
  wtLUEdges in '..\wtLUEdges.pas' {frmwtLUEdges},
  WTMaintEdges in '..\WTMaintEdges.pas' {frmWTMaintEdges},
  wtMaintCutOuts in '..\wtMaintCutOuts.pas' {frmWTMaintCutOuts},
  wtMaintEdgeDetails in '..\wtMaintEdgeDetails.pas' {frmWTMaintEdgeDetails},
  wtLUCustType in '..\wtLUCustType.pas' {frmWTLUCustType},
  wtMaintCustTypes in '..\wtMaintCustTypes.pas' {frmWTMaintCustTypes},
  wtLUVat in '..\wtLUVat.pas' {frmwtLUVat},
  wtMaintVat in '..\wtMaintVat.pas' {frmwtMaintVat},
  AllCommon in '..\AllCommon.pas',
  WTSrchCustomer in '..\WTSrchCustomer.pas' {frmWTSrchCustomer},
  wtMaintQUpstand in '..\wtMaintQUpstand.pas' {frmWTMaintQUpstand},
  wtMaintQCutOut in '..\wtMaintQCutOut.pas' {frmWtMaintQCutOut},
  wtMaintQEdge in '..\wtMaintQEdge.pas' {frmWTMaintQEdge},
  wtMaintQExtra in '..\wtMaintQExtra.pas' {frmWTMaintQExtra},
  wtMaintCustomerConts in '..\wtMaintCustomerConts.pas' {frmwtMaintCustomerConts},
  WTSrchCustContacts in '..\WTSrchCustContacts.pas' {frmWTSrchCustContacts},
  wtMaintQElement in '..\wtMaintQElement.pas' {frmWTMaintQElement},
  wtLUPurchases in '..\wtLUPurchases.pas' {frmwtLUPurchases},
  wtLUSales in '..\wtLUSales.pas' {frmwtLUSales},
  WTJobsDM in '..\WTJobsDM.pas' {dtmdlJob: TDataModule},
  wtLUJobs in '..\wtLUJobs.pas' {frmwtLUJobs},
  WTSalesOrderDM in '..\WTSalesOrderDM.pas' {dtmdlSalesOrder: TDataModule},
  wtMaintSalesOrder in '..\wtMaintSalesOrder.pas' {frmWTMaintSalesOrder},
  wtPurchasesDM in '..\wtPurchasesDM.pas' {dtmdlPurchase: TDataModule},
  wtMaintPurchOrders in '..\wtMaintPurchOrders.pas' {frmWTMaintPurchOrders},
  wtSalesInvoiceDM in '..\wtSalesInvoiceDM.pas' {dtmdlSalesInvoice: TDataModule},
  wtMaintSalesInvoice in '..\wtMaintSalesInvoice.pas' {frmWTMaintSalesInvoice},
  wtRSQuote in '..\wtRSQuote.pas' {frmWTRSQuote},
  wtLUWTGroup in '..\wtLUWTGroup.pas' {frmWTLUWTGroup},
  WTMaintWTGroup in '..\WTMaintWTGroup.pas' {frmWTMaintWTGroup},
  wtMaintAddChgs in '..\wtMaintAddChgs.pas' {frmwtMaintAddChgs},
  wtMaintJob in '..\wtMaintJob.pas' {frmWTMaintJob},
  wtMaintJUpstand in '..\wtMaintJUpstand.pas' {frmWTMaintJUpstand},
  wtMaintJEdge in '..\wtMaintJEdge.pas' {frmWTMaintJEdge},
  wtMaintJElement in '..\wtMaintJElement.pas' {frmWTMaintJElement},
  wtMaintJExtra in '..\wtMaintJExtra.pas' {frmWTMaintJExtra},
  wtMaintJCutOut in '..\wtMaintJCutOut.pas' {frmWtMaintJCutOut},
  WTRSJobCutSched in '..\WTRSJobCutSched.pas' {frmWTRSJobCutSched},
  WTRSJobMasonRpt in '..\WTRSJobMasonRpt.pas' {frmWTRSJobMasonRpt},
  WTRPJobMasonRpt in '..\WTRPJobMasonRpt.pas' {frmWTRPJobMasonRpt},
  WTRPJobCutSched in '..\WTRPJobCutSched.pas' {frmWTRPJobCutSched},
  WTQuoteSearch in '..\WTQuoteSearch.pas' {frmWTQuoteSearch},
  WTJobSearch in '..\WTJobSearch.pas' {frmWTJobSearch},
  wtMaintQEvents in '..\wtMaintQEvents.pas' {frmWTMaintQEvents},
  wtMaintJEvents in '..\wtMaintJEvents.pas' {frmWTMaintJEvents},
  wtUtilities in '..\wtUtilities.pas' {frmWTUtilities},
  wtLUOperators in '..\wtLUOperators.pas' {frmWTLUOperators},
  WTMaintOperators in '..\WTMaintOperators.pas' {frmWTMaintOperators},
  WTUpdateDB in '..\WTUpdateDB.pas' {dtmdlUpdateDB: TDataModule},
  WTLogin in '..\WTLogin.pas' {frmWTLogin},
  WtLUWTGroupPrices in '..\WtLUWTGroupPrices.pas' {frmWtLUWTGroupPrices},
  WTMaintWTGPrices in '..\WTMaintWTGPrices.pas' {frmWTMaintWTGPrices},
  wtRSJobSheet in '..\wtRSJobSheet.pas' {frmWTRSJobSheet},
  wtRPJobAccSheet in '..\wtRPJobAccSheet.pas' {frmwtRPJobAccSheet},
  wtLUEdgeTypes in '..\wtLUEdgeTypes.pas' {frmWTLUEdgeTypes},
  wtMaintEdgeType in '..\wtMaintEdgeType.pas' {frmWTMaintEdgeType},
  wtMaintQElementM in '..\wtMaintQElementM.pas' {frmWTMaintQElementM},
  wtMaintJElementM in '..\wtMaintJElementM.pas' {frmWTMaintJElementM},
  wtRSQuotePerf in '..\wtRSQuotePerf.pas' {frmWTRSQuotePerf},
  wtSendFax in '..\wtSendFax.pas' {frmWTSendFax},
  wtFaxList in '..\wtFaxList.pas' {frmWTFaxList},
  wtEmailList in '..\wtEmailList.pas' {frmWTEmailList},
  wtMaintClient in '..\wtMaintClient.pas' {frmWTMaintClient},
  WTLUQuoteRpts in '..\WTLUQuoteRpts.pas' {frmWTLUQuoteRpts},
  WTRPQuotePerf in '..\WTRPQuotePerf.pas' {frmwtRPQuotePerf},
  DateSelV5 in '..\DateSelV5.pas' {DateSelV5Form},
  wtRSOutQuote in '..\wtRSOutQuote.pas' {frmWTRSOutQuote},
  WTRPOutQuote in '..\WTRPOutQuote.pas' {frmwtRPOutQuote},
  AllImages in '..\AllImages.pas' {frmAllImages},
  WTMaintSalesOrderJobLine in '..\WTMaintSalesOrderJobLine.pas' {frmWTMaintSalesOrderJobLine},
  wtLUStock in '..\wtLUStock.pas' {frmWTLUStock},
  wtStockDM in '..\wtStockDM.pas' {dtmdlStock: TDataModule},
  wtLUReps in '..\wtLUReps.pas' {frmWTLUReps},
  wtMaintReps in '..\wtMaintReps.pas' {frmWTMaintReps},
  wtLUProductGroups in '..\wtLUProductGroups.pas' {frmWTLUProductGroups},
  wtMaintMatType in '..\wtMaintMatType.pas' {frmWtMaintMatType},
  wtMaintProduct in '..\wtMaintProduct.pas' {frmWtMaintProduct},
  wtLUProducts in '..\wtLUProducts.pas' {frmWTLUProducts},
  wtMaintSalesInvoiceLine in '..\wtMaintSalesInvoiceLine.pas' {frmWTMaintSalesInvoiceLine},
  wtRSSalesInvoice in '..\wtRSSalesInvoice.pas' {frmwtRSSalesInvoice},
  wtLUSalesInvoices in '..\wtLUSalesInvoices.pas' {frmWTLUSalesInvoices},
  WTLUSalesInvoiceSO in '..\WTLUSalesInvoiceSO.pas' {frmWTLUSalesInvoiceSO},
  WTMaintSalesOrderLine in '..\WTMaintSalesOrderLine.pas' {frmWTMaintSalesOrderLine},
  wtRSSOrder in '..\wtRSSOrder.pas' {frmWTRSSOrder},
  wtLUSOLines in '..\wtLUSOLines.pas' {frmWTLUSOLines},
  WTLUManageMentRpts in '..\WTLUManageMentRpts.pas' {frmWTLUSOrderRpts},
  WTRPSOrderTemplate in '..\WTRPSOrderTemplate.pas' {frmwtRPSOrderTemplate},
  WTRSSOrderTemplate in '..\WTRSSOrderTemplate.pas' {frmWTRSSOrderTemplate},
  WTSOrderSearch in '..\WTSOrderSearch.pas' {frmWTSOrderSearch},
  wtMaintJobComplete in '..\wtMaintJobComplete.pas' {frmWTMaintJobComplete},
  wtLUSalesOrderQuotes in '..\wtLUSalesOrderQuotes.pas' {frmWTLUSalesOrderQuotes},
  wtLUSalesCredits in '..\wtLUSalesCredits.pas' {frmWTLUSalesCredits},
  WTLUSalesInvoiceCN in '..\WTLUSalesInvoiceCN.pas' {frmWTLUSalesInvoiceCN},
  wtRSSalesInvoiceReprint in '..\wtRSSalesInvoiceReprint.pas' {frmWTRSSalesInvoiceReprint},
  wtAccExport1 in '..\wtAccExport1.pas' {frmWTAccExport1},
  WTAccExport2 in '..\WTAccExport2.pas' {frmWTAccExport2},
  WTAccExport3 in '..\WTAccExport3.pas' {frmWTAccExport3},
  WTAccExportDM in '..\WTAccExportDM.pas' {dmAccExport: TDataModule},
  WTAccExport4 in '..\WTAccExport4.pas' {frmWTAccExport4},
  WTAccExportFactInvs in '..\WTAccExportFactInvs.pas' {frmWTAccExportFactInvs},
  wtLoginError in '..\wtLoginError.pas' {frmWTLoginError},
  wtLicence in '..\wtLicence.pas' {frmWTLicence},
  WTLUJobRpts in '..\WTLUJobRpts.pas' {frmWTLUJobRpts},
  wtRSOutJobs in '..\wtRSOutJobs.pas' {frmWTRSOutJobs},
  WTRPOutJobs in '..\WTRPOutJobs.pas' {frmwtRPOutJobs},
  WTRPSOAntInvoice in '..\WTRPSOAntInvoice.pas' {frmwtRPSOAntInvoice},
  wtRSSOAntInvoice in '..\wtRSSOAntInvoice.pas' {frmWTRSSOAntInvoice},
  wtRPTemplate in '..\wtRPTemplate.pas' {frmwtRPTemplate},
  wtRPJob in '..\wtRPJob.pas' {frmwtRPJob},
  wtMaintFitters in '..\wtMaintFitters.pas' {frmWTMaintFitters},
  wtLUFitters in '..\wtLUFitters.pas' {frmWTLUFitters},
  wtMaintJRemedial in '..\wtMaintJRemedial.pas' {frmWTMaintJRemedial},
  wtMaintSalesLead in '..\wtMaintSalesLead.pas' {frmWTMaintSalesLead},
  wtLUSalesLead in '..\wtLUSalesLead.pas' {frmWTLUSalesLead},
  WTRPQuoteSalesLead in '..\WTRPQuoteSalesLead.pas' {frmwtRPQuoteSalesLead},
  wtRSQuoteSalesLead in '..\wtRSQuoteSalesLead.pas' {frmWTRSQuoteSalesLead},
  wtRSJobFitting in '..\wtRSJobFitting.pas' {frmWTRSJobFitting},
  WTLUEdgeDetails in '..\WTLUEdgeDetails.pas' {frmWTLUEdgeDetails},
  wtLUCutOutDetails in '..\wtLUCutOutDetails.pas' {frmWTLUCutOutDetails},
  wtMaintCutOutDetails in '..\wtMaintCutOutDetails.pas' {frmWTMaintCutOutDetails},
  wtLUCutOuts in '..\wtLUCutOuts.pas' {frmWTLUCutOuts},
  WTMaintTrade in '..\WTMaintTrade.pas' {frmWTMaintTrade},
  wtWin7 in '..\wtWin7.pas',
  Printer.Enums in '..\..\PrinterTools\Printer.Enums.pas',
  Printer.Interfaces in '..\..\PrinterTools\Printer.Interfaces.pas',
  Printer.Tools in '..\..\PrinterTools\Printer.Tools.pas',
  WtRPJobFitting in '..\Romany\Reports\WtRPJobFitting.pas' {frmwtRPJobFitting},
  WtRPJobFittingTrade in '..\Romany\Reports\WtRPJobFittingTrade.pas' {frmwtRPJobFittingTrade},
  WtRPJobSheet in '..\Romany\Reports\WtRPJobSheet.pas' {frmwtRPJobSheet},
  wtRPQuote in '..\Romany\Reports\wtRPQuote.pas' {frmwtRPQuote},
  wtRPQuoteTrade in '..\Romany\Reports\wtRPQuoteTrade.pas' {frmwtRPQuoteTrade},
  wtRPSalesInvoice in '..\Romany\Reports\wtRPSalesInvoice.pas' {frmWTRPSalesInvoice},
  wtRPSOrder in '..\Romany\Reports\wtRPSOrder.pas' {frmwtRPSOrder};

{$R *.RES}

begin
  {$IFDEF DEBUG}
  ReportMemoryLeaksOnShutdown := True;
  {$ENDIF}
  Application.Initialize;
  frmWTSplash := TfrmWTSplash.Create( Application );
  frmWTSplash.Show;
  frmWTSplash.Refresh;
  Application.Title := 'Worktop Manufacturing';
  Application.CreateForm(TdtmdlWorktops, dtmdlWorktops);
  Application.CreateForm(TfrmWTMain, frmWTMain);
  Application.CreateForm(TfrmWTSendFax, frmWTSendFax);
  Application.CreateForm(TfrmAllImages, frmAllImages);
  Application.CreateForm(TfrmwtRPJobFitting, frmwtRPJobFitting);
  Application.CreateForm(TfrmwtRPJobFittingTrade, frmwtRPJobFittingTrade);
  Application.CreateForm(TfrmwtRPJobSheet, frmwtRPJobSheet);
  Application.CreateForm(TfrmwtRPQuote, frmwtRPQuote);
  Application.CreateForm(TfrmwtRPQuoteTrade, frmwtRPQuoteTrade);
  Application.CreateForm(TfrmWTRPSalesInvoice, frmWTRPSalesInvoice);
  Application.CreateForm(TfrmwtRPSOrder, frmwtRPSOrder);
  Application.Run;
end.
