program redeye;

uses
  Forms,
  PBWin7 in '..\PBWin7.pas',
  pbMainMenu in '..\pbMainMenu.pas' {frmpbMainMenu},
  pbluCustomers in '..\pbluCustomers.pas' {frmpbluCustomers},
  pbluSuppliers in '..\pbluSuppliers.pas' {frmpbluSuppliers},
  pbDatabase in '..\pbDatabase.pas' {dmBroker: TDataModule},
  pbLogin in '..\pbLogin.pas' {frmpbLogin},
  pbEnvSel in '..\pbEnvSel.pas' {frmpbEnvSel},
  pbCustomerDm in '..\pbCustomerDm.pas' {dtmdlCustomers: TDataModule},
  pbluCustOrders in '..\pbluCustOrders.pas' {frmpbluCustOrders},
  pbOrdersDm in '..\pbOrdersDm.pas' {dtmdlOrders: TDataModule},
  pbSupplierDm in '..\pbSupplierDm.pas' {dtmdlSuppliers: TDataModule},
  pbluOrdersSearch in '..\pbluOrdersSearch.pas' {frmpbluOrdersSearch},
  PBMaintCust in '..\PBMaintCust.pas' {PBMaintCustFrm},
  CCSPrint in '..\..\CCSCOMMOND7\CCSPrint.pas',
  pbluCustBrSelect in '..\pbluCustBrSelect.pas' {frmpbluCustBrSelect},
  PBImages in '..\PBImages.pas' {PBImagesFrm},
  PBDBMemo in '..\PBDBMemo.pas' {PBDBMemoFrm},
  PBDelivNotes in '..\PBDelivNotes.pas' {PBDelivNotesFrm},
  PBMaintCompany in '..\PBMaintCompany.pas' {PBMaintCompanyFrm},
  pbluSupplierSelect in '..\pbluSupplierSelect.pas' {frmpbluSupplierSelect},
  PBLUPrdTyp in '..\PBLUPrdTyp.pas' {PBLUPrdTypFrm},
  PBMaintRep in '..\PBMaintRep.pas' {PBMaintRepFrm},
  PBLURep in '..\PBLURep.pas' {PBLURepFrm},
  PBLUAdHoc in '..\PBLUAdHoc.pas' {PBLUAdHocFrm},
  PBLUCust in '..\PBLUCust.pas' {PBLUCustFrm},
  PBLUPrdTypCap in '..\PBLUPrdTypCap.pas' {PBLUPrdTypCapFrm},
  PBLUPrdTypOChg in '..\PBLUPrdTypOChg.pas' {PBLUPrdTypOChgFrm},
  PBLUPrdTypQu in '..\PBLUPrdTypQu.pas' {PBLUPrdTypQuFrm},
  PBLUPrdTypQuList in '..\PBLUPrdTypQuList.pas' {PBLUPrdTypQuListfrm},
  PBLURepNom in '..\PBLURepNom.pas' {PBLURepNomFrm},
  PBLUSConta in '..\PBLUSConta.pas' {PBLUSContaFrm},
  PBLUSupBrch in '..\PBLUSupBrch.pas' {PBLUSupBrchFrm},
  PBLUSupp in '..\PBLUSupp.pas' {PBLUSuppFrm},
  PBMaintAdHoc in '..\PBMaintAdHoc.pas' {PBMaintAdHocFrm},
  PBMaintGroups in '..\PBMaintGroups.pas' {PBMaintGroupsFrm},
  PBMaintGroupsDets in '..\PBMaintGroupsDets.pas' {PBMaintGroupsDetsFrm},
  PBMaintPrdTyp in '..\PBMaintPrdTyp.pas' {PBMaintPrdTypFrm},
  PBMaintPrdTypCap in '..\PBMaintPrdTypCap.pas' {PBMaintPrdTypCapFrm},
  PBMaintPrdTypOChg in '..\PBMaintPrdTypOChg.pas' {PBMaintPrdTypOChgFrm},
  PBMaintPrdTypQu in '..\PBMaintPrdTypQu.pas' {PBMaintPrdTypQuFrm},
  PBMaintRepNom in '..\PBMaintRepNom.pas' {PBMaintRepNomFrm},
  PBMaintSConta in '..\PBMaintSConta.pas' {PBMaintSContaFrm},
  PBMaintSupBrch in '..\PBMaintSupBrch.pas' {PBMaintSupBrchFrm},
  PBMaintSupp in '..\PBMaintSupp.pas' {PBMaintSuppFrm},
  PBMaintSuppCap in '..\PBMaintSuppCap.pas' {PBMaintSuppCapFrm},
  PBMaintSpecIns in '..\PBMaintSpecIns.pas' {PBMaintSpecInsFrm},
  PBLUSpecIns in '..\PBLUSpecIns.pas' {PBLUSpecInsFrm},
  PBLUAddCharges in '..\PBLUAddCharges.pas' {PBLUAddChrgFrm},
  PBLUPriceUnit in '..\PBLUPriceUnit.pas' {PBLUPriceUnitFrm},
  PBMaintAddChrgs in '..\PBMaintAddChrgs.pas' {PBMaintAddChrgsFrm},
  PBMaintPriceUnit in '..\PBMaintPriceUnit.pas' {PBMaintPriceUnitFrm},
  PBLUStandSize in '..\PBLUStandSize.pas' {PBLUStandSizeFrm},
  PBMaintPaper in '..\PBMaintPaper.pas' {PBMaintPaperFrm},
  PBMaintStandSize in '..\PBMaintStandSize.pas' {PBMaintStandSizeFrm},
  PBLUArtwrkTyp in '..\PBLUArtwrkTyp.pas' {PBLUArtwrkTypFrm},
  PBMaintArtwrkTyp in '..\PBMaintArtwrkTyp.pas' {PBMaintArtwrkTypFrm},
  PBMaintOpsDet in '..\PBMaintOpsDet.pas' {PBMaintOpsDetFrm},
  PBLUOps in '..\PBLUOps.pas' {PBLUOpsFrm},
  PBAuditControl in '..\PBAuditControl.pas' {PBAuditControlFrm},
  PBMaintInterf in '..\PBMaintInterf.pas' {PBMaintInterfFrm},
  PBMaintLastNos in '..\PBMaintLastNos.pas' {PBMaintLastNosFrm},
  PBMaintOpsDetPass in '..\PBMaintOpsDetPass.pas' {PBMaintOpsDetPassFrm},
  PBMaintVATCode in '..\PBMaintVATCode.pas' {PBMaintVATCodeFrm},
  PBAuditDM in '..\PBAuditDM.pas' {PBAuditDataMod: TDataModule},
  PBLUBranch in '..\PBLUBranch.pas' {PBLUBranchFrm},
  PBLUCConta in '..\PBLUCConta.pas' {PBLUCContaFrm},
  PBLUCContaEvents in '..\PBLUCContaEvents.pas' {PBLUCContaEventsFrm},
  PBLUCRep in '..\PBLUCRep.pas' {PBLUCRepFrm},
  PBLUFormRef in '..\PBLUFormRef.pas' {PBLUFormRefFrm},
  PBMaintBranch in '..\PBMaintBranch.pas' {PBMaintBranchFrm},
  PBMaintCConta in '..\PBMaintCConta.pas' {PBMaintCContaFrm},
  PBMaintContApp in '..\PBMaintContApp.pas' {PBMaintContAppfrm},
  PBMaintCRep in '..\PBMaintCRep.pas' {PBMaintCRepFrm},
  PBMaintFormRef in '..\PBMaintFormRef.pas' {PBMaintFormRefFrm},
  PBMaintPOrd in '..\PBMaintPOrd.pas' {PBMaintPOrdFrm},
  PBIntSelDM in '..\PBIntSelDM.pas' {dmIntSel: TDataModule},
  PBPOObjects in '..\PBPOObjects.pas',
  PBPODataMod in '..\PBPODataMod.pas' {PBPODM: TDataModule},
  DateSelV5 in '..\DateSelV5.pas' {DateSelV5Form},
  PBJobBagDM in '..\PBJobBagDM.pas' {dmJobBag: TDataModule},
  PBMaintPOrdLine in '..\PBMaintPOrdLine.pas' {PBMaintPOrdLineFrm},
  PBMaintPOrdLineDeliv in '..\PBMaintPOrdLineDeliv.pas' {PBMaintPOrdLineDelivFrm},
  PBMaintPOrdLineExtChg in '..\PBMaintPOrdLineExtChg.pas' {PBMaintPOrdLineExtChgFrm},
  PBLUProofHistN in '..\PBLUProofHistN.pas' {PBLUProofHistNFrm},
  PBPOAddDtls in '..\PBPOAddDtls.pas' {PBPOAddDtlsFrm},
  PBMaintPOAddNotes in '..\PBMaintPOAddNotes.pas' {PBMaintPOAddNotesFrm},
  PBPartDescDg in '..\PBPartDescDg.pas' {PBPartDescDlg},
  PBMaintPOrdLInactive in '..\PBMaintPOrdLInactive.pas' {PBMaintPOrdLInactiveFrm},
  PBLUReasCode in '..\PBLUReasCode.pas' {PBLUReasCodeFrm},
  PBMaintReasCode in '..\PBMaintReasCode.pas' {PBMaintReasCodeFrm},
  PBMaintPOrdLineCallOff in '..\PBMaintPOrdLineCallOff.pas' {PBMaintPOrdLineCallOffFrm},
  PBLUCustFormRef in '..\PBLUCustFormRef.pas' {PBLUCustFormRefFrm},
  PBMaintPOrdLView in '..\PBMaintPOrdLView.pas' {PBMaintPOrdLViewFrm},
  PBMaintIntNote in '..\PBMaintIntNote.pas' {PBMaintIntNoteFrm},
  PBRSPOrdN in '..\PBRSPOrdN.pas' {PBRSPOrdNFrm},
  CCSDataBroker in '..\..\CCSCOMMOND7\CCSDataBroker.pas' {DataBroker: TDataModule},
  LetterDM in '..\..\PAGEDESIGNER\LetterDM.pas' {dmLetter: TDataModule},
  PDLetter in '..\..\PAGEDESIGNER\PDLetter.pas',
  CCSPress in '..\..\CCSCOMMOND7\CCSPress.pas' {frmPrintingPress},
  CCSDevil in '..\..\CCSCOMMOND7\CCSDevil.pas',
  Compositor in '..\..\CCSCOMMOND7\Compositor.pas' {Compositor},
  PBDBPOrdLtr in '..\PBDBPOrdLtr.pas' {dbPOrdLtr: TDataModule},
  PBFaxList in '..\PBFaxList.pas' {PBFaxListFrm},
  PBEmailList in '..\PBEmailList.pas' {PBEmailListFrm},
  PBSendFax in '..\PBSendFax.pas' {PBSendFaxFrm},
  pbluCustStock in '..\pbluCustStock.pas' {frmpbluCustStock},
  pbStockDm in '..\pbStockDm.pas' {dtmdlStock: TDataModule},
  pbLuBranches in '..\pbLuBranches.pas' {frmpbluBranches},
  pbluCustEnquiries in '..\pbluCustEnquiries.pas' {frmpbluCustEnquiries},
  pbEnqsdm in '..\pbEnqsdm.pas' {dtmdlEnqs: TDataModule},
  pbluContacts in '..\pbluContacts.pas' {frmpbluContacts},
  pbluEnqsSearch in '..\pbluEnqsSearch.pas' {frmpbluEnqsSearch},
  STLUStkMvmnts in '..\STLUStkMvmnts.pas' {STLUStkMvmntsFrm},
  STLUStkLoc in '..\STLUStkLoc.pas' {STLUStkLocFrm},
  STLUStkBinLots in '..\STLUStkBinLots.pas' {STLUStkBinLotsFrm},
  STLUStkSales in '..\STLUStkSales.pas' {STLUStkSalesFrm},
  STLUStkProduction in '..\STLUStkProduction.pas' {STLUStkProductionFrm},
  STLUStkPurchases in '..\STLUStkPurchases.pas' {STLUStkPurchasesFrm},
  PBenquiry in '..\PBenquiry.pas' {PBEnquiryFrm},
  STSOObjects in '..\STSOObjects.pas',
  PBenqline in '..\PBenqline.pas' {PBEnqLineTmp},
  PBEnqLineDtls in '..\PBEnqLineDtls.pas' {PBEnqLineDtlsFrm},
  PBEnqAddDtls in '..\PBEnqAddDtls.pas' {PBEnqAddDtlsFrm},
  PBEnqDataMod in '..\PBEnqDataMod.pas' {PBEnqDataModFrm: TDataModule},
  PBPOToEnq in '..\PBPOToEnq.pas' {PBPOToEnqFrm},
  PBEnqSelSup in '..\PBEnqSelSup.pas' {PBEnqSelSupFrm},
  PBRSEnqN in '..\PBRSEnqN.pas' {PBRSEnqNFrm},
  PBDBEnqLtr in '..\PBDBEnqLtr.pas' {dbEnqLtr: TDataModule},
  PBEnqSuppDataMod in '..\PBEnqSuppDataMod.pas' {PBEnqSuppDataModFrm: TDataModule},
  PBEnqSupTmp in '..\PBEnqSupTmp.pas' {PBEnqSupTmpFrm},
  PBLUEnqAddChg in '..\PBLUEnqAddChg.pas' {PBLUEnqAddChgFrm},
  PBEnqRespQty in '..\PBEnqRespQty.pas' {PBEnqRespQtyFrm},
  PBEnqJobPrice in '..\PBEnqJobPrice.pas' {PBEnqJobPriceFrm},
  PBEnqJobDtls in '..\PBEnqJobDtls.pas' {PBEnqJobDtlsFrm},
  PBEnqAddChg in '..\PBEnqAddChg.pas' {PBEnqAddChgFrm},
  PBDBQuoLtr in '..\PBDBQuoLtr.pas' {dbQuoLtr: TDataModule},
  PBDBQuoSumLtr in '..\PBDBQuoSumLtr.pas' {dbQuoSumLtr: TDataModule},
  PBRSQuoN in '..\PBRSQuoN.pas' {PBRSQuoNFrm},
  STSODataMod in '..\STSODataMod.pas' {STSalesOrdDM: TDataModule},
  STMaintSOrdLineServ in '..\STMaintSOrdLineServ.pas' {STMaintSOrdLineServFrm},
  STPrtMnt in '..\STPrtMnt.pas' {STPrtMntFrm},
  STPrtMntDetsMulti in '..\STPrtMntDetsMulti.pas' {STPrtMntDetsMultiFrm},
  STPrtMntDets in '..\STPrtMntDets.pas' {STPrtMntDetsFrm},
  StMntPrtSupp in '..\StMntPrtSupp.pas' {STMntPrtSuppFrm},
  STLUPrtGrp in '..\STLUPrtGrp.pas' {STLUPrtGrpFrm},
  STMntPrtGrp in '..\STMntPrtGrp.pas' {STMntPrtGrpFrm},
  STProdImport in '..\STProdImport.pas' {STProdImportFrm},
  STMaintPrtEComm in '..\STMaintPrtEComm.pas' {STMaintPrtECommFrm},
  STMaintSOrdLine in '..\STMaintSOrdLine.pas' {STMaintSOrdLineFrm},
  CSLUCustCstCntr in '..\..\CCSCOMMOND7\CSLUCustCstCntr.pas' {CSLUCustCstCntrFrm},
  CSMaintCustCstCntr in '..\..\CCSCOMMOND7\CSMaintCustCstCntr.pas' {CsMaintCustCstCntrFrm},
  STMaintSinvExtChg in '..\STMaintSinvExtChg.pas' {STMaintSInvExtChgFrm},
  STMaintSOrdSerialNos in '..\STMaintSOrdSerialNos.pas' {STMaintSOrdSerialNosFrm},
  PBNarrativeDM in '..\PBNarrativeDM.pas' {dmNarrative: TDataModule},
  pbluCustDeliv in '..\pbluCustDeliv.pas' {frmpbluOrderdeliv},
  STPrtAllocSales in '..\STPrtAllocSales.pas' {STPrtAllocSalesFrm},
  STStockDM in '..\STStockDM.pas' {STStockDataMod: TDataModule},
  STPrtAllocStStock in '..\STPrtAllocStStock.pas' {STPrtAllocStStockFrm},
  STRSPickNote in '..\STRSPickNote.pas' {STRSPickNotefrm},
  STPickObject in '..\STPickObject.pas',
  STPickingDM in '..\STPickingDM.pas' {STPickDM: TDataModule},
  STPickbyPart in '..\STPickbyPart.pas' {STPickbyPartFrm},
  STPickItem in '..\STPickItem.pas' {STPickItemFrm},
  STRSSalesOrd in '..\STRSSalesOrd.pas' {STRSSalesOrdfrm},
  PBRSDelivNote in '..\PBRSDelivNote.pas' {PBRSDelivNoteFrm},
  PBRSBoxLabels in '..\PBRSBoxLabels.pas' {PBRSBoxLabelsfrm},
  PBMaintDeliv in '..\PBMaintDeliv.pas' {PBMaintDelivFrm},
  pbStockMoveDm in '..\pbStockMoveDm.pas' {dtmdlStockMove: TDataModule},
  PBMaintDelivBin in '..\PBMaintDelivBin.pas' {PBMaintDelivBinfrm},
  PBMntPrtBinUpd in '..\PBMntPrtBinUpd.pas' {PBMntPrtBinUpdFrm},
  PBMntPrtBin in '..\PBMntPrtBin.pas' {PBMntPrtBinFrm},
  PBDelivStock in '..\PBDelivStock.pas' {PBDelivStockFrm},
  STRSBoxLabels in '..\STRSBoxLabels.pas' {STRSBoxLabelsfrm},
  pbluCustJobs in '..\pbluCustJobs.pas' {frmpbluCustJobs},
  pbJobsDm in '..\pbJobsDm.pas' {dtmdlJobs: TDataModule},
  pbluCustJobsSearch in '..\pbluCustJobsSearch.pas' {frmpbluCustJobsSearch},
  PBMaintJobBagDets in '..\PBMaintJobBagDets.pas' {PBMaintJobBagDetsFrm},
  PBMaintJobBagRC in '..\PBMaintJobBagRC.pas' {PBMaintJobBagRCFrm},
  PBMaintQEnq in '..\PBMaintQEnq.pas' {PBMaintQEnqFrm},
  PBEnquiryDataMod in '..\PBEnquiryDataMod.pas' {PBEnqDM: TDataModule},
  PBRSProofN in '..\PBRSProofN.pas' {PBRSProofNFrm},
  PBMaintProofHistN in '..\PBMaintProofHistN.pas' {PBMaintProofHistNFrm},
  PBAutoPODets in '..\PBAutoPODets.pas' {PBAutoPODetsFrm},
  PBAutoPO in '..\PBAutoPO.pas' {PBAutoPOFrm},
  PBAutoPODataMod in '..\PBAutoPODataMod.pas' {PBAutoPODM: TDataModule},
  STMaintProduct in '..\STMaintProduct.pas' {frmSTMaintProduct},
  STMaintProductLvls in '..\STMaintProductLvls.pas' {frmSTMaintProductLvls},
  STPrtTran in '..\STPrtTran.pas' {STPrtTranFrm},
  STPrtTransQty in '..\STPrtTransQty.pas' {STPrtTransQtyFrm},
  STLUBinPrt in '..\STLUBinPrt.pas' {STLUBinPrtFrm},
  STPrtTransRecv in '..\STPrtTransRecv.pas' {STPrtTransRecvFrm},
  STPrtTransSN in '..\STPrtTransSN.pas' {STPrtTransSNFrm},
  STLUStStkNumbers in '..\STLUStStkNumbers.pas' {STLUStStkNumbersFrm},
  STMaintStStkNumbers in '..\STMaintStStkNumbers.pas' {STMaintStStkNumbersfrm},
  PBRPProof in '..\Quick Reports\Nexus\PBRPProof.pas' {PBRPProofFrm},
  PBRPDeliv in '..\Quick Reports\Nexus\PBRPDeliv.pas' {PBRPDelivFrm},
  STLUProductLvls in '..\STLUProductLvls.pas' {frmSTLUProductLvls},
  PBLUDeliveriesDM in '..\PBLUDeliveriesDM.pas' {dtmdlDeliveries: TDataModule},
  STRPDeliv in '..\Quick Reports\Nexus\STRPDeliv.pas' {STRPDelivfrm},
  STRPLabels in '..\Quick Reports\Nexus\STRPLabels.pas' {STRPLabelsFrm},
  STRPPick in '..\Quick Reports\Nexus\STRPPick.pas' {STRPPickfrm},
  STRSDelivNote in '..\STRSDelivNote.pas' {STRSDelivNotefrm},
  pbluOrders in '..\pbluOrders.pas' {frmpbLUOrders},
  pbluVatCode in '..\pbluVatCode.pas' {PBLUVATCodeFrm},
  STPrtMntLvls in '..\STPrtMntLvls.pas' {STPrtMntLvlsFrm},
  STLUSuppPrt in '..\STLUSuppPrt.pas' {STLUSuppPrtFrm},
  STRSLabels in '..\STRSLabels.pas' {STRSLabelsfrm},
  STRPBxLabels in '..\Quick Reports\Nexus\STRPBxLabels.pas' {STRPBxLabelsFrm},
  CCSMaintPrtImages in '..\..\CCSCOMMOND7\CCSMaintPrtImages.pas' {CCSMaintPrtImagesFrm},
  gifimage in '..\..\CCSCOMMOND7\gifimage.pas',
  CCSImageViewer in '..\..\CCSCOMMOND7\CCSImageViewer.pas' {CCSImageViewerFrm},
  STMntSOrd in '..\STMntSOrd.pas' {STMntSOrdFrm},
  STMntSOrdSpecIn in '..\STMntSOrdSpecIn.pas' {STMntSOrdSpecInFrm},
  pbLUEnquiries in '..\pbLUEnquiries.pas' {frmPBLuEnquiries},
  pbLuStock in '..\pbLuStock.pas' {frmPBLUStock},
  pbLuSalesOrders in '..\pbLuSalesOrders.pas' {frmPBLUSalesOrders},
  pbLuJobs in '..\pbLuJobs.pas' {frmPBLUJobs},
  pbLUSalesInvoices in '..\pbLUSalesInvoices.pas' {frmPBLUSalesInvoices},
  pbLUPurchaseInvoices in '..\pbLUPurchaseInvoices.pas' {frmPBLUPurchaseInvoices},
  PBSalesInvoiceDm in '..\PBSalesInvoiceDm.pas' {dmSalesInvoice: TDataModule},
  PBLUSalesInvoiceSO in '..\PBLUSalesInvoiceSO.pas' {PBLUSalesInvoiceSOfrm},
  PBLUSalesInvoiceCN in '..\PBLUSalesInvoiceCN.pas' {PBLUSalesInvoiceCNfrm},
  PBLUSalesInvoiceJB in '..\PBLUSalesInvoiceJB.pas' {PBLUSalesInvoiceJBfrm},
  PBLUSalesInvoiceJBL in '..\PBLUSalesInvoiceJBL.pas' {PBLUSalesInvoiceJBLfrm},
  PBLUSalesInvoicePO in '..\PBLUSalesInvoicePO.pas' {PBLUSalesInvoicePOfrm},
  PBMaintSalesInvoiceLine in '..\PBMaintSalesInvoiceLine.pas' {PBMaintSalesInvoiceLinefrm},
  PBMaintSalesInvoice in '..\PBMaintSalesInvoice.pas' {PBMaintSalesInvoicefrm},
  PBSalesInvRPrint in '..\PBSalesInvRPrint.pas' {PBSalesInvRPrintFrm},
  PBSalesInvPrint in '..\PBSalesInvPrint.pas' {PBSalesInvPrintFrm},
  PBMaintInvChgs in '..\PBMaintInvChgs.pas' {PBMaintInvChgsfrm},
  STMntStorTyp in '..\STMntStorTyp.pas' {STMntStorTypFrm},
  STLUStorTyp in '..\STLUStorTyp.pas' {STLUStorTypFrm},
  STMntPrtStor in '..\STMntPrtStor.pas' {STMntPrtStorFrm},
  STLUPrtStor in '..\STLUPrtStor.pas' {STLUPrtStorFrm},
  STMntPrtBinUpd in '..\STMntPrtBinUpd.pas' {STMntPrtBinUpdFrm},
  STMntPrtBin in '..\STMntPrtBin.pas' {STMntPrtBinFrm},
  pbLUStockRpts in '..\pbLUStockRpts.pas' {frmPBLUStockRpts},
  STRSStkBalRep in '..\STRSStkBalRep.pas' {STRSStkBalRepfrm},
  STRPStkBalRep2 in '..\STRPStkBalRep2.pas' {STRPStkBalRep2frm},
  STRPStkBalRep in '..\STRPStkBalRep.pas' {STRPStkBalRepfrm},
  STFaxList in '..\STFaxList.pas' {STFaxListFrm},
  STEmailList in '..\STEmailList.pas' {STEmailListFrm},
  StMovSl in '..\StMovSl.pas' {StMovSlfrm},
  StMovRep in '..\StMovRep.pas' {StMovRepFrm},
  STRSSlwMvngStkRep in '..\STRSSlwMvngStkRep.pas' {STRSSlwMvngStkRepfrm},
  STRPSlwMvngStkRep in '..\STRPSlwMvngStkRep.pas' {STRPSlwMvngStkRepfrm},
  STNegStkRep in '..\STNegStkRep.pas' {STNegStkRepFrm},
  STNegStksl in '..\STNegStksl.pas' {STNegStkSlfrm},
  STRSStkVal in '..\STRSStkVal.pas' {STRSStkValfrm},
  STStkValSl in '..\STStkValSl.pas' {STStkValSlfrm},
  STStkValRep in '..\STStkValRep.pas' {STStkValRepFrm},
  STStkVarRep in '..\STStkVarRep.pas' {STStkVarRepFrm},
  STRSAgedStk in '..\STRSAgedStk.pas' {STRSAgedStkFrm},
  STRPAgedStk in '..\STRPAgedStk.pas' {STRPAgedStkFrm},
  STRPSalesByCust in '..\STRPSalesByCust.pas' {STRPSalesByCustFrm},
  STRSSalesByCust in '..\STRSSalesByCust.pas' {STRSSalesByCustFrm},
  STLUSordDM in '..\STLUSordDM.pas' {DmLookupSOrd: TDataModule},
  STRPSOHistory in '..\STRPSOHistory.pas' {STRPSOHistoryFrm},
  STRSSOHistory in '..\STRSSOHistory.pas' {STRSSOHistoryFrm},
  STLUPrtByCustOrder in '..\STLUPrtByCustOrder.pas' {STLUPrtByCustOrderFrm},
  STRPWorkIP in '..\STRPWorkIP.pas' {STRPWorkIPfrm},
  STRSWorkIP in '..\STRSWorkIP.pas' {STRSWorkIPfrm},
  STPartSuppSel in '..\STPartSuppSel.pas' {STPartSuppSelFrm},
  STRPCustProdUsage in '..\STRPCustProdUsage.pas' {STRPCustProdUsagefrm},
  STRPCustStkBal in '..\STRPCustStkBal.pas' {STRPCustStkBalfrm},
  STRSCustProdUsage in '..\STRSCustProdUsage.pas' {STRSCustProdUsageFrm},
  STRSCustStkBal in '..\STRSCustStkBal.pas' {STRSCustStkBalfrm},
  STPartSuppRep in '..\STPartSuppRep.pas' {STPartSuppRepFrm},
  STPartSuppDM in '..\STPartSuppDM.pas' {STPartSDM: TDataModule},
  CCSemailHandler in '..\..\CCSCOMMOND7\CCSemailHandler.pas' {emailHandler: TDataModule},
  CCSEmailList in '..\..\CCSCOMMOND7\CCSEmailList.pas' {CCSEmailListFrm},
  STRSBoxLabelsDeliv in '..\STRSBoxLabelsDeliv.pas' {STRSBoxLabelsDelivFrm},
  STRPLabelsDeliv in '..\Quick Reports\Nexus\STRPLabelsDeliv.pas' {STRPLabelsdelivFrm},
  pbLUOrderRpts in '..\pbLUOrderRpts.pas' {frmPBLUOrderRpts},
  PBFaxToOne in '..\PBFaxToOne.pas' {PBFaxToOneFrm},
  PBEmailToOne in '..\PBEmailToOne.pas' {PBEmailToOneFrm},
  PBRSEnqSel in '..\PBRSEnqSel.pas' {PBRSEnqSelFrm},
  PBRPEnqLst in '..\PBRPEnqLst.pas' {PBRPEnqLstFrm},
  PBEnqNote in '..\PBEnqNote.pas' {PBEnqNoteFrm},
  PBEnqQuantities in '..\PBEnqQuantities.pas' {PBEnqQuantitiesFrm},
  PBEnqSuppRespns in '..\PBEnqSuppRespns.pas' {PBEnqSuppRespnsFrm},
  PBEnqSupResp in '..\PBEnqSupResp.pas' {PBEnqSupRespFrm},
  pbLUJobRpts in '..\pbLUJobRpts.pas' {frmPBLUJobRpts},
  PBRDPORep in '..\PBRDPORep.pas' {PBRDPORepDataMod: TDataModule},
  PBRSWorkIP in '..\PBRSWorkIP.pas' {PBRSWorkIPfrm},
  PBRP4CastSumm in '..\PBRP4CastSumm.pas' {PBRP4CastSummFrm},
  PBRS4CastInvs in '..\PBRS4CastInvs.pas' {PBRS4CastInvsFrm},
  PBRS4CastSumm in '..\PBRS4CastSumm.pas' {PBRS4CastSummfrm},
  PBRP4CastInvs in '..\PBRP4CastInvs.pas' {PBRP4CastInvsFrm},
  PBRSRptOrds in '..\PBRSRptOrds.pas' {PBRSRptOrdsFrm},
  PBRPRptOrds in '..\PBRPRptOrds.pas' {PBRPRptOrdsFrm},
  PBRPWorkIP in '..\PBRPWorkIP.pas' {PBRPWorkIPfrm},
  PBRSJBMargin in '..\PBRSJBMargin.pas' {PBRSJBMarginfrm},
  PBRSODueEnq in '..\PBRSODueEnq.pas' {PBRSODueEnqFrm},
  PBRSODueQte in '..\PBRSODueQte.pas' {PBRSODueQteFrm},
  PBRSPODue in '..\PBRSPODue.pas' {PBRSPODueFrm},
  PBRSPORepM in '..\PBRSPORepM.pas' {PBRSPORepMFrm},
  PBRSPOREP in '..\PBRSPOREP.pas' {PBRSPORepFrm},
  PBRPPOnotonJB in '..\PBRPPOnotonJB.pas' {PBRPPOnotonJBfrm},
  PBRSPOnotonJB in '..\PBRSPOnotonJB.pas' {PBRSPOnotonJBfrm},
  pbLUSalesInvRpts in '..\pbLUSalesInvRpts.pas' {frmPBLUSalesInvRpts},
  PBRPJBMargin in '..\PBRPJBMargin.pas' {PBRPJBMarginFrm},
  PBRPODueEnq in '..\PBRPODueEnq.pas' {PBRPODueEnqFrm},
  PBRPODueQte in '..\PBRPODueQte.pas' {PBRPODueQteFrm},
  PBRPPODue in '..\PBRPPODue.pas' {PBRPPODueFrm},
  PBRPPORep in '..\PBRPPORep.pas' {PBRPPORepFrm},
  PBRPPORepM in '..\PBRPPORepM.pas' {PBRPPORepMFrm},
  PBRPRepProfitSumm in '..\PBRPRepProfitSumm.pas' {PBRPRepProfitSummFrm},
  PBRPSalesByInv in '..\PBRPSalesByInv.pas' {PBRPSalesByInvFrm},
  PBRPSalesByInvDet in '..\PBRPSalesByInvDet.pas' {PBRPSalesByInvDetFrm},
  PBRPSalesbyProd in '..\PBRPSalesbyProd.pas' {PBRPSalesbyProdFrm},
  PBRPSalesComm in '..\PBRPSalesComm.pas' {PBRPSalesCommFrm},
  PBRPSalesCommbyCat in '..\PBRPSalesCommbyCat.pas' {PBRPSalesCommbyCatFrm},
  PBRPSalesProfit in '..\PBRPSalesProfit.pas' {PBRPSalesProfitFrm},
  PBRPSalesProfitSumm in '..\PBRPSalesProfitSumm.pas' {PBRPSalesProfitSummFrm},
  PBRSCustState in '..\PBRSCustState.pas' {PBRSCustStateFrm},
  PBRSCustTurn in '..\PBRSCustTurn.pas' {PBRSCustTurnFrm},
  PBRSSalesByInv in '..\PBRSSalesByInv.pas' {PBRSSalesByInvFrm},
  PBRSSalesByProd in '..\PBRSSalesByProd.pas' {PBRSSalesByProdFrm},
  PBRSSalesComm in '..\PBRSSalesComm.pas' {PBRSSalesCommFrm},
  PBRSSalesProfit in '..\PBRSSalesProfit.pas' {PBRSSalesProfitfrm},
  PBLUSInvDM in '..\PBLUSInvDM.pas' {dmLookUpSInv: TDataModule},
  PBRPProofStatus in '..\PBRPProofStatus.pas' {PBRPProofStatusfrm},
  PBRSProofStatus in '..\PBRSProofStatus.pas' {PBRSProofStatusFrm},
  PBSupplierInvoiceDm in '..\PBSupplierInvoiceDm.pas' {dmSupplierInvoice: TDataModule},
  PBMaintSuppInvoice in '..\PBMaintSuppInvoice.pas' {PBMaintSuppInvoicefrm},
  PBMaintSuppInvoicePass in '..\PBMaintSuppInvoicePass.pas' {PBMaintSuppInvoicePassFrm},
  PBMaintSuppInvoiceChgs in '..\PBMaintSuppInvoiceChgs.pas' {PBMaintSuppInvoiceChgsfrm},
  PBMaintSuppInvoiceLine in '..\PBMaintSuppInvoiceLine.pas' {PBMaintSuppInvoiceLinefrm},
  PBLUSupplierInvoicePurch in '..\PBLUSupplierInvoicePurch.pas' {PBLUSupplierInvoicePurchFrm},
  PBLUSupplierInvoiceCN in '..\PBLUSupplierInvoiceCN.pas' {PBLUSupplierInvoiceCNFrm},
  PBLUSupplierInvoiceJB in '..\PBLUSupplierInvoiceJB.pas' {PBLUSupplierInvoiceJBFrm},
  PBLUSupplierInvoicePO in '..\PBLUSupplierInvoicePO.pas' {PBLUSupplierInvoicePOFrm},
  pbLUPurchaseOrders in '..\pbLUPurchaseOrders.pas' {frmPBLUPurchaseOrders},
  pbPOrdersDM in '..\pbPOrdersDM.pas' {dtmdlPOrders: TDataModule},
  STMntPOrd in '..\STMntPOrd.pas' {STMntPOrdFrm},
  STPOObjects in '..\STPOObjects.pas',
  STPODataMod in '..\STPODataMod.pas' {STPODM: TDataModule},
  STMntPOrdAdd in '..\STMntPOrdAdd.pas' {STMntPOrdAddFrm},
  STMntPOrdQty in '..\STMntPOrdQty.pas' {STMntPOrdQtyFrm},
  STMaintPOExtChg in '..\STMaintPOExtChg.pas' {STMaintPOExtChgFrm},
  STPordRSl in '..\STPordRSl.pas' {STPordRSlFrm},
  STPOrdRep in '..\Quick Reports\Nexus\STPOrdRep.pas' {STPOrdRepFrm},
  STPODirectConf in '..\STPODirectConf.pas' {STPODirectConfFrm},
  STMaintParam in '..\STMaintParam.pas' {STMaintParamFrm},
  STLUFormRef in '..\STLUFormRef.pas' {frmSTLUFormRef},
  STMaintFormRef in '..\STMaintFormRef.pas' {frmSTMaintFormRef},
  pbLUCustOrdersJB in '..\pbLUCustOrdersJB.pas' {frmpbluCustOrdersJB},
  pbluCustEvents in '..\pbluCustEvents.pas' {frmPBLUCustEvents},
  pbEventsDM in '..\pbEventsDM.pas' {dtmdlEvents: TDataModule},
  PBMaintCContaEvents in '..\PBMaintCContaEvents.pas' {PBMaintCContaEventsFrm},
  PBMaintContactEvents in '..\PBMaintContactEvents.pas' {frmPBMaintContactEvents},
  PBLUReps in '..\PBLUReps.pas' {frmPBLUReps},
  pbLUCustomerRpts in '..\pbLUCustomerRpts.pas' {frmPBLUCustomerRpts},
  PBRSCustContDet in '..\PBRSCustContDet.pas' {PBRSCustContDetFrm},
  PBRSCustDet in '..\PBRSCustDet.pas' {PBRSCustDetFrm},
  PBRPCustContDet in '..\PBRPCustContDet.pas' {PBRPCustContDetFrm},
  PBRPCustDet in '..\PBRPCustDet.pas' {PBRPCustDetFrm},
  CCSCommon in '..\..\CCSCOMMOND7\CCSCommon.pas',
  taoMAPI in '..\..\CCSCOMMOND7\taoMAPI.pas',
  PBRPLabelsReels in '..\Quick Reports\Nexus\PBRPLabelsReels.pas' {PBRPLabelsReelsFrm},
  CCSMaintProdImages in '..\..\CCSCOMMOND7\CCSMaintProdImages.pas' {CCSMaintProdImagesFrm},
  CCSProgressBar in '..\..\CCSCOMMOND7\CCSProgressBar.pas' {frmCCSProgressBar},
  STRPStockLabels in '..\Quick Reports\Nexus\STRPStockLabels.pas' {STRPStockLabelsFrm},
  PBRPJobBag in '..\Quick Reports\Nexus\PBRPJobBag.pas' {frmPBRPJobBag},
  PBRPJobBagSched in '..\Quick Reports\Nexus\PBRPJobBagSched.pas' {frmPBRPJobBagSched},
  PBMaintWorkCentre in '..\PBMaintWorkCentre.pas' {PBMaintWorkCentreFrm},
  PBLUWorkCentre in '..\PBLUWorkCentre.pas' {PBLUWorkCentrefrm},
  PBRPLabels in '..\Quick Reports\Nexus\PBRPLabels.pas' {PBRPLabelsFrm},
  PBMaintProofStatus in '..\PBMaintProofStatus.pas' {PBMaintProofStatusFrm},
  PBLUProofStatus in '..\PBLUProofStatus.pas' {PBLUProofStatusFrm},
  STRPPickingNote in '..\Quick Reports\Nexus\STRPPickingNote.pas' {STRPPickingNoteFrm},
  PBMaintJobBag in '..\PBMaintJobBag.pas' {PBMaintJobBagFrm},
  PBLUCustomerCats in '..\PBLUCustomerCats.pas' {PBLUCustomerCatsFrm},
  PBMaintCustomerCats in '..\PBMaintCustomerCats.pas' {PBMaintCustomerCatsFrm},
  PBLUCategory in '..\PBLUCategory.pas' {PBLUCategoryFrm},
  PBLUCustProductTemp in '..\PBLUCustProductTemp.pas' {PBLUCustProductTempFrm},
  PBRSCustCatKPI in '..\PBRSCustCatKPI.pas' {PBRSCustCatKPIfrm},
  PBRSSalesByPrdCat in '..\PBRSSalesByPrdCat.pas' {PBRSSalesByPrdCatFrm},
  PBRPCustCatKPI in '..\PBRPCustCatKPI.pas' {PBRPCustCatKPIFrm},
  PBRPCustState in '..\Quick Reports\Nexus\PBRPCustState.pas' {PBRPCustStateFrm},
  PBRSPurchByInv in '..\PBRSPurchByInv.pas' {PBRSPurchByInvFrm},
  PBMaintQuote in '..\PBMaintQuote.pas' {PBMaintQuoteFrm},
  PBWOrdersDm in '..\PBWOrdersDm.pas' {dtmdlWOrders: TDataModule},
  PBMaintProcess in '..\PBMaintProcess.pas' {PBMaintProcessFrm},
  PBLUProcess in '..\PBLUProcess.pas' {PBLUProcessFrm},
  PBMaintWorksOrders in '..\PBMaintWorksOrders.pas' {frmPBMaintWorksOrders},
  SFJobBagLogDM in '..\..\SFDC\SFJobBagLogDM.pas' {dtmdlJobBagLog: TDataModule},
  PBRPQuote in '..\Quick Reports\Nexus\PBRPQuote.pas' {frmPBRPQuote},
  PBRSFSCClaim in '..\PBRSFSCClaim.pas' {PBRSFSCClaimFrm},
  STRPProductList in '..\STRPProductList.pas' {STRPProductListFrm},
  STLUCustPart in '..\STLUCustPart.pas' {STLUCustPartFrm},
  STMaintCustPart in '..\STMaintCustPart.pas' {STMaintCustPartFrm},
  pbluNCASearch in '..\pbluNCASearch.pas' {frmpbluNCASearch},
  pbLuNCA in '..\pbLuNCA.pas' {frmPBluNCA},
  PBLUNCARpts in '..\PBLUNCARpts.pas' {frmPBLUNCARpts},
  PBRPSalesInv in '..\Quick Reports\Nexus\PBRPSalesInv.pas' {PBRPSalesInvFrm},
  STRSProductList in '..\STRSProductList.pas' {STRSProductListFrm},
  PBRSJBDraft in '..\PBRSJBDraft.pas' {PBRSJBDraftFrm},
  PBRPJBDraft in '..\PBRPJBDraft.pas' {PBRPJBDraftFrm},
  PBRSCustInvoice in '..\PBRSCustInvoice.pas' {PBRSCustInvoiceFrm},
  PBMaintSalesInvoiceDetail in '..\PBMaintSalesInvoiceDetail.pas' {PBMaintSalesInvoiceDetailFrm},
  STRPSord in '..\Quick Reports\Nexus\STRPSord.pas' {STRPSordFrm},
  PBRPNonConform in '..\Quick Reports\Nexus\PBRPNonConform.pas' {frmPBRPNonConform},
  PBRSNonConform in '..\PBRSNonConform.pas' {frmPBRSNonConform},
  PBRSNCAClient in '..\PBRSNCAClient.pas' {PBRSNCAClientfrm},
  PBRSNCACostGraph in '..\PBRSNCACostGraph.pas' {PBRSNCACostGraphFrm},
  PBRSNCAReason in '..\PBRSNCAReason.pas' {PBRSNCAReasonFrm},
  PBRSNCASource in '..\PBRSNCASource.pas' {PBRSNCASourceFrm},
  PBRSNCASourcePie in '..\PBRSNCASourcePie.pas' {PBRSNCASourcePieFrm},
  PBMaintNonConfDoc in '..\PBMaintNonConfDoc.pas' {PBMaintNonConfDocFrm},
  PBMaintPOrdNonConfDoc in '..\PBMaintPOrdNonConfDoc.pas' {PBMaintPOrdNonConfDocFrm},
  STRSPODelivNote in '..\STRSPODelivNote.pas' {STRSPODelivNoteFrm},
  STRPPODelivNote in '..\STRPPODelivNote.pas' {STRPPODelivNoteFrm},
  Outlook12_TLB in '..\..\CCSCommonD7\Outlook12_TLB.pas',
  Office12_TLB in '..\..\CCSCommonD7\Office12_TLB.pas',
  Printer.Enums in '..\..\..\PrinterTools\Printer.Enums.pas',
  Printer.Interfaces in '..\..\..\PrinterTools\Printer.Interfaces.pas',
  Printer.Tools in '..\..\..\PrinterTools\Printer.Tools.pas';

{$R *.RES}

begin
  {$IFDEF DEBUG}
  ReportMemoryLeaksOnShutdown := True;
  {$ENDIF}
  Application.Initialize;
  Application.Title := 'Redeye Management Information';
  Application.CreateForm(TdmBroker, dmBroker);
  Application.CreateForm(TfrmpbMainMenu, frmpbMainMenu);
  Application.CreateForm(TPBSendFaxFrm, PBSendFaxFrm);
  Application.CreateForm(TPBImagesFrm, PBImagesFrm);
  Application.CreateForm(TdmLetter, dmLetter);
  Application.CreateForm(TPBAuditDataMod, PBAuditDataMod);
  Application.Run;
end.
