program redeye_PrintGuy;

uses
  Forms,
  pbMainMenu in '..\pbMainMenu.pas' {frmpbMainMenu},
  pbluCustomers in '..\pbluCustomers.pas' {frmpbluCustomers},
  pbluSuppliers in '..\pbluSuppliers.pas' {frmpbluSuppliers},
  pbDatabase in '..\pbDatabase.pas' {dmBroker: TDataModule},
  pbLogin in '..\pbLogin.pas' {frmpbLogin},
  pbEnvSel in '..\pbEnvSel.pas' {frmpbEnvSel},
  pbCustomerDm in '..\pbCustomerDm.pas' {dtmdlCustomers: TDataModule},
  pbluCustOrders in '..\pbluCustOrders.pas' {frmpbluCustOrders},
  pbOrdersDm in '..\pbOrdersDm.pas' {dtmdlOrders: TDataModule},
  pbSupplierDm in '..\pbSupplierDm.pas' {dtmdlSuppliers: TDataModule},
  pbluOrdersSearch in '..\pbluOrdersSearch.pas' {frmpbluOrdersSearch},
  PBMaintCust in '..\PBMaintCust.pas' {PBMaintCustFrm},
  CCSPrint in '..\..\CCSCommonD7\CCSPrint.pas',
  pbluCustBrSelect in '..\pbluCustBrSelect.pas' {frmpbluCustBrSelect},
  PBImages in '..\PBImages.pas' {PBImagesFrm},
  PBDBMemo in '..\PBDBMemo.pas' {PBDBMemoFrm},
  PBDelivNotes in '..\PBDelivNotes.pas' {PBDelivNotesFrm},
  PBMaintCompany in '..\PBMaintCompany.pas' {PBMaintCompanyFrm},
  pbluSupplierSelect in '..\pbluSupplierSelect.pas' {frmpbluSupplierSelect},
  PBLUPrdTyp in '..\PBLUPrdTyp.pas' {PBLUPrdTypFrm},
  PBMaintRep in '..\PBMaintRep.pas' {PBMaintRepFrm},
  PBLURep in '..\PBLURep.pas' {PBLURepFrm},
  PBLUAdHoc in '..\PBLUAdHoc.pas' {PBLUAdHocFrm},
  PBLUCust in '..\PBLUCust.pas' {PBLUCustFrm},
  PBLUPrdTypCap in '..\PBLUPrdTypCap.pas' {PBLUPrdTypCapFrm},
  PBLUPrdTypOChg in '..\PBLUPrdTypOChg.pas' {PBLUPrdTypOChgFrm},
  PBLUPrdTypQu in '..\PBLUPrdTypQu.pas' {PBLUPrdTypQuFrm},
  PBLUPrdTypQuList in '..\PBLUPrdTypQuList.pas' {PBLUPrdTypQuListfrm},
  PBLURepNom in '..\PBLURepNom.pas' {PBLURepNomFrm},
  PBLUSConta in '..\PBLUSConta.pas' {PBLUSContaFrm},
  PBLUSupBrch in '..\PBLUSupBrch.pas' {PBLUSupBrchFrm},
  PBLUSupp in '..\PBLUSupp.pas' {PBLUSuppFrm},
  PBMaintAdHoc in '..\PBMaintAdHoc.pas' {PBMaintAdHocFrm},
  PBMaintGroups in '..\PBMaintGroups.pas' {PBMaintGroupsFrm},
  PBMaintGroupsDets in '..\PBMaintGroupsDets.pas' {PBMaintGroupsDetsFrm},
  PBMaintPrdTyp in '..\PBMaintPrdTyp.pas' {PBMaintPrdTypFrm},
  PBMaintPrdTypCap in '..\PBMaintPrdTypCap.pas' {PBMaintPrdTypCapFrm},
  PBMaintPrdTypOChg in '..\PBMaintPrdTypOChg.pas' {PBMaintPrdTypOChgFrm},
  PBMaintPrdTypQu in '..\PBMaintPrdTypQu.pas' {PBMaintPrdTypQuFrm},
  PBMaintRepNom in '..\PBMaintRepNom.pas' {PBMaintRepNomFrm},
  PBMaintSConta in '..\PBMaintSConta.pas' {PBMaintSContaFrm},
  PBMaintSupBrch in '..\PBMaintSupBrch.pas' {PBMaintSupBrchFrm},
  PBMaintSupp in '..\PBMaintSupp.pas' {PBMaintSuppFrm},
  PBMaintSuppCap in '..\PBMaintSuppCap.pas' {PBMaintSuppCapFrm},
  PBMaintSpecIns in '..\PBMaintSpecIns.pas' {PBMaintSpecInsFrm},
  PBLUSpecIns in '..\PBLUSpecIns.pas' {PBLUSpecInsFrm},
  PBLUAddCharges in '..\PBLUAddCharges.pas' {PBLUAddChrgFrm},
  PBLUPriceUnit in '..\PBLUPriceUnit.pas' {PBLUPriceUnitFrm},
  PBMaintAddChrgs in '..\PBMaintAddChrgs.pas' {PBMaintAddChrgsFrm},
  PBMaintPriceUnit in '..\PBMaintPriceUnit.pas' {PBMaintPriceUnitFrm},
  CCSCommon in '..\..\CCSCommonD7\CCSCommon.pas',
  PBLUStandSize in '..\PBLUStandSize.pas' {PBLUStandSizeFrm},
  PBMaintPaper in '..\PBMaintPaper.pas' {PBMaintPaperFrm},
  PBMaintStandSize in '..\PBMaintStandSize.pas' {PBMaintStandSizeFrm},
  PBLUArtwrkTyp in '..\PBLUArtwrkTyp.pas' {PBLUArtwrkTypFrm},
  PBMaintArtwrkTyp in '..\PBMaintArtwrkTyp.pas' {PBMaintArtwrkTypFrm},
  PBMaintOpsDet in '..\PBMaintOpsDet.pas' {PBMaintOpsDetFrm},
  PBLUOps in '..\PBLUOps.pas' {PBLUOpsFrm},
  PBAuditControl in '..\PBAuditControl.pas' {PBAuditControlFrm},
  PBMaintInterf in '..\PBMaintInterf.pas' {PBMaintInterfFrm},
  PBMaintLastNos in '..\PBMaintLastNos.pas' {PBMaintLastNosFrm},
  PBMaintOpsDetPass in '..\PBMaintOpsDetPass.pas' {PBMaintOpsDetPassFrm},
  PBMaintVATCode in '..\PBMaintVATCode.pas' {PBMaintVATCodeFrm},
  PBAuditDM in '..\PBAuditDM.pas' {PBAuditDataMod: TDataModule},
  PBLUBranch in '..\PBLUBranch.pas' {PBLUBranchFrm},
  PBLUCConta in '..\PBLUCConta.pas' {PBLUCContaFrm},
  PBLUCContaEvents in '..\PBLUCContaEvents.pas' {PBLUCContaEventsFrm},
  PBLUCRep in '..\PBLUCRep.pas' {PBLUCRepFrm},
  PBLUFormRef in '..\PBLUFormRef.pas' {PBLUFormRefFrm},
  PBMaintBranch in '..\PBMaintBranch.pas' {PBMaintBranchFrm},
  PBMaintCConta in '..\PBMaintCConta.pas' {PBMaintCContaFrm},
  PBMaintContApp in '..\PBMaintContApp.pas' {PBMaintContAppfrm},
  PBMaintFormRef in '..\PBMaintFormRef.pas' {PBMaintFormRefFrm},
  PBMaintPOrd in '..\PBMaintPOrd.pas' {PBMaintPOrdFrm},
  PBIntSelDM in '..\PBIntSelDM.pas' {dmIntSel: TDataModule},
  PBPOObjects in '..\PBPOObjects.pas',
  PBPODataMod in '..\PBPODataMod.pas' {PBPODM: TDataModule},
  DateSelV5 in '..\DateSelV5.pas' {DateSelV5Form},
  PBJobBagDM in '..\PBJobBagDM.pas' {dmJobBag: TDataModule},
  PBMaintPOrdLine in '..\PBMaintPOrdLine.pas' {PBMaintPOrdLineFrm},
  PBMaintPOrdLineDeliv in '..\PBMaintPOrdLineDeliv.pas' {PBMaintPOrdLineDelivFrm},
  PBMaintPOrdLineExtChg in '..\PBMaintPOrdLineExtChg.pas' {PBMaintPOrdLineExtChgFrm},
  PBLUProofHistN in '..\PBLUProofHistN.pas' {PBLUProofHistNFrm},
  PBPOAddDtls in '..\PBPOAddDtls.pas' {PBPOAddDtlsFrm},
  PBMaintPOAddNotes in '..\PBMaintPOAddNotes.pas' {PBMaintPOAddNotesFrm},
  PBPartDescDg in '..\PBPartDescDg.pas' {PBPartDescDlg},
  PBMaintPOrdLInactive in '..\PBMaintPOrdLInactive.pas' {PBMaintPOrdLInactiveFrm},
  PBLUReasCode in '..\PBLUReasCode.pas' {PBLUReasCodeFrm},
  PBMaintReasCode in '..\PBMaintReasCode.pas' {PBMaintReasCodeFrm},
  PBMaintPOrdLineCallOff in '..\PBMaintPOrdLineCallOff.pas' {PBMaintPOrdLineCallOffFrm},
  PBLUCustFormRef in '..\PBLUCustFormRef.pas' {PBLUCustFormRefFrm},
  PBMaintPOrdLView in '..\PBMaintPOrdLView.pas' {PBMaintPOrdLViewFrm},
  PBMaintIntNote in '..\PBMaintIntNote.pas' {PBMaintIntNoteFrm},
  PBRSPOrdN in '..\PBRSPOrdN.pas' {PBRSPOrdNFrm},
  CCSDataBroker in '..\..\CCSCommonD7\CCSDataBroker.pas' {DataBroker: TDataModule},
  LetterDM in '..\..\PAGEDESIGNER\LetterDM.pas' {dmLetter: TDataModule},
  PDLetter in '..\..\PAGEDESIGNER\PDLetter.pas',
  CCSPress in '..\..\CCSCommonD7\CCSPress.pas' {frmPrintingPress},
  CCSDevil in '..\..\CCSCommonD7\CCSDevil.pas',
  Compositor in '..\..\CCSCommonD7\Compositor.pas' {Compositor},
  PBDBPOrdLtr in '..\PBDBPOrdLtr.pas' {dbPOrdLtr: TDataModule},
  PBFaxList in '..\PBFaxList.pas' {PBFaxListFrm},
  PBEmailList in '..\PBEmailList.pas' {PBEmailListFrm},
  PBSendFax in '..\PBSendFax.pas' {PBSendFaxFrm},
  pbluCustStock in '..\pbluCustStock.pas' {frmpbluCustStock},
  pbStockDm in '..\pbStockDm.pas' {dtmdlStock: TDataModule},
  pbLuBranches in '..\pbLuBranches.pas' {frmpbluBranches},
  pbluCustEnquiries in '..\pbluCustEnquiries.pas' {frmpbluCustEnquiries},
  pbEnqsdm in '..\pbEnqsdm.pas' {dtmdlEnqs: TDataModule},
  pbluContacts in '..\pbluContacts.pas' {frmpbluContacts},
  pbluEnqsSearch in '..\pbluEnqsSearch.pas' {frmpbluEnqsSearch},
  STLUStkMvmnts in '..\STLUStkMvmnts.pas' {STLUStkMvmntsFrm},
  STLUStkLoc in '..\STLUStkLoc.pas' {STLUStkLocFrm},
  STLUStkBinLots in '..\STLUStkBinLots.pas' {STLUStkBinLotsFrm},
  STLUStkSales in '..\STLUStkSales.pas' {STLUStkSalesFrm},
  STLUStkProduction in '..\STLUStkProduction.pas' {STLUStkProductionFrm},
  STLUStkPurchases in '..\STLUStkPurchases.pas' {STLUStkPurchasesFrm},
  PBenquiry in '..\PBenquiry.pas' {PBEnquiryFrm},
  STSOObjects in '..\STSOObjects.pas',
  PBenqline in '..\PBenqline.pas' {PBEnqLineTmp},
  PBEnqLineDtls in '..\PBEnqLineDtls.pas' {PBEnqLineDtlsFrm},
  PBEnqAddDtls in '..\PBEnqAddDtls.pas' {PBEnqAddDtlsFrm},
  PBEnqDataMod in '..\PBEnqDataMod.pas' {PBEnqDataModFrm: TDataModule},
  PBPOToEnq in '..\PBPOToEnq.pas' {PBPOToEnqFrm},
  PBEnqSelSup in '..\PBEnqSelSup.pas' {PBEnqSelSupFrm},
  PBRSEnqN in '..\PBRSEnqN.pas' {PBRSEnqNFrm},
  PBDBEnqLtr in '..\PBDBEnqLtr.pas' {dbEnqLtr: TDataModule},
  PBEnqSuppDataMod in '..\PBEnqSuppDataMod.pas' {PBEnqSuppDataModFrm: TDataModule},
  PBEnqSupTmp in '..\PBEnqSupTmp.pas' {PBEnqSupTmpFrm},
  PBLUEnqAddChg in '..\PBLUEnqAddChg.pas' {PBLUEnqAddChgFrm},
  PBEnqRespQty in '..\PBEnqRespQty.pas' {PBEnqRespQtyFrm},
  PBEnqJobPrice in '..\PBEnqJobPrice.pas' {PBEnqJobPriceFrm},
  PBEnqJobDtls in '..\PBEnqJobDtls.pas' {PBEnqJobDtlsFrm},
  PBEnqAddChg in '..\PBEnqAddChg.pas' {PBEnqAddChgFrm},
  PBDBQuoLtr in '..\PBDBQuoLtr.pas' {dbQuoLtr: TDataModule},
  PBDBQuoSumLtr in '..\PBDBQuoSumLtr.pas' {dbQuoSumLtr: TDataModule},
  PBRSQuoN in '..\PBRSQuoN.pas' {PBRSQuoNFrm},
  STSODataMod in '..\STSODataMod.pas' {STSalesOrdDM: TDataModule},
  STMaintSOrdLineServ in '..\STMaintSOrdLineServ.pas' {STMaintSOrdLineServFrm},
  STPrtMnt in '..\STPrtMnt.pas' {STPrtMntFrm},
  STPrtMntDetsMulti in '..\STPrtMntDetsMulti.pas' {STPrtMntDetsMultiFrm},
  STPrtMntDets in '..\STPrtMntDets.pas' {STPrtMntDetsFrm},
  StMntPrtSupp in '..\StMntPrtSupp.pas' {STMntPrtSuppFrm},
  STLUPrtGrp in '..\STLUPrtGrp.pas' {STLUPrtGrpFrm},
  STMntPrtGrp in '..\STMntPrtGrp.pas' {STMntPrtGrpFrm},
  STProdImport in '..\STProdImport.pas' {STProdImportFrm},
  STMaintPrtEComm in '..\STMaintPrtEComm.pas' {STMaintPrtECommFrm},
  STMaintSOrdLine in '..\STMaintSOrdLine.pas' {STMaintSOrdLineFrm},
  STMaintSinvExtChg in '..\STMaintSinvExtChg.pas' {STMaintSInvExtChgFrm},
  STMaintSOrdSerialNos in '..\STMaintSOrdSerialNos.pas' {STMaintSOrdSerialNosFrm},
  PBNarrativeDM in '..\PBNarrativeDM.pas' {dmNarrative: TDataModule},
  pbluCustDeliv in '..\pbluCustDeliv.pas' {frmpbluOrderdeliv},
  STPrtAllocSales in '..\STPrtAllocSales.pas' {STPrtAllocSalesFrm},
  STStockDM in '..\STStockDM.pas' {STStockDataMod: TDataModule},
  STPrtAllocStStock in '..\STPrtAllocStStock.pas' {STPrtAllocStStockFrm},
  STRSPickNote in '..\STRSPickNote.pas' {STRSPickNotefrm},
  STPickObject in '..\STPickObject.pas',
  STPickingDM in '..\STPickingDM.pas' {STPickDM: TDataModule},
  STPickbyPart in '..\STPickbyPart.pas' {STPickbyPartFrm},
  STPickItem in '..\STPickItem.pas' {STPickItemFrm},
  STRSSalesOrd in '..\STRSSalesOrd.pas' {STRSSalesOrdfrm},
  PBRSDelivNote in '..\PBRSDelivNote.pas' {PBRSDelivNoteFrm},
  PBRSBoxLabels in '..\PBRSBoxLabels.pas' {PBRSBoxLabelsfrm},
  PBMaintDeliv in '..\PBMaintDeliv.pas' {PBMaintDelivFrm},
  pbStockMoveDm in '..\pbStockMoveDm.pas' {dtmdlStockMove: TDataModule},
  PBMaintDelivBin in '..\PBMaintDelivBin.pas' {PBMaintDelivBinfrm},
  PBMntPrtBinUpd in '..\PBMntPrtBinUpd.pas' {PBMntPrtBinUpdFrm},
  PBMntPrtBin in '..\PBMntPrtBin.pas' {PBMntPrtBinFrm},
  PBDelivStock in '..\PBDelivStock.pas' {PBDelivStockFrm},
  STRSBoxLabels in '..\STRSBoxLabels.pas' {STRSBoxLabelsfrm},
  pbluCustJobs in '..\pbluCustJobs.pas' {frmpbluCustJobs},
  pbJobsDm in '..\pbJobsDm.pas' {dtmdlJobs: TDataModule},
  pbluJobsSearch in '..\pbluJobsSearch.pas' {frmpbluJobsSearch},
  PBMaintJobBagDets in '..\PBMaintJobBagDets.pas' {PBMaintJobBagDetsFrm},
  PBMaintJobBagRC in '..\PBMaintJobBagRC.pas' {PBMaintJobBagRCFrm},
  PBMaintQEnq in '..\PBMaintQEnq.pas' {PBMaintQEnqFrm},
  PBEnquiryDataMod in '..\PBEnquiryDataMod.pas' {PBEnqDM: TDataModule},
  PBRSProofN in '..\PBRSProofN.pas' {PBRSProofNFrm},
  PBMaintProofHistN in '..\PBMaintProofHistN.pas' {PBMaintProofHistNFrm},
  PBAutoPODets in '..\PBAutoPODets.pas' {PBAutoPODetsFrm},
  PBAutoPO in '..\PBAutoPO.pas' {PBAutoPOFrm},
  PBAutoPODataMod in '..\PBAutoPODataMod.pas' {PBAutoPODM: TDataModule},
  STMaintProduct in '..\STMaintProduct.pas' {frmSTMaintProduct},
  STMaintProductLvls in '..\STMaintProductLvls.pas' {frmSTMaintProductLvls},
  STPrtTran in '..\STPrtTran.pas' {STPrtTranFrm},
  STPrtTransQty in '..\STPrtTransQty.pas' {STPrtTransQtyFrm},
  STLUBinPrt in '..\STLUBinPrt.pas' {STLUBinPrtFrm},
  STPrtTransRecv in '..\STPrtTransRecv.pas' {STPrtTransRecvFrm},
  STPrtTransSN in '..\STPrtTransSN.pas' {STPrtTransSNFrm},
  STLUStStkNumbers in '..\STLUStStkNumbers.pas' {STLUStStkNumbersFrm},
  STMaintStStkNumbers in '..\STMaintStStkNumbers.pas' {STMaintStStkNumbersfrm},
  PBRPProof in '..\Quick Reports\PrintGuy\PBRPProof.pas' {PBRPProofFrm},
  PBRPDeliv in '..\Quick Reports\PrintGuy\PBRPDeliv.pas' {PBRPDelivFrm},
  PBRPLabels in '..\Quick Reports\PrintGuy\PBRPLabels.pas' {PBRPLabelsFrm},
  STLUProductLvls in '..\STLUProductLvls.pas' {frmSTLUProductLvls},
  PBLUDeliveriesDM in '..\PBLUDeliveriesDM.pas' {dtmdlDeliveries: TDataModule},
  STRPDeliv in '..\Quick Reports\PrintGuy\STRPDeliv.pas' {STRPDelivfrm},
  STRPLabels in '..\Quick Reports\PrintGuy\STRPLabels.pas' {STRPLabelsFrm},
  STRPPick in '..\Quick Reports\PrintGuy\STRPPick.pas' {STRPPickfrm},
  STRSDelivNote in '..\STRSDelivNote.pas' {STRSDelivNotefrm},
  pbluOrders in '..\pbluOrders.pas' {frmpbLUOrders},
  pbluVatCode in '..\pbluVatCode.pas' {PBLUVATCodeFrm},
  STPrtMntLvls in '..\STPrtMntLvls.pas' {STPrtMntLvlsFrm},
  STLUSuppPrt in '..\STLUSuppPrt.pas' {STLUSuppPrtFrm},
  STRSLabels in '..\STRSLabels.pas' {STRSLabelsfrm},
  STRPBxLabels in '..\Quick Reports\PrintGuy\STRPBxLabels.pas' {STRPBxLabelsFrm},
  CCSMaintPrtImages in '..\..\CCSCommonD7\CCSMaintPrtImages.pas' {CCSMaintPrtImagesFrm},
  gifimage in '..\..\CCSCommonD7\gifimage.pas',
  CCSImageViewer in '..\..\CCSCommonD7\CCSImageViewer.pas' {CCSImageViewerFrm},
  STMntSOrd in '..\STMntSOrd.pas' {STMntSOrdFrm},
  STMntSOrdSpecIn in '..\STMntSOrdSpecIn.pas' {STMntSOrdSpecInFrm},
  pbLUEnquiries in '..\pbLUEnquiries.pas' {frmPBLuEnquiries},
  pbLuStock in '..\pbLuStock.pas' {frmPBLUStock},
  pbLuSalesOrders in '..\pbLuSalesOrders.pas' {frmPBLUSalesOrders},
  pbLuJobs in '..\pbLuJobs.pas' {frmPBLUJobs},
  pbLUSalesInvoices in '..\pbLUSalesInvoices.pas' {frmPBLUSalesInvoices},
  pbLUPurchaseInvoices in '..\pbLUPurchaseInvoices.pas' {frmPBLUPurchaseInvoices},
  PBSalesInvoiceDm in '..\PBSalesInvoiceDm.pas' {dmSalesInvoice: TDataModule},
  PBLUSalesInvoiceSO in '..\PBLUSalesInvoiceSO.pas' {PBLUSalesInvoiceSOfrm},
  PBLUSalesInvoiceCN in '..\PBLUSalesInvoiceCN.pas' {PBLUSalesInvoiceCNfrm},
  PBLUSalesInvoiceJB in '..\PBLUSalesInvoiceJB.pas' {PBLUSalesInvoiceJBfrm},
  PBLUSalesInvoiceJBL in '..\PBLUSalesInvoiceJBL.pas' {PBLUSalesInvoiceJBLfrm},
  PBLUSalesInvoicePO in '..\PBLUSalesInvoicePO.pas' {PBLUSalesInvoicePOfrm},
  PBMaintSalesInvoiceLine in '..\PBMaintSalesInvoiceLine.pas' {PBMaintSalesInvoiceLinefrm},
  PBMaintSalesInvoice in '..\PBMaintSalesInvoice.pas' {PBMaintSalesInvoicefrm},
  PBRPSalesInv in '..\Quick Reports\PrintGuy\PBRPSalesInv.pas' {PBRPSalesInvFrm},
  PBSalesInvRPrint in '..\PBSalesInvRPrint.pas' {PBSalesInvRPrintFrm},
  PBSalesInvPrint in '..\PBSalesInvPrint.pas' {PBSalesInvPrintFrm},
  PBMaintInvChgs in '..\PBMaintInvChgs.pas' {PBMaintInvChgsfrm},
  STMntStorTyp in '..\STMntStorTyp.pas' {STMntStorTypFrm},
  STLUStorTyp in '..\STLUStorTyp.pas' {STLUStorTypFrm},
  STMntPrtStor in '..\STMntPrtStor.pas' {STMntPrtStorFrm},
  STLUPrtStor in '..\STLUPrtStor.pas' {STLUPrtStorFrm},
  STMntPrtBinUpd in '..\STMntPrtBinUpd.pas' {STMntPrtBinUpdFrm},
  STMntPrtBin in '..\STMntPrtBin.pas' {STMntPrtBinFrm},
  pbLUStockRpts in '..\pbLUStockRpts.pas' {frmPBLUStockRpts},
  STRSStkBalRep in '..\STRSStkBalRep.pas' {STRSStkBalRepfrm},
  STRPStkBalRep2 in '..\STRPStkBalRep2.pas' {STRPStkBalRep2frm},
  STRPStkBalRep in '..\STRPStkBalRep.pas' {STRPStkBalRepfrm},
  STFaxList in '..\STFaxList.pas' {STFaxListFrm},
  STEmailList in '..\STEmailList.pas' {STEmailListFrm},
  StMovSl in '..\StMovSl.pas' {StMovSlfrm},
  StMovRep in '..\StMovRep.pas' {StMovRepFrm},
  STRSSlwMvngStkRep in '..\STRSSlwMvngStkRep.pas' {STRSSlwMvngStkRepfrm},
  STRPSlwMvngStkRep in '..\STRPSlwMvngStkRep.pas' {STRPSlwMvngStkRepfrm},
  STNegStkRep in '..\STNegStkRep.pas' {STNegStkRepFrm},
  STNegStksl in '..\STNegStksl.pas' {STNegStkSlfrm},
  STRSStkVal in '..\STRSStkVal.pas' {STRSStkValfrm},
  STStkValSl in '..\STStkValSl.pas' {STStkValSlfrm},
  STStkValRep in '..\STStkValRep.pas' {STStkValRepFrm},
  STStkVarRep in '..\STStkVarRep.pas' {STStkVarRepFrm},
  STRSAgedStk in '..\STRSAgedStk.pas' {STRSAgedStkFrm},
  STRPAgedStk in '..\STRPAgedStk.pas' {STRPAgedStkFrm},
  STRPSalesByCust in '..\STRPSalesByCust.pas' {STRPSalesByCustFrm},
  STRSSalesByCust in '..\STRSSalesByCust.pas' {STRSSalesByCustFrm},
  STLUSordDM in '..\STLUSordDM.pas' {DmLookupSOrd: TDataModule},
  STRPSOHistory in '..\STRPSOHistory.pas' {STRPSOHistoryFrm},
  STRSSOHistory in '..\STRSSOHistory.pas' {STRSSOHistoryFrm},
  STLUPrtByCustOrder in '..\STLUPrtByCustOrder.pas' {STLUPrtByCustOrderFrm},
  STRPWorkIP in '..\STRPWorkIP.pas' {STRPWorkIPfrm},
  STRSWorkIP in '..\STRSWorkIP.pas' {STRSWorkIPfrm},
  STPartSuppSel in '..\STPartSuppSel.pas' {STPartSuppSelFrm},
  STRPCustProdUsage in '..\STRPCustProdUsage.pas' {STRPCustProdUsagefrm},
  STRPCustStkBal in '..\STRPCustStkBal.pas' {STRPCustStkBalfrm},
  STRSCustProdUsage in '..\STRSCustProdUsage.pas' {STRSCustProdUsageFrm},
  STRSCustStkBal in '..\STRSCustStkBal.pas' {STRSCustStkBalfrm},
  STPartSuppRep in '..\STPartSuppRep.pas' {STPartSuppRepFrm},
  STPartSuppDM in '..\STPartSuppDM.pas' {STPartSDM: TDataModule},
  CCSemailHandler in '..\..\CCSCommonD7\CCSemailHandler.pas' {emailHandler: TDataModule},
  CCSEmailList in '..\..\CCSCommonD7\CCSEmailList.pas' {CCSEmailListFrm},
  STRSBoxLabelsDeliv in '..\STRSBoxLabelsDeliv.pas' {STRSBoxLabelsDelivFrm},
  STRPLabelsDeliv in '..\Quick Reports\PrintGuy\STRPLabelsDeliv.pas' {STRPLabelsdelivFrm},
  pbLUOrderRpts in '..\pbLUOrderRpts.pas' {frmPBLUOrderRpts},
  PBFaxToOne in '..\PBFaxToOne.pas' {PBFaxToOneFrm},
  PBEmailToOne in '..\PBEmailToOne.pas' {PBEmailToOneFrm},
  PBRSEnqSel in '..\PBRSEnqSel.pas' {PBRSEnqSelFrm},
  PBRPEnqLst in '..\PBRPEnqLst.pas' {PBRPEnqLstFrm},
  PBEnqNote in '..\PBEnqNote.pas' {PBEnqNoteFrm},
  PBEnqQuantities in '..\PBEnqQuantities.pas' {PBEnqQuantitiesFrm},
  PBEnqSuppRespns in '..\PBEnqSuppRespns.pas' {PBEnqSuppRespnsFrm},
  PBEnqSupResp in '..\PBEnqSupResp.pas' {PBEnqSupRespFrm},
  pbLUJobRpts in '..\pbLUJobRpts.pas' {frmPBLUJobRpts},
  PBRDPORep in '..\PBRDPORep.pas' {PBRDPORepDataMod: TDataModule},
  PBRSWorkIP in '..\PBRSWorkIP.pas' {PBRSWorkIPfrm},
  PBRP4CastSumm in '..\PBRP4CastSumm.pas' {PBRP4CastSummFrm},
  PBRS4CastInvs in '..\PBRS4CastInvs.pas' {PBRS4CastInvsFrm},
  PBRS4CastSumm in '..\PBRS4CastSumm.pas' {PBRS4CastSummfrm},
  PBRP4CastInvs in '..\PBRP4CastInvs.pas' {PBRP4CastInvsFrm},
  PBRSRptOrds in '..\PBRSRptOrds.pas' {PBRSRptOrdsFrm},
  PBRPRptOrds in '..\PBRPRptOrds.pas' {PBRPRptOrdsFrm},
  PBRPWorkIP in '..\PBRPWorkIP.pas' {PBRPWorkIPfrm},
  PBRSJBMargin in '..\PBRSJBMargin.pas' {PBRSJBMarginfrm},
  PBRSODueEnq in '..\PBRSODueEnq.pas' {PBRSODueEnqFrm},
  PBRSODueQte in '..\PBRSODueQte.pas' {PBRSODueQteFrm},
  PBRSPODue in '..\PBRSPODue.pas' {PBRSPODueFrm},
  PBRSPORepM in '..\PBRSPORepM.pas' {PBRSPORepMFrm},
  PBRSPOREP in '..\PBRSPOREP.pas' {PBRSPORepFrm},
  PBRPPOnotonJB in '..\PBRPPOnotonJB.pas' {PBRPPOnotonJBfrm},
  PBRSPOnotonJB in '..\PBRSPOnotonJB.pas' {PBRSPOnotonJBfrm},
  pbLUSalesInvRpts in '..\pbLUSalesInvRpts.pas' {frmPBLUSalesInvRpts},
  PBRPJBMargin in '..\PBRPJBMargin.pas' {PBRPJBMarginFrm},
  PBRPODueEnq in '..\PBRPODueEnq.pas' {PBRPODueEnqFrm},
  PBRPODueQte in '..\PBRPODueQte.pas' {PBRPODueQteFrm},
  PBRPPODue in '..\PBRPPODue.pas' {PBRPPODueFrm},
  PBRPPORep in '..\PBRPPORep.pas' {PBRPPORepFrm},
  PBRPPORepM in '..\PBRPPORepM.pas' {PBRPPORepMFrm},
  PBRPRepProfitSumm in '..\PBRPRepProfitSumm.pas' {PBRPRepProfitSummFrm},
  PBRPSalesByInv in '..\PBRPSalesByInv.pas' {PBRPSalesByInvFrm},
  PBRPSalesByInvDet in '..\PBRPSalesByInvDet.pas' {PBRPSalesByInvDetFrm},
  PBRPSalesbyProd in '..\PBRPSalesbyProd.pas' {PBRPSalesbyProdFrm},
  PBRPSalesComm in '..\PBRPSalesComm.pas' {PBRPSalesCommFrm},
  PBRPSalesCommbyCat in '..\PBRPSalesCommbyCat.pas' {PBRPSalesCommbyCatFrm},
  PBRPSalesProfit in '..\PBRPSalesProfit.pas' {PBRPSalesProfitFrm},
  PBRPSalesProfitSumm in '..\PBRPSalesProfitSumm.pas' {PBRPSalesProfitSummFrm},
  PBRSCustState in '..\PBRSCustState.pas' {PBRSCustStateFrm},
  PBRSCustTurn in '..\PBRSCustTurn.pas' {PBRSCustTurnFrm},
  PBRSSalesByInv in '..\PBRSSalesByInv.pas' {PBRSSalesByInvFrm},
  PBRSSalesByProd in '..\PBRSSalesByProd.pas' {PBRSSalesByProdFrm},
  PBRSSalesComm in '..\PBRSSalesComm.pas' {PBRSSalesCommFrm},
  PBRSSalesProfit in '..\PBRSSalesProfit.pas' {PBRSSalesProfitfrm},
  PBRPCustState in '..\Quick Reports\PrintGuy\PBRPCustState.pas' {PBRPCustStateFrm},
  PBLUSInvDM in '..\PBLUSInvDM.pas' {dmLookUpSInv: TDataModule},
  PBRPProofStatus in '..\PBRPProofStatus.pas' {PBRPProofStatusfrm},
  PBRSProofStatus in '..\PBRSProofStatus.pas' {PBRSProofStatusFrm},
  PBSupplierInvoiceDm in '..\PBSupplierInvoiceDm.pas' {dmSupplierInvoice: TDataModule},
  PBMaintSuppInvoice in '..\PBMaintSuppInvoice.pas' {PBMaintSuppInvoicefrm},
  PBMaintSuppInvoicePass in '..\PBMaintSuppInvoicePass.pas' {PBMaintSuppInvoicePassFrm},
  PBMaintSuppInvoiceChgs in '..\PBMaintSuppInvoiceChgs.pas' {PBMaintSuppInvoiceChgsfrm},
  PBMaintSuppInvoiceLine in '..\PBMaintSuppInvoiceLine.pas' {PBMaintSuppInvoiceLinefrm},
  PBLUSupplierInvoicePurch in '..\PBLUSupplierInvoicePurch.pas' {PBLUSupplierInvoicePurchFrm},
  PBLUSupplierInvoiceCN in '..\PBLUSupplierInvoiceCN.pas' {PBLUSupplierInvoiceCNFrm},
  PBLUSupplierInvoiceJB in '..\PBLUSupplierInvoiceJB.pas' {PBLUSupplierInvoiceJBFrm},
  PBLUSupplierInvoicePO in '..\PBLUSupplierInvoicePO.pas' {PBLUSupplierInvoicePOFrm},
  pbLUPurchaseOrders in '..\pbLUPurchaseOrders.pas' {frmPBLUPurchaseOrders},
  pbPOrdersDM in '..\pbPOrdersDM.pas' {dtmdlPOrders: TDataModule},
  STMntPOrd in '..\STMntPOrd.pas' {STMntPOrdFrm},
  STPOObjects in '..\STPOObjects.pas',
  STPODataMod in '..\STPODataMod.pas' {STPODM: TDataModule},
  STMntPOrdAdd in '..\STMntPOrdAdd.pas' {STMntPOrdAddFrm},
  STMntPOrdQty in '..\STMntPOrdQty.pas' {STMntPOrdQtyFrm},
  STMaintPOExtChg in '..\STMaintPOExtChg.pas' {STMaintPOExtChgFrm},
  STPordRSl in '..\STPordRSl.pas' {STPordRSlFrm},
  STPOrdRep in '..\Quick Reports\PrintGuy\STPOrdRep.pas' {STPOrdRepFrm},
  STPODirectConf in '..\STPODirectConf.pas' {STPODirectConfFrm},
  STMaintParam in '..\STMaintParam.pas' {STMaintParamFrm},
  STLUFormRef in '..\STLUFormRef.pas' {frmSTLUFormRef},
  STMaintFormRef in '..\STMaintFormRef.pas' {frmSTMaintFormRef},
  pbLUCustOrdersJB in '..\pbLUCustOrdersJB.pas' {frmpbluCustOrdersJB},
  pbluCustEvents in '..\pbluCustEvents.pas' {frmPBLUCustEvents},
  pbEventsDM in '..\pbEventsDM.pas' {dtmdlEvents: TDataModule},
  PBMaintCContaEvents in '..\PBMaintCContaEvents.pas' {PBMaintCContaEventsFrm},
  PBMaintContactEvents in '..\PBMaintContactEvents.pas' {frmPBMaintContactEvents},
  PBLUReps in '..\PBLUReps.pas' {frmPBLUReps},
  pbLUCustomerRpts in '..\pbLUCustomerRpts.pas' {frmPBLUCustomerRpts},
  PBRSCustContDet in '..\PBRSCustContDet.pas' {PBRSCustContDetFrm},
  PBRSCustDet in '..\PBRSCustDet.pas' {PBRSCustDetFrm},
  PBRPCustContDet in '..\PBRPCustContDet.pas' {PBRPCustContDetFrm},
  PBRPCustDet in '..\PBRPCustDet.pas' {PBRPCustDetFrm},
  pbLUSalesCredits in '..\pbLUSalesCredits.pas' {frmPBLUSalesCredits},
  pbLUPurchaseCredits in '..\pbLUPurchaseCredits.pas' {frmPBLUPurchaseCredits},
  pbluCustSalesInvoices in '..\pbluCustSalesInvoices.pas' {frmpbLUCustSalesInvoices},
  PBLUProofStatus in '..\PBLUProofStatus.pas' {PBLUProofStatusFrm},
  PBMaintProofStatus in '..\PBMaintProofStatus.pas' {PBMaintProofStatusFrm},
  PBEnqInActLine in '..\PBEnqInActLine.pas' {PBEnqInActLineFrm},
  PBRSPOrd in '..\PBRSPOrd.pas' {PBRSPOrdFrm},
  PBMaintPOrdInactive in '..\PBMaintPOrdInactive.pas' {PBMaintPOrdInactiveFrm},
  pbLUPurchaseInvoiceRpts in '..\pbLUPurchaseInvoiceRpts.pas' {frmPBLUPurchaseInvoiceRpts},
  pbLUPurchaseOrderRpts in '..\pbLUPurchaseOrderRpts.pas' {frmPBLUPurchaseOrderRpts},
  PBPeriodEndDM in '..\PBPeriodEndDM.pas' {dmPeriodEnd: TDataModule},
  PBPeriodEnd in '..\PBPeriodEnd.pas' {PBPeriodEndfrm},
  pbLUSupplierRpts in '..\pbLUSupplierRpts.pas' {frmPBLUSupplierRpts},
  PBRSCapability in '..\PBRSCapability.pas' {PBRSCapabilityfrm},
  PBRSSupCap in '..\PBRSSupCap.pas' {PBRSSupCapFrm},
  PBRSSuppDet in '..\PBRSSuppDet.pas' {PBRSSuppDetFrm},
  PBMaintClient in '..\PBMaintClient.pas' {PBMaintClientFrm},
  PBAuditView in '..\PBAuditView.pas' {PBAuditViewFrm},
  STStkEnq in '..\STStkEnq.pas' {STStkEnqFrm},
  STPrtEnqMov in '..\STPrtEnqMov.pas' {STPrtEnqMovFrm},
  STStoreStockDM in '..\STStoreStockDM.pas' {DMStoreStock: TDataModule},
  STStoreStockObj in '..\STStoreStockObj.pas',
  STStoreStock in '..\STStoreStock.pas' {STStoreStockFrm},
  StMaintAgedStk in '..\StMaintAgedStk.pas' {StMaintAgedStkFrm},
  STImpSalesOrdersDM in '..\STImpSalesOrdersDM.pas' {dtmdlImpSO: TDataModule},
  STImpSalesOrders in '..\STImpSalesOrders.pas' {STImpSalesOrdersFrm},
  STRSImportAudit in '..\STRSImportAudit.pas' {STRSImportAuditfrm},
  pbLUSalesOrdersRpts in '..\pbLUSalesOrdersRpts.pas' {frmPBLUSalesOrdersRpts},
  STRPProfitRep in '..\STRPProfitRep.pas' {STRPProfitRepfrm},
  STMaintSOrdDel in '..\STMaintSOrdDel.pas' {STMaintSOrdDelfrm},
  STLUCourier in '..\STLUCourier.pas' {STLUCourierFrm},
  STMaintCourierServ in '..\STMaintCourierServ.pas' {STMaintCourierServFrm},
  STMaintCourier in '..\STMaintCourier.pas' {STMaintCourierFrm},
  STLUCourierServ in '..\STLUCourierServ.pas' {STLUCourierServFrm},
  STRSSOrderDeliv in '..\STRSSOrderDeliv.pas' {STRSSOrderDelivFrm},
  STEDIPOrd in '..\STEDIPOrd.pas' {STEDIPOrdFrm},
  STStkTakeDM in '..\STStkTakeDM.pas' {STStkTkDM: TDataModule},
  STStkTkbyPart in '..\STStkTkbyPart.pas' {STStkTkbyPartFrm},
  STStkTkItem in '..\STStkTkItem.pas' {STStkTkItemFrm},
  STStkTkObject in '..\STStkTkObject.pas',
  STStkTkRep in '..\STStkTkRep.pas' {StStkTkRepFrm},
  STStkTkSel in '..\STStkTkSel.pas' {STStkTkSelFrm},
  STStkTkSl in '..\STStkTkSl.pas' {STStkTkslfrm},
  PBMaintCustDisc in '..\PBMaintCustDisc.pas' {PBMaintCustDiscFrm},
  PBLUCustCstCntr in '..\PBLUCustCstCntr.pas' {PBLUCustCstCntrFrm},
  PBLUCustDisc in '..\PBLUCustDisc.pas' {PBLUCustDiscFrm},
  PBMaintCustCstCntr in '..\PBMaintCustCstCntr.pas' {PBMaintCustCstCntrFrm},
  PBLUSupOrdType in '..\PBLUSupOrdType.pas' {PBLUSupOrdTypeFrm},
  PBMaintSupOrdType in '..\PBMaintSupOrdType.pas' {PBMaintSupOrdTypeFrm},
  PBAccImportDM in '..\PBAccImportDM.pas' {dmAccImport: TDataModule},
  PBAccExport1 in '..\PBAccExport1.pas' {PBAccExport1Frm},
  PBAccExport2 in '..\PBAccExport2.pas' {PBAccExport2Frm},
  PBAccExport3 in '..\PBAccExport3.pas' {PBAccExport3Frm},
  PBAccExport4 in '..\PBAccExport4.pas' {PBAccExport4Frm},
  PBAccExportDM in '..\PBAccExportDM.pas' {dmAccExport: TDataModule},
  PBAccExportFactInvs in '..\PBAccExportFactInvs.pas' {PBAccExportFactInvsFrm},
  PBMaintFinanceYear in '..\PBMaintFinanceYear.pas' {PBMaintFinanceYearFrm},
  PBMaintCompanyFY in '..\PBMaintCompanyFY.pas' {PBMaintCompanyFYfrm},
  PBRSQuo in '..\PBRSQuo.pas' {PBRSQuoFrm},
  PBMaintCRep in '..\PBMaintCRep.pas' {pbMaintCRepFrm},
  PBAbout in '..\PBAbout.pas' {PBAboutFrm},
  STRPUnpaidStock in '..\STRPUnpaidStock.pas' {STRPUnpaidStockFrm},
  pbluFormReferences in '..\pbluFormReferences.pas' {frmPBLUFormReferences},
  pbFormReferenceDM in '..\pbFormReferenceDM.pas' {dtmdlForms: TDataModule},
  PBLUStkLocs in '..\PBLUStkLocs.pas' {PBLUStkLocsFrm},
  pbLUFormReferenceRpts in '..\pbLUFormReferenceRpts.pas' {frmPBLUFormReferenceRpts},
  PBRSStkVal in '..\PBRSStkVal.pas' {PBRSStkValFrm},
  PBRSStkBal in '..\PBRSStkBal.pas' {PBRSStkBalFrm},
  PBRSStkHold in '..\PBRSStkHold.pas' {PBRSStkHoldFrm},
  PBRSStkMove in '..\PBRSStkMove.pas' {PBRSStkMoveFrm},
  PBRSStkRec in '..\PBRSStkRec.pas' {PBRSStkRecFrm},
  PBRPStkVal in '..\PBRPStkVal.pas' {PBRPStkValfrm},
  PBRPStkBal in '..\PBRPStkBal.pas',
  PBRPStkHold in '..\PBRPStkHold.pas' {PBRPStkHoldfrm},
  PBRPStkMove in '..\PBRPStkMove.pas' {PBRPStkMovefrm},
  PBRPStkRec in '..\PBRPStkRec.pas' {PBRPStkRecfrm},
  PBLUStkHistory in '..\PBLUStkHistory.pas' {PBLUStkHistoryfrm},
  CCSMaintProdImages in '..\..\CCSCOMMOND7\CCSMaintProdImages.pas' {CCSMaintProdImagesFrm},
  PBRSWorksOrder in '..\PBRSWorksOrder.pas' {frmPBRSWorksOrder},
  taoMAPI in '..\..\CCSCOMMOND7\taoMAPI.pas',
  PBRPLabelsReels in '..\Quick Reports\PrintGuy\PBRPLabelsReels.pas' {PBRPLabelsReelsFrm},
  CCSProgressBar in '..\..\CCSCOMMOND7\CCSProgressBar.pas' {frmCCSProgressBar},
  STRPStockLabels in '..\STRPStockLabels.pas' {STRPStockLabelsFrm},
  PBRSJobBag in '..\PBRSJobBag.pas' {frmPBRSJobBag},
  STRPSord in '..\Quick Reports\PrintGuy\STRPSord.pas' {STRPSordFrm},
  SFJobBagLogDM in '..\..\SFDC\SFJobBagLogDM.pas' {dtmdlJobBagLog: TDataModule},
  STRPPickingNote in '..\Quick Reports\PrintGuy\STRPPickingNote.pas' {STRPPickingNoteFrm},
  PBRPCusSupLabs in '..\Quick Reports\PrintGuy\PBRPCusSupLabs.pas' {PBRPCusSupLabsFrm},
  Printer.Enums in '..\..\..\PrinterTools\Printer.Enums.pas',
  Printer.Interfaces in '..\..\..\PrinterTools\Printer.Interfaces.pas',
  Printer.Tools in '..\..\..\PrinterTools\Printer.Tools.pas';

{$R *.RES}

begin
  {$IFDEF DEBUG}
  ReportMemoryLeaksOnShutdown := True;
  {$ENDIF}
  Application.Initialize;
  Application.Title := 'PrintGuy - Redeye Print Management';
  Application.MainFormOnTaskBar := True;
  Application.CreateForm(TdmBroker, dmBroker);
  Application.CreateForm(TfrmpbMainMenu, frmpbMainMenu);
  Application.CreateForm(TPBSendFaxFrm, PBSendFaxFrm);
  Application.CreateForm(TPBImagesFrm, PBImagesFrm);
  Application.CreateForm(TdmLetter, dmLetter);
  Application.CreateForm(TPBAuditDataMod, PBAuditDataMod);
  Application.Run;
end.
